# Cleaning/Harmonizing Corpora & Add the language codes from the formulars

Objective: clean the raw data to obtain the original non-filtered version of the texts (to compare with the filtered version and create a middle version suitable for sentencizer/tokenization and pos-tagging)

Work done in this notebook:
- remove unnecessary columns from dataframes
- insert col for ISO codes
- concat dataframes per corpora
- insert col for corpora
- concat all into one dataframe
- add the lang id from formulars

#### Importations

In [ ]:
!pip uninstall numpy spacy -y
!pip install "numpy==1.26.4"
!pip install spacy

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 617, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Elise\anaconda3\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\Elise\\AppData\\Local\\Temp\\pip-uninstall-od6zw27n\\numpy\\fft\\_pocketfft_internal.cp311-win_amd64.pyd'

Collecting numpy==1.26.4
  Obtaining dependency information for numpy==1.26.4 from https://files.pythonhosted.org/packages/3f/6b/5610004206cf7f8e7ad91c5a85a8c71b2f2f8051a0c0c4d5916b76d6cbb2/numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4

WARNING: Ignoring invalid distribution ~umpy (C:\Users\Elise\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~umpy (C:\Users\Elise\anaconda3\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.8.0 requires blosc2~=2.0.0, which is not installed.
tables 3.8.0 requires cython>=0.29.21, which is not installed.
feature-engine 1.8.0 requires scikit-learn>=1.4.0, but you have scikit-learn 1.3.0 which is incompatible.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.90 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

In [1]:
import pandas as pd
import numpy as np 
#import spacy

C:\Users\Elise\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

### 1. Importation of the files, exploitation of the statistics, removal of unnecessary data
#### a. Files' importation

In [3]:
df_fnw_gcf = pd.read_csv("fineweb2_gcf_concat.csv")
df_fnw_gcr = pd.read_csv("fineweb2_gcr_concat.csv")
df_fnw_hat = pd.read_csv("fineweb2_hat_concat.csv")
df_glotcc_gcf = pd.read_csv("glotcc_gcf.csv")
df_glotcc_gcr = pd.read_csv("glotcc_gcr.csv")
df_glotcc_hat = pd.read_csv("glotcc_hat.csv")

In [5]:
df_fnw_gcf

,text,id,media,metadata
0,billet - chronique\n- Détails\n- Publié le sam...,<urn:uuid:8b665f6d-1ec7-413f-9560-fbd0b941d22f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://gen..."
1,Dékré konmkwa lestravay aboli adan tout koloni...,<urn:uuid:a6ef2d6f-d2d6-4fa4-9f50-d0f0a10b4396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://ord..."
2,"Il y a deux ans était publié, sous la houlette...",<urn:uuid:f8a9a3d0-268c-4b0c-9ba4-6d439484a396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
3,"""Counter Strike Source""\nCounter Strike Source...",<urn:uuid:45222417-204e-456c-8f4f-039d1210c351>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
4,\n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...,<urn:uuid:e487404b-555a-4459-ad01-5c66f450a070>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
5,"Mas An Nou, sé Mas a neg Gwadloup, sé Mas a mo...",<urn:uuid:8eace61a-1191-463b-bc70-bb0b54b56f9f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://mas..."
6,"Messié, Dam, sé MetoBôkay ka palé ba zôt!\nDé ...",<urn:uuid:1661751a-bdeb-4d60-a524-4e50ab8fc32c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://met..."
7,"Dèpi lendi, an monté ba zòt on blòg ww otila a...",<urn:uuid:96d834b7-93b8-4643-9ab4-e479d71e2aab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://sha..."
8,« Bobòn fwa…\nTwa fwa bel kont ! »\nRann sèvis...,<urn:uuid:4d61ce30-164c-4b86-9d34-897fb209e916>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
9,\n\nPa rapôt a travay oben pou dé rézon pli pè...,<urn:uuid:db19b73b-61a0-41aa-90d6-d44004580c76>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
10,billet - chronique\n- Détails\n- Publié le lun...,<urn:uuid:485b0675-1c1f-4b41-89b6-47707fcf7f4a>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
11,[ Refrain ]\nShabine Glindor Miss Docterous Gi...,<urn:uuid:5cd2dc22-16b8-4267-b9ab-c36c59186f26>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
12,L’écriture en langue créole s’est d’abord dépl...,<urn:uuid:4ca9dd6b-5a05-4347-acbe-254c521e8a4c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
13,Player mode on | off\nGrid\nList\n02:48Watch l...,<urn:uuid:0bd9d00e-459c-44d0-b75a-59e3ee42a032>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
14,Sé dépi lanné 2.000 an asosiyasion Chinwa l’Af...,<urn:uuid:b58e621b-2f14-49c9-b335-e76b338f92b6>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
15,"[Intro] :\nYeah !!, Brasco (Brasco)\nHey gué c...",<urn:uuid:3c8ba6a5-db13-4c9b-ae42-07ba3a815733>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
16,billet - chronique\n- Détails\n- Catégorie : B...,<urn:uuid:d876e575-e705-44b5-91db-d96e6e299e5e>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://gen..."
17,Sé jou-tala pétrolet Madinina an vèdet. Sé cho...,<urn:uuid:d3ca1c60-a08c-4e9d-a875-ba05ab75d03a>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
18,an chèché ... an pas touvé ...\nalò .... an ka...,<urn:uuid:18e81c5b-1631-4900-b659-b6b4721c7cb8>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
19,Man pé ké mélanjé sa ou fè an politik épi sa’w...,<urn:uuid:4cdfc40e-bac9-47ae-a1bc-e45971c638cf>,[],"{'dump': 'CC-MAIN-2014-23', 'url': 'http://www..."
20,"La mwen té près fin tout lantou en mwen, en té...",<urn:uuid:db6b202e-c9d6-4ab1-b36e-41f0e2c25ef0>,[],"{'dump': 'CC-MAIN-2014-42', 'url': 'http://www..."
21,Le drapeau d'Haïti est rouge et bleu organisé ...,<urn:uuid:c138fc4e-6173-4ffc-9a22-e33a0cff2a0f>,[],"{'dump': 'CC-MAIN-2015-22', 'url': 'http://www..."
22,Léssé mwen diw jan ou té ka manké mwen La nost...,<urn:uuid:15fab596-9108-479a-ac56-393d7b9dfa9a>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
23,Kouté nou\nLecture automatique sauf pour\n(Cli...,<urn:uuid:a38aad9e-547b-4409-9cab-21c58c41320f>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
24,"On lè, fanm touvé-yo las pran kou anba men a n...",<urn:uuid:1df21096-5351-4e16-91eb-0677be57d943>,[],"{'dump': 'CC-MAIN-2016-36', 'url': 'http://dya..."
25,"Ki Amérendien, ki Afriken, ki Zendien, ki Blan...",<urn:uuid:714615e2-37b4-4af3-bdf6-e3dde81cafab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
26,Site de promotion des cultures et des langues ...,<urn:uuid:1c674fe2-d547-4528-a685-becee13c687c>,[],"{'dump': 'CC-MAIN-2017-13', 'url': 'http://pot..."
27,"Tini déserten moun, yo toujou ka chèché-touvé ...",<urn:uuid:5b227398-adf2-407e-9b99-373900017ef2>,[],"{'dump': 'CC-MAIN-2017-22', 'url': 'http://mon..."
28,-\n-\n-\nPar SHAKA (Gwakafwika) le 1 Septembre...,<urn:uuid:f16c0d4c-7b6b-49b3-b333-d2ed22260c8a>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://gwa..."
29,A pies kalté moman yo pa santi ki andidan pep-...,<urn:uuid:74d63b73-c97a-4532-8d67-2ce3f3b6e9cf>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://mon..."
30,"An mwa mé-la ki pasé la, té ni twa kongré ki f...",<urn:uuid:6cf1a325-4c44-49a3-9901-ad6f3cee8f8c>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'http://car..."
31,Corrigé Exercice n° 1\nLes particules pré-verb...,<urn:uuid:288c580f-3a86-4688-a5ee-b9ee6a8c50d8>,[],"{'dump': 'CC-MAIN-2017-51', 'url': 'http://cre..."
32,"Pa plita ki an midi a, man tann an granmoun ka...",<urn:uuid:a6dc41d7-a049-4700-8471-1cd4a4e14b91>,[],"{'dump': 'CC-MAIN-2018-05', 'url': 'http://mon..."
33,Chalè té ka lévé anba wob Létisia kifè manzel ...,<urn:uuid:3717d539-2401-4c49-996a-a4ed542d7a80>,[],"{'dump': 'CC-MAIN-2018-22', 'url': 'http://www..."
34,"Chofè an retrè, mé pa laritret\nSé sa tout sé ...",<urn:uuid:eb73bd59-9ec3-483b-a89f-b7ccd06a8d74>,[],"{'dump': 'CC-MAIN-2019-04', 'url': 'http://mon..."
35,Tan ka bay. Mémwè ka chonjé. Wi ! Lot jou a la...,<urn:uuid:f3dcca57-69b7-4a70-b0bd-d4c53d8a75b1>,[],"{'dump': 'CC-MAIN-2019-22', 'url': 'http://mon..."
36,Pawòl-palé a moun Lésent é ta moun Déhé pa tou...,<urn:uuid:f2ec55cb-4315-4582-976d-79ddc8be0633>,[],"{'dump': 'CC-MAIN-2019-30', 'url': 'http://www..."
37,Gadé vidéo-a ki pli ba teks-tala ! Sa nou ka w...,<urn:uuid:84aceb86-c508-486a-a1da-df152d55bde4>,[],"{'dump': 'CC-MAIN-2019-51', 'url': 'http://mon..."
38,Mètfédàm : En hommage à Gerty Archimède\nOu té...,<urn:uuid:8b0b2c88-8970-4caa-bd63-0807af416b1b>,[],"{'dump': 'CC-MAIN-2020-16', 'url': 'https://ww..."
39,Dékouvè kijan réinyon an nou ka déwoulé é touv...,<urn:uuid:389ed822-57e3-4323-b9b6-ad87b85ecce8>,[],"{'dump': 'CC-MAIN-2020-50', 'url': 'https://ww..."
40,"Nou ka goumen pou siklotwon, nou ka goumen pou...",<urn:uuid:851cae32-94cf-4f5a-b228-3217aa84b8f9>,[],"{'dump': 'CC-MAIN-2021-04', 'url': 'http://www..."
41,"Dézienm bagay nou pé konstaté tou, sé ki l'Eko...",<urn:uuid:16940138-2bf9-41d3-8e31-e324112b8b0d>,[],"{'dump': 'CC-MAIN-2021-17', 'url': 'http://mon..."
42,"Jòdijou, kontel an zwézo yo démaré zel-li, lan...",<urn:uuid:2753ab82-728a-4d99-a233-5d1cb5b2d22c>,[],"{'dump': 'CC-MAIN-2021-43', 'url': 'https://ww..."
43,« Roch dan dlo pa konnet doulè roch dan solèy”...,<urn:uuid:3b0fd1d0-acac-4b4c-a9d6-c56f4a6d54bc>,[],"{'dump': 'CC-MAIN-2022-21', 'url': 'http://jud..."
44,"Dans le cadre du Festival haïtien ""FESTIVAL EN...",<urn:uuid:015c422e-5170-43c3-90d1-85a4af49665f>,[],"{'dump': 'CC-MAIN-2023-06', 'url': 'https://fo..."
45,Description\nDégajé & Pwòpté\nTin plizyè jan p...,<urn:uuid:534f732a-490f-4b33-924a-2e4c8e9b619f>,[],"{'dump': 'CC-MAIN-2023-14', 'url': 'https://ww..."
46,Man té ka travay épi Maksimilien LIMINO. Misié...,<urn:uuid:bedd30ca-4e19-4cb3-a83f-204a8565623b>,[],"{'dump': 'CC-MAIN-2023-40', 'url': 'https://mo..."

### 2. Removal of unnecessary info, lang ID column added, concatenation of dataframe per corpus
#### a. Removal of all columns except text/content + iso code column added

In [8]:
# fineweb2
print(list(df_fnw_gcf.columns.values))

['text', 'id', 'media', 'metadata']

In [10]:
cols_to_remove = ["id", "media", "metadata"]
df_fnw_gcf = df_fnw_gcf.drop(columns=cols_to_remove)
df_fnw_gcr = df_fnw_gcr.drop(columns=cols_to_remove)
df_fnw_hat = df_fnw_hat.drop(columns=cols_to_remove)

In [12]:
df_fnw_gcf["iso-639-3"] = "gcf"
df_fnw_gcr["iso-639-3"] = "gcr"
df_fnw_hat["iso-639-3"] = "hat"

In [14]:
df_fnw_gcr

                                                 text iso-639-3
0   VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...       gcr
1   Lé ven senk(25) mè démildis(2010) tout éléktér...       gcr
2   Communique de presse du 16 octobre 2013\nALE L...       gcr
3   1)LONI : POUKISA LAGWIYANN NOU PA ANNAN SA ?\n...       gcr
4   Lo nou té wè lit bann moun-yan ki té jwenn ann...       gcr
5   KAYENN « MINING SYMPOSIUM »\nPoukisa yé rivé f...       gcr
6   Mo ka sonjé pronmyè fwè mo tandé sa zafè rakab...       gcr
7   Site de promotion des cultures et des langues ...       gcr
8   Trwa variété di grenn di lanti kiltivé.\nSerte...       gcr
9   Mo té ké lé li sa artik-a %%?\nChak lannen, Té...       gcr
10  Mo té ké lé li sa artik-a %%?\nLanmizik pou la...       gcr
11  Abandonnen sa ki mal. 1 Corinthiens 6:9, 10\nS...       gcr
12  Mo té ké lé li sa artik-a %%?\nLiv ké brochir ...       gcr
13  Grann Dépresyon\nGrann Déprésyon-an (The Great...       gcr
14  Ion\nOun ion oben yon est sa roun atom oben ro...       gcr
15  Jé di sosyété\nJé di sosyété-a sa roun jé ki k...       gcr
16  Tablo péryodik di sé éléman\nTablo péryodik dé...       gcr
17  Artiri\nNou ka aplé artiri ansanm-an dé arm ko...       gcr
18  Entéraksyon fèb\nEntéraksyon fèb-a (osi aplé f...       gcr
19  Sa paj ka konsèrné lannen 1156 di kalandriyé j...       gcr
20  15 Mé mo menm mo pa profité di sa bagaj-ya pyè...       gcr

In [16]:
# Glotcc
print(list(df_glotcc_gcf.columns.values))

['content', 'warc-target-uri', 'warc-date', 'warc-record-id', 'quality-warnings', 'categories', 'identification-language', 'identification-prob', 'identification-consistency', 'script-percentage', 'num-sents', 'content-length', 'tlsh']

In [18]:
cols = ['warc-target-uri', 'warc-date', 'warc-record-id', 'quality-warnings', 'categories', 'identification-language', 'identification-prob', 'identification-consistency', 'script-percentage', 'num-sents', 'content-length', 'tlsh']
df_glotcc_gcf = df_glotcc_gcf.drop(columns=cols)
df_glotcc_gcr = df_glotcc_gcr.drop(columns=cols)
df_glotcc_hat = df_glotcc_hat.drop(columns=cols)

In [20]:
df_glotcc_gcf

                                              content
0   Popozision ki sòti nan Konsit LLKM za òganizé,...
1   Kantapou létjip Lafrans fanm, yo mennen bon mo...
2   Lanné 2017 ka komansé, lokazyon pou viré jété ...
3   ADN Awa !, 14 février 1952, 14 décembre 2010, ...
4   Lendi bonmaten, anlo moun té anrajé anlè lawou...
5   House of Àṣẹ (pwononsé a-ché) sé on koté èspés...
6   An ay fè on lantou Brisèl é an pa vwè pon-on m...
7   Cette nouvelle lecture devrait se faire aiséme...
8   Dimanch pasé tout moun té douvan télé-yo pou t...
9   Aaaah arrété fè mwen chié dé labiè mwen brè Ou...
10  Lasimenn pasé té ja ka ba’y nef jou moun té ka...
11  ADN Awa !, 14 février 1952, 14 décembre 2010, ...
12  Popozision ki sòti nan Konsit LLKM za òganizé,...
13  Sé nan lanné 1981 an éti an krey manmay ki té ...
14  Senkan apré i pati an péyi san chapo, Neg fond...
15  Sé sa anlo moun ka mandé, mé sa vré, lè an bag...
16  « Manman, lagrev baré mwen, misié Michel pa lé...
17  Magré mwa mas-la dit dépi lontan, ni anlo moun...
18  Le 22 septembre dernier, les amies et camarade...
19  Cliquez ici pour aller directement à la méthod...
20  (extraits d'une interview de Katrin René-St-El...
21  Apré on Bac Litérè an Gwadloup, an pasé dé lan...
22  Misié té ka fè wol mò, pas anlo moun té lé tér...
23  Luil ésansiyèl a vétivè (Vetiveria zizanioides...
24  Pou moun ki ka di kréyòl pé pa maké, sa pa vré...

In [22]:
df_glotcc_gcf["iso-639-3"] = "gcf"
df_glotcc_gcr["iso-639-3"] = "gcr"
df_glotcc_hat["iso-639-3"] = "hat"

In [24]:
df_glotcc_hat

                                              content iso-639-3
0   AfrikaansAzərbaycanBahasa IndonesiaBasa jawabo...       hat
1   Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...       hat
2   Prezidan Joe Biden te byen resevwa lòt jou la ...       hat
3   Ningbo Hongtai te etabli an 2004, ki chita nan...       hat
4   Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...       hat
5   Michel DeGraff nan TEDx @MIT — Lang gen gwo po...       hat
6   An menm tan an, li tou gen reyaksyon carboxyl ...       hat
7   Jou ki te 31 desanm 2019 la, kèk manm ANVA te ...       hat
8   1 Jésus te antre nan yon kannòt pou travèse dl...       hat
9   Entwodiksyon Radiant P4 fleksib ekspozisyon di...       hat
10  * Remak: Inite koule a se estanda mèt kib/èdta...       hat
11  Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...       hat
12  2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...       hat

#### b. Concatenation per corpus + adding of corpus column

In [26]:
# concatenation fnw
df_fnw = pd.concat([df_fnw_gcf, df_fnw_gcr, df_fnw_hat], ignore_index=True)
df_fnw

                                                 text iso-639-3
0   billet - chronique\n- Détails\n- Publié le sam...       gcf
1   Dékré konmkwa lestravay aboli adan tout koloni...       gcf
2   Il y a deux ans était publié, sous la houlette...       gcf
3   "Counter Strike Source"\nCounter Strike Source...       gcf
4   \n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...       gcf
..                                                ...       ...
93  À partir de ce lundi 13 jusqu’au 17 mars, l’As...       hat
94  Nan Montrouis, bò pòtay Latibonit. Sou twotwa ...       hat
95  Konpayi nou an te patisipe nan 16yèm Egzibisyo...       hat
96  \n\n1 Korint 9Haitian Creole Version (HCV)\n9 ...       hat
97  Nov 02, 2017\nYon compressésLè mande tretman m...       hat

[98 rows x 2 columns]

In [28]:
df_fnw["original-corpus"] = "fineweb2"
df_fnw

,text,iso-639-3,original-corpus
0,billet - chronique\n- Détails\n- Publié le sam...,gcf,fineweb2
1,Dékré konmkwa lestravay aboli adan tout koloni...,gcf,fineweb2
2,"Il y a deux ans était publié, sous la houlette...",gcf,fineweb2
3,"""Counter Strike Source""\nCounter Strike Source...",gcf,fineweb2
4,\n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...,gcf,fineweb2
...,...,...,...
93,"À partir de ce lundi 13 jusqu’au 17 mars, l’As...",hat,fineweb2
94,"Nan Montrouis, bò pòtay Latibonit. Sou twotwa ...",hat,fineweb2
95,Konpayi nou an te patisipe nan 16yèm Egzibisyo...,hat,fineweb2
96,\n\n1 Korint 9Haitian Creole Version (HCV)\n9 ...,hat,fineweb2
97,"Nov 02, 2017\nYon compressésLè mande tretman m...",hat,fineweb2

In [30]:
# concatenation glotcc
df_glotcc = pd.concat([df_glotcc_gcf, df_glotcc_gcr, df_glotcc_hat], ignore_index=True)
df_glotcc["original-corpus"] = "glotcc"
df_glotcc

,content,iso-639-3,original-corpus
0,"Popozision ki sòti nan Konsit LLKM za òganizé,...",gcf,glotcc
1,"Kantapou létjip Lafrans fanm, yo mennen bon mo...",gcf,glotcc
2,"Lanné 2017 ka komansé, lokazyon pou viré jété ...",gcf,glotcc
3,"ADN Awa !, 14 février 1952, 14 décembre 2010, ...",gcf,glotcc
4,"Lendi bonmaten, anlo moun té anrajé anlè lawou...",gcf,glotcc
5,House of Àṣẹ (pwononsé a-ché) sé on koté èspés...,gcf,glotcc
6,An ay fè on lantou Brisèl é an pa vwè pon-on m...,gcf,glotcc
7,Cette nouvelle lecture devrait se faire aiséme...,gcf,glotcc
8,Dimanch pasé tout moun té douvan télé-yo pou t...,gcf,glotcc
9,Aaaah arrété fè mwen chié dé labiè mwen brè Ou...,gcf,glotcc
10,Lasimenn pasé té ja ka ba’y nef jou moun té ka...,gcf,glotcc
11,"ADN Awa !, 14 février 1952, 14 décembre 2010, ...",gcf,glotcc
12,"Popozision ki sòti nan Konsit LLKM za òganizé,...",gcf,glotcc
13,Sé nan lanné 1981 an éti an krey manmay ki té ...,gcf,glotcc
14,"Senkan apré i pati an péyi san chapo, Neg fond...",gcf,glotcc
15,"Sé sa anlo moun ka mandé, mé sa vré, lè an bag...",gcf,glotcc
16,"« Manman, lagrev baré mwen, misié Michel pa lé...",gcf,glotcc
17,"Magré mwa mas-la dit dépi lontan, ni anlo moun...",gcf,glotcc
18,"Le 22 septembre dernier, les amies et camarade...",gcf,glotcc
19,Cliquez ici pour aller directement à la méthod...,gcf,glotcc
20,(extraits d'une interview de Katrin René-St-El...,gcf,glotcc
21,"Apré on Bac Litérè an Gwadloup, an pasé dé lan...",gcf,glotcc
22,"Misié té ka fè wol mò, pas anlo moun té lé tér...",gcf,glotcc
23,Luil ésansiyèl a vétivè (Vetiveria zizanioides...,gcf,glotcc
24,"Pou moun ki ka di kréyòl pé pa maké, sa pa vré...",gcf,glotcc
25,Jupiter (senbòl : ) sa roun planèt jéyant gazé...,gcr,glotcc
26,"Hiver : kanpangn di Boleslas III Bouche-Torse,...",gcr,glotcc
27,Friedrich Wilhelm Nietzsche (prounonsé [ˈfʁiːd...,gcr,glotcc
28,Rock-a sa roun janr mizikal ki aparèt andan la...,gcr,glotcc
29,"Adi Shankara (sanskri : Ādi Śaṅkara, devanagar...",gcr,glotcc
30,Jen : èspédisyon di Saladin à lès-a di Jourdai...,gcr,glotcc
31,"Bahamas, an form long Commonwealth dé Bahamas,...",gcr,glotcc
32,"10 mè : lanprò-a di Mali Kanga Moussa, ki pati...",gcr,glotcc
33,"21 mè : dé navir fransé, ki koumandé pa August...",gcr,glotcc
34,26 jen : Palman ékosè-a ka ògtrwayé monnonpòl-...,gcr,glotcc
35,Bondjé ka dézigné oun fika oben fòs souprenm k...,gcr,glotcc
36,Jayinism-an oben jinism-an (du sanskrit : जैनम...,gcr,glotcc
37,11 janvyé : tout koumèrs dirèk ant Filipin-yan...,gcr,glotcc
38,AfrikaansAzərbaycanBahasa IndonesiaBasa jawabo...,hat,glotcc
39,Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...,hat,glotcc
40,Prezidan Joe Biden te byen resevwa lòt jou la ...,hat,glotcc
41,"Ningbo Hongtai te etabli an 2004, ki chita nan...",hat,glotcc
42,Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...,hat,glotcc
43,Michel DeGraff nan TEDx @MIT — Lang gen gwo po...,hat,glotcc
44,"An menm tan an, li tou gen reyaksyon carboxyl ...",hat,glotcc
45,"Jou ki te 31 desanm 2019 la, kèk manm ANVA te ...",hat,glotcc
46,1 Jésus te antre nan yon kannòt pou travèse dl...,hat,glotcc
47,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
48,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
49,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
50,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [32]:
# final concatenation of the two dataframes 
df_glotcc = df_glotcc.rename(columns={"content": "text"}) # change glotcc 'content' column header into 'text', to align with fineweb2
df_fnw_glotcc = pd.concat([df_fnw, df_glotcc], ignore_index=True)
df_fnw_glotcc

,text,iso-639-3,original-corpus
0,billet - chronique\n- Détails\n- Publié le sam...,gcf,fineweb2
1,Dékré konmkwa lestravay aboli adan tout koloni...,gcf,fineweb2
2,"Il y a deux ans était publié, sous la houlette...",gcf,fineweb2
3,"""Counter Strike Source""\nCounter Strike Source...",gcf,fineweb2
4,\n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...,gcf,fineweb2
...,...,...,...
144,1 Jésus te antre nan yon kannòt pou travèse dl...,hat,glotcc
145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [34]:
print(df_fnw_glotcc["iso-639-3"].value_counts())

iso-639-3
gcf    72
hat    43
gcr    34
Name: count, dtype: int64

In [36]:
print(df_fnw_glotcc["original-corpus"].value_counts())

original-corpus
fineweb2    98
glotcc      51
Name: count, dtype: int64

In [38]:
# adding index as columns
df_fnw_glotcc.reset_index(level=0, inplace=True)
df_fnw_glotcc

,index,text,iso-639-3,original-corpus
0,0,billet - chronique\n- Détails\n- Publié le sam...,gcf,fineweb2
1,1,Dékré konmkwa lestravay aboli adan tout koloni...,gcf,fineweb2
2,2,"Il y a deux ans était publié, sous la houlette...",gcf,fineweb2
3,3,"""Counter Strike Source""\nCounter Strike Source...",gcf,fineweb2
4,4,\n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...,gcf,fineweb2
...,...,...,...,...
144,144,1 Jésus te antre nan yon kannòt pou travèse dl...,hat,glotcc
145,145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
146,146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
147,147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
148,148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [42]:
df_fnw_glotcc.to_csv("fineweb2_glotcc_4C.csv", index=False)

### 3. Adding of document-level language tags + conllu files out per corpora

In [4]:
df_data_all_lang = pd.read_csv("fineweb2_glotcc_4C_all_clean.csv")
df_data_all_lang.head()

,index,text,iso-639-3,original-corpus
0,0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2
1,1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2
2,2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2
3,3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2
4,4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2

In [6]:
# changer le nom de la colonne iso !!
df_data_all_lang.rename(columns={'iso-639-3': 'original-lang-tag'}, inplace=True)
df_data_all_lang

,index,text,original-lang-tag,original-corpus
0,0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2
1,1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2
2,2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2
3,3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2
4,4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2
...,...,...,...,...
144,144,Mat 4:13. Jésus te antre nan yon kannòt pou tr...,hat,glotcc
145,145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc
146,146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc
147,147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc
148,148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc

In [8]:
df_new_tags = pd.read_csv(r"C:\Users\Elise\Desktop\STAGE\Thèse\Cleaning2_bis_langID_added\Index_DocAnnot_from_formulars.tsv", sep="\t")
df_new_tags

     index form-tag glottocode-tag wals-tag
0        0      MAR        gcf-mar      mqc
1        1      GUA        gcf-gua      gdl
2        2      MAR        gcf-mar      mqc
3        3      GUA        gcf-gua      gdl
4        4      GUA        gcf-gua      gdl
..     ...      ...            ...      ...
144    144      HAI            hat      hcr
145    145      HAI            hat      hcr
146    146      HAI            hat      hcr
147    147      HAI            hat      hcr
148    148      HAI            hat      hcr

[149 rows x 4 columns]

In [10]:
# Extract the old and the new tags to compare first!
original_code_list = list(df_data_all_lang["original-lang-tag"])
glottocode_tag_list = list(df_new_tags["glottocode-tag"]) # 2e colonne
print(original_code_list, "\n", glottocode_tag_list)

['gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcf', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat']
 ['gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-mar', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-gua', 'gcf-mar', 'gcf-gua', 'gcf-mar', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'gcr', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat', 'hat']

In [12]:
print(f"Numbers of texts in Martinican: {glottocode_tag_list.count('gcf-mar')}\nNumbers of texts in Guadeloupean: {glottocode_tag_list.count('gcf-gua')}\nNumbers of texts in Guyanese: {glottocode_tag_list.count('gcr')}\nNumbers of texts in Haitian: {glottocode_tag_list.count('hat')}")

Numbers of texts in Martinican: 37
Numbers of texts in Guadeloupean: 35
Numbers of texts in Guyanese: 33
Numbers of texts in Haitian: 44

In [14]:
# evaluation of the original tags -> collapsed 3-class precision/recall/F1 (0 granularity for gcf cases -> always said correct)
from sklearn.metrics import classification_report, confusion_matrix

collapse = {"gcf": "gcf", "gcf-mar": "gcf", "gcf-gua": "gcf", "gcr": "gcr", "hat": "hat"}
gold = [collapse[l] for l in glottocode_tag_list]
basic = original_code_list

print(classification_report(gold, basic, labels=["gcf", "gcr", "hat"]))
print(confusion_matrix(gold, basic, labels=["gcf", "gcr", "hat"]))

              precision    recall  f1-score   support

         gcf       1.00      1.00      1.00        72
         gcr       0.97      1.00      0.99        33
         hat       1.00      0.98      0.99        44

    accuracy                           0.99       149
   macro avg       0.99      0.99      0.99       149
weighted avg       0.99      0.99      0.99       149

[[72  0  0]
 [ 0 33  0]
 [ 0  1 43]]

In [16]:
# Evaluation of the original tags -> hierarchical Precision/Recall/F1

from collections import Counter

# Defining parent relationships (a label's ancestors, not including itself) -> gold tags as ancestors, ancestors as keys in the dict
parents = {
    "gcf": [],
    "gcf-mar": ["gcf"],
    "gcf-gua": ["gcf"],
    "gcr": [],
    "hat": [],
}

def expand(label):
    """Return the set of a label plus all its ancestors."""
    result = {label}
    to_process = [label]
    while to_process:
        current = to_process.pop()
        for p in parents.get(current, []):
            if p not in result:
                result.add(p)
                to_process.append(p)
    return result

def hierarchical_prf(basic_labels, gold_labels):
    """
    basic_labels, gold_labels: parallel lists of string labels, one per document.
    Returns (precision, recall, f1) computed over the whole set (micro-averaged,
    the standard way hierarchical P/R/F1 is reported).
    """
    numerator = 0
    basic_total = 0
    gold_total = 0

    for b, g in zip(basic_labels, gold_labels):
        exp_b = expand(b)
        exp_g = expand(g)
        numerator += len(exp_b & exp_g)
        basic_total += len(exp_b)
        gold_total += len(exp_g)

    hP = numerator / basic_total if basic_total else 0.0
    hR = numerator / gold_total if gold_total else 0.0
    hF1 = 2 * hP * hR / (hP + hR) if (hP + hR) else 0.0

    return hP, hR, hF1

hP, hR, hF1 = hierarchical_prf(basic, gold)
print(f"Hierarchical Precision: {hP:.3f}")
print(f"Hierarchical Recall:    {hR:.3f}")
print(f"Hierarchical F1:        {hF1:.3f}")

Hierarchical Precision: 0.993
Hierarchical Recall:    0.993
Hierarchical F1:        0.993

In [18]:
# Evaluation of the original tags -> hierarchical evaluation per category (all)

def hierarchical_prf_by_gold_class(basic_labels, gold_labels):
    by_class = {}
    classes = sorted(set(gold_labels))
    for cls in classes:
        idxs = [i for i, g in enumerate(gold_labels) if g == cls]
        b_sub = [basic_labels[i] for i in idxs]
        g_sub = [gold_labels[i] for i in idxs]
        by_class[cls] = hierarchical_prf(b_sub, g_sub)
    return by_class

for cls, (p, r, f1) in hierarchical_prf_by_gold_class(basic, glottocode_tag_list).items():
    print(f"{cls:10s}  hP={p:.3f}  hR={r:.3f}  hF1={f1:.3f}")

gcf-gua     hP=1.000  hR=0.500  hF1=0.667
gcf-mar     hP=1.000  hR=0.500  hF1=0.667
gcr         hP=1.000  hR=1.000  hF1=1.000
hat         hP=0.977  hR=0.977  hF1=0.977

In [20]:
# Evaluation of the original tags -> hierarchical evaluation per category (gcf-mar & gcf-gua only)

def hierarchical_prf_filtered(basic_labels, gold_labels, gold_subset):
    idxs = [i for i, g in enumerate(gold_labels) if g in gold_subset]
    b_sub = [basic_labels[i] for i in idxs]
    g_sub = [gold_labels[i] for i in idxs]
    return hierarchical_prf(b_sub, g_sub)

hP, hR, hF1 = hierarchical_prf_filtered(basic, glottocode_tag_list, {"gcf-mar", "gcf-gua"})
print(f"gcf subtypes combined — hP={hP:.3f}  hR={hR:.3f}  hF1={hF1:.3f}")

gcf subtypes combined — hP=1.000  hR=0.500  hF1=0.667

In [22]:
# And then add the new tags into the dataset df to create language-separated corpora (conllu files)

wals_tag_list = list(df_new_tags["wals-tag"])
df_data_all_lang['new-lang-tag'] = wals_tag_list

df_data_all_lang

,index,text,original-lang-tag,original-corpus,new-lang-tag
0,0,"[...] Sé jou-tala, ou sé di nou ka tonbé bien ...",gcf,fineweb2,mqc
1,1,"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-...",gcf,fineweb2,gdl
2,2,Man pé palé di Jean Bernabé an manniè ki lib d...,gcf,fineweb2,mqc
3,3,Counter Strike Source yo ka kriyéy osi CSS.\nS...,gcf,fineweb2,gdl
4,4,"Moun ki konnèt tibwen listwa a péyi Ayiti, yo ...",gcf,fineweb2,gdl
...,...,...,...,...,...
144,144,Mat 4:13. Jésus te antre nan yon kannòt pou tr...,hat,glotcc,hcr
145,145,Entwodiksyon Radiant P4 fleksib ekspozisyon di...,hat,glotcc,hcr
146,146,* Remak: Inite koule a se estanda mèt kib/èdta...,hat,glotcc,hcr
147,147,Diksyonè Kreyòl Vilsen (Haitian Creole Monolin...,hat,glotcc,hcr
148,148,2024 Konsèvasyon Atizay Konsèvasyon Atizay Pwo...,hat,glotcc,hcr

In [24]:
# to group the texts according to the gold standard
grouped = df_data_all_lang.groupby("new-lang-tag")["text"].apply(" ".join)
corpus_mqc = grouped["mqc"]
corpus_gdl = grouped["gdl"]
corpus_gfr = grouped["gfr"]
corpus_hcr = grouped["hcr"]

In [26]:
grouped

new-lang-tag
gdl    [...]\nAn non pèp fransé-a,\nGouvèlman fransé-...
gfr    VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...
hcr    [...]\nUSC foutbòl Jwè bati kay yo an Ayiti.\n...
mqc    [...] Sé jou-tala, ou sé di nou ka tonbé bien ...
Name: text, dtype: object

In [28]:
corpus_gdl

"[...]\nAn non pèp fransé-a,\nGouvèlman fransé-a ka konssidéré ki lestravay sé an koutba kont dignité moun. Ika konsidéré ki, lè ou ka détwi tout posibilité moun té pou ni di gouvèné kòy limenm, ou ka dè dé bagay disparèt. Sé dé bagay-tala pa dòtki, baz natirel limanité menm sa ou ni dwa ni, épi sa yo andwa ba’w.\nI ka konsidéré ki, yo ka anvyolé manman-chous Larépiblik, kivédi Liberté, Ègalité, Fratènitè.\nI ka konsidéré ki, si yonn dé dispozisyon pa té ka vini lamenm déyè règ konduit poklamasyon abolisyon-an, an brigandaj san manman té ké mèt adan sé koloni-an.\nGouvèlman fransé mété dékré-tala doubout :\nPriméy pwen\nLestravay kay aboli, nèt, adan tout koloni, tout mòso tè ki ta Lafrans, dé mwaapré laplikasyon lwa-tala adoptéé. Adan yo shak-la, di jou lapalikasyon dékré-a koumansé fè shimen’y, adan koloni, tout kalté chatiman éti moun\nka ba moun kou, tout kalité lavan éti moun ka vann moun, sa pa pou fèt pyès ankò ; sa entèdi.\nDézyèm pwen\nTafè oblijé moun Sénégal angajé kòy pandan antan, ki i lé, ki i da lé sa bout.\nTwazyèm pwen\nSé sé gouvènè-a obencé kaomisè jénéral Larépiblik-la, ki ké ni pou asiré libèté pèp Matinik, pèp Gwadloup épi pèp lilet lantou’y, pèp Lagiyan, pèp Sénégal, pèp tout dòt bò lakòt west lafrik éti Lafrans établi dòy, pèp mayòt, pèp lilet ki lantou’y èk pèp Laljèri.\nKatyèm pwen\nSa ki té esklav épi ki sé ni kondanasyon ki ka mété nonm pli ba ki nonm, oben ki sé ni penn korèksyonèl pou dé bagay an nonm lib pa té ké ni tousa lapenn pou fè, lalwa ka éfasé sé kondanasyon-tala. Tout dépòté ki té ka sibi mizi gouvèlman té pwan kont yo, té rantré kay yo.\nSentyèm pwen\nLasanblé National ké réglé chak pa déonmajman kolon sé ni pou touché.\nSizyèm pwen\nSé koloni nou an ki pa ni esklav ankò, épi tè nou ni Lézend, ké ni délégasyon yo Lasanblé Nasyonal.\nSétyèm pwen\nTèg jénéral la ki ka di « dépi ou pozé pyé an Frans si ou esklav, ou lib » ka aplithé kòy adan koloni fransé menm mannyè ki asou lézòt tè Larépiblik fransé ni.\nYuityèm pwen\nPou jòdi kon pou dèmen, menm andidan an péyi étranjé, an fransé pa ni pou ni esklav, i pa ni pou genyen\nesklav, i pa ni pou vann esklav. I pa ni non pli pou mté kòy an pyès mannyè, ni mannyè dirèk, ni endirèk non dan pyès kalté modèltrafik konsa. Tout moun ki ké permèt kòy dérespèkèté sé dispozisyon-tala kay pèd tout dwa kriyé yo fransé ankò. Si, magré sa, an fransé sé ni wè épi sé entèsisyon-tala, an moma éti laplikasyon dékré-a sòti, léta ka ba’y twa zan pou mété kòy an naks. Sa ki sé vini ni esklav létranjé, swa sé an léritaj, swa yo sé ba yo’y, swa mariyaj yo sé fè yo ni yo, anba menm penn-an, yo ké ni pou rann esklav-la lib, oben, rifizé léritaj-tala adam menm délé-a, di jou yo apwann yo ké mèt esklav.\nNévyèm pwen\nMinis Lamarin, Minis Lékolini, Minis Ladjès, yo chak, an travail yo ki ta yo, yo ni pou fè dékré-tala fè chimen’y pou i réyalisé pou bon.\nDékré-tala fèt Pari dan konsèy gouvèlman li 27 avril 1848.\nMoun-tala fèt Pari dan konsèy govèlman pwovizwa-a.\nVictor Schoelcher [...]. Counter Strike Source yo ka kriyéy osi CSS.\nSé on FPS (First Person Shout). Sé on swit a Counter Strike ki li mèm sé on mod a Half Life\nOu ni on ékip a téwowis' é on ékip a kont' téwowis' ka goumé avè zarm.\nFo ou rivé fè misyon la.\nSwa ou téwowis é fo ou anpéché lot ékip la sové sé oatj la, ou swa fo ou ay pozé on bomb on koté prési.\nSwa ou kont' téwowis' é fo ou ay sové otaj, ou swa fo ou anpéché sé téwowis' la pozé bomb a yo, é si yo rivé pozéy fo ou dézamorséy avan i pété.\nSé on jé Multijouè, ou pé jwéy anlè on serveur lokal(LAN), mè moun ka jwé sa onlo si internet.\nNi onlo kalité zarm adan, ni revolvè, snaypè, mitrayèt', grènad avéglant', etc... Ni onlo Map diféran osi adan !\nJé la sa fun !!!\nOu ka pran on bon pyé adan !\nZôt pé jwinn' nou si tracker la : KMKPC anlè tracker la.\nSi zôt bizwin info é konsèy jwinn' nou si forum an nou, adan sijé la sa : CSS anlè forum an nou\nGadé vidéo la zôt ké konprann' ki jé sa yé... pou sa ki pa konèt... Mèt video la an HD !!! Moun ki konnèt tibwen listwa a péyi Ayiti, yo pitèt gadé nyouz lannuit pasé épi yo rété ka sonjé, tankou mwen menm an mwen sonjé pannan on ti moman tan : “On trannmandtè ? Epi kisa apré ? Sé modi pòò Ayiti modi, wi !”\nMen, alòs trannmandtè sé brann lanati ; fèbasité total-radikal douvan trannmandtè, sa se moun tousèl ki anrèskonsab. Lèwgadé listwa a fèbasité a Ayiti douvan tout déga natirèl – dépi dlo-monté, lafen ka fè byò si moun épi maladi jis trannmandtè sanmanman lasa – sé on listwa ki pa fèt avantyè, sé on listwa ki konpliké men chouk a listwa lasa klè kon klè ka vwè.\nSé sé èsklav la yo té pran Lafrik-Ginen ki fè péyi Ayiti an lanné 1804. Alòs lèsklavaj téka fè florès atè Etazini épi tout Lakarayib, sé èsklav la pété chenn, jété tout kolon fransé déwò pou yo kréyé on répiblik ki ta yo. Sé padavwa yo lansé onsèl wélélé pou libèté a yo, moun Ayiti rousouvwè pinisyon dèyè pinisyon dépi sa. On pinisyon ki manjé lajan a péyi la toupannan onnèksétéra lanné lè – an lanné 1825 – sé Fransé la mandé Ayisyen gangné èvè lò on lendépandans yo té ja obtyenn èvè san. On pinisyon lè Mériken mètè Ayiti anba okipasyon militè dépi 1915 jis 1934. On pinisyon èvè on mové administrasyon natif-natal gouvèlman Etazini wousoulé épi sipòté. (Dépi yonndé tan, apré yo té koumansé ba li balan sé administrasyon mériken la pran lòpsyon dékalé démokrasi-konstitisyon Ayiti la.)\nSé konsa nou rivé an sityasyon konyéla la : sé pasé dis mil (10 000) òwganizasyon ki la ka pòté mannèv ki dapré yo pou pèwmèt rédé moun Ayiti, men Ayiti sé yonn a péyi pi andalo asi latè toujou. On mòso a lajan sé òwganizasyon rédé-moun lasa ka sèvi èvè y la sé on lajan ki sòti dyèktéman an pòch a gouvèlman Etazini, on gouvèlman ki apiyé pou onpilo adan mannèv ki pòté viré anfendéfen an pòch mériken – pou on pa pi gwo pasé sa ki fèt pou dòt péyi gwo lizinaj.\nSolidarité ka koulé asou Ayiti.\nMé a pa tout pwoblèm la. Adan kèsyon a solidarité oliwonlatè, i ka sanm sa onchay mannèv – ki an tan pasé, ki jòdijou – té pou ankayé nèt dépi koumansman a yo. Tini tout sé pwojé la ki ka sanm sa yo pa fèt pou sèvi ba moun Ayiti ki anmizè men pou pwofité ba moun ki ka jéré sé pwojé lasa. Pi fò pasé sa, onpliralité òwganizasyon ka sanm sa yo pri adan on lapépasité – désèrten jis adan on lavépasité – mèt doubout on lyannaj ansanm ki èvè dòt òwganizasyon, ki – sa ki pi pòtalan – èvè èstrikti piblik a sosyété la yo pou sèvi la.\nEskiz yo abityé bay - on gouvèlman kon ta Ayiti flòkò épi li pri adan wousoulman – pa ka kyenbé. Okontrè, sé on rézon anplis pou travay èvè gouvèlman la. Bik final a tout sèkou ba péyi Ayiti téké pou fòwtifiyé ki enstitisyon, ki èstrikti, ki lakonésans Ayiti.\nSimenn lasa, lis a biten Ayiti bouzwen – biten kontèl djòb, nannan épi woubwazman – lonjé bip! piplis ankò. Sé prensipalman anvil-kapital la èvè oliwon a li, la tini plis moun ka rété an péyi la, la dékalté òwganizasyon kon Kwa-Wouj épi Nasyon Alyansé tini biwo a yo trannmandtè la déchèpiyé. Onlo koté – kontèl lopital prensipal la – ki téké pé sèvi pou pòté sèkou ba moun andélala, yo menm yo andélala.\nKanmenmsa, tini désèrten òwganizasyon ki la ka ba moun pal ki pal pou tanbonvré atè péyi Ayiti. Ja tini yonn – omwens – trannmandtè la pa kité anzèb. Zanmi lasanté, Partners in Health an lang anglé, sé pi gwo èstrikti ka bay swen nan sèksyon a péyi Ayiti (Mwen menm, mwen adan krèy pou déplwayman òwganizasyon lasa). Zanmi lasanté, anlyannaj èvè Ministè lasanté Ayiti, ka jéré dis (10) lopital oben klinik ki yotout olwen Pòtoprens épi ki yotout annéta. Apré bidim dékalborasyon la ki rivé la, Zanmi lasanté sé pitèt pi gwo èstrikti lasanté ki vayan toujou an tout péyi la.\nAbonnè, li sé osi on vré modèl lendépandans – on modèl èvè on zing Mériken ki angajé adan mouvman a touléjou épi èvè moun Ayiti ki mèt a mannyòk. Sé pitèt dékalté brennman konsa ki néta trasé on chimen pou Ayiti nèfté pwomès a révolisyon Sendomeng la ansanm i la ka woulévé.\nFabien Marius-Hatchi sé makè a blog Lidejis, li sé on zanmi a Tlaxcala, lyannaj lantou latè tradiktè pou pliralité lang. Tradiksyon lasa pé pibliyé nenpòt dòt koté dépi sé tout artik la ki pibliyé é dépi yo ka fè konnèt non a makè la, non a moun la ki touné artik la adan ondòt lang, non a moun la ki kontrolé jan artik la touné épi non a sitwèb la ki pibliyé li dabò. Mas An Nou, sé Mas a neg Gwadloup, sé Mas a moun tout koté, sé Mas a pep la. Mas An Nou, sé on Mas popilè, on Mas ka rasanblé nonm é fanm ki ni on bon lespri é ki vlé poté on kontribisyon o nivo a kilti a péyi la.\nMas An Nou, sé on mouvman a neg ki enmé tradisyon a péyi la, é ki vlé montré on lot son, on lot vibrasyon, on lot anbyans. Mas An Nou, sé osi on mouvman a mas a po, adan larel a Mas a Sen Jan. Dèpi lendi, an monté ba zòt on blòg ww otila an pé fè plis biten èvè-y kon pa èkzanp voyé vidéo, mizik asi-y. Non a-y 'Gwakafwika Révolisyon'. Aprédavwa an sibi pwoblèm èvè sé mésyé, plis ki janmen nou an tan a Révolisyon!\n[...]\nKanmarad, asi CCN moun pé woupwan bokantaj a pawòl-maké! Mèt a mannyòk-la (webmaster) fè on bèl travay!\n15 òktòb 1987, gouvèlman fwansé ka fè kyouyé mèt a mannyòk a révolisyon a péyi Bikina Faso, Thomas Sankara.\nAn ké woupwan an gwadloupéyen on pawòl a Thomas Sankara fwansé fè kyouyé on jou 15 òktòb 1987 an péyi Bikina Faso : 'Nèg mawon ki pé pa menné on révolisyon ankò pa mérité yo lévé yo di gad. Fò pa yo atann si pal a ansyen mèt a-yo pou sa. Sé lévé gawoulé pou yo pé sav woufè kò a-yo é libéré-yo!'.\nSa fwè é sè Gwadloup, sé konba a LKP, konba an-nou, konba a pèp Gwadloup!\n[...]\nLò a gwadloupéyen dwèt rété an péyi a-yo!\nKriz mondyal vin pété, lò-la asi marché mondyal-la monté anflèch! Lò-la monté a 200% an apenn 10 lanné. Moun maléré ki bizwen lajan oblijé ay vann lò yo tini pou yo sòti-yo dafè. Mé pwoblèm-la si on moun bizwen vann lò a-y, i pé ké rékipéré valè a lò-la menm mé valè a pwa a lò-la. Kivédi yo ké achté-y an men a-y asi valè a pwa a-y. On èkzanp, on bijou a 18 kara a 10 gram ki ni on valè a 360 éwo, si on moun ka vann li ba on awtizan, sa ké kouté-y éwo. Rézilta, pisimyé on moun vann ba on moun ki pa ka woulé an larèl a lò-la. Malérèzman, konm moun-la bizwen gannyé lajan pas zafè a-yo mélé, yo pa kay aka awtizan gwadloupéyen-la, yo kay aka sé miltinasyonal-la ki tini mwayen bay plis lajan. Rézilta menm bijou a 10 gram-la ké kouté aka sé miltinasyonal-lasa éwo. Alò pisimyé moun-la ay aka sé mésyé. Mé sa moun pa sav la, lò-la sé miltinasyonal-la ka achté an men a gwadloupéyen pa ka rété an péyi-la. Lò-la yo ka menné-y an péyi éwopéyen, yo ka fonn lò-la pou yo fè dòt bijou oben ankò yo ka mété sé lengo-la adan kòf a-yo. Lè on moun ka vann lò-la ba sé miltinsayonal-la, lò-la pa ka rété Gwadloup mé si menm moun-lasa ka vann li ba on awtizan Gwadloup, lò-la ka rété an péyi-la. E an pa sav si zò sav, lò-la ka sèvi sékirité adan on péyi si an ka pa ka.\nSi zò bizwen santi on losyon ki tini on lòdè 'nozé a bonda', ay jété on zyé asi http://info.france2.fr/jean-paul-guerlain-derape. On vidéo zò pé vwè osi aka 'Bondamanjak'.\n[...]\nYè asi plaj 'Datcha' an komin Gozyé, on pwason mòdé rèd osèryé on boug pannan i té ka bengné an lanmè-la. Yo di sété ké on gwo pwason ki fè sa. Yo di sé travay a on békin. On gwo pwason ki ka fè pétèt 1, 70 a 1,80 m! Bomaten-la asi RTB, on maren-péchè di békin-lasa tini on laj é i tini pwoblèm pou touvé manjé osèryé. Alò sé pousa i ka touvé-y owa plaj-lasa pou'y pé sav manjé sa moun ka lagé an lanmè-la. Moun ka di osi, fò pa moun bengné èvè lò a-yo asi yo davwa tousa ka kléré ka fè pwason kon békin vini owa moun. Kifè alè moun oblijé mobilizé osèryé pou yo pé sav trapé békin-lasa. Chonjé pa tini lontan sé on pwason kon sa ki té blésé osèryé on ti-gason an pyé a-y.\nBékin-la pé tini on longè ki pé rivé jous a 3 mèt! On pwason ki tini dan osèryé!\n[...]\nPou plis kamo asi Koup Digicel Karayib-la, ay asi Boul an Karayib-la.\nM'Bitako kay ba pèp Bastè on rèprézantasyon, non a-y 'On ti-longan lanmou'\nandidan oditoryòm-la Gwadloup. Sa ka fèt jòdi sanmdi a Huitèd'swè. Vini vwè sa!\nAnnou manjé sa péyi an-nou ka fè, kon sa\nnou ké mwens malad!\nBomaten-la asi RTB, Jéra adan jounal a-y té ka bay sa yo té ka di adan sanblé a LKP owa lapòs Bastè yè swa. On sanblé ola Alex Bandou a LiPG (Linyon Péyizan Gwadloup) té ka di nou ankò, ankò é ankò on fwa fò nou manjé sa péyi an-nou ka pwodui.\nPoukisa? Sé padavwa lè'w ka manjé sa ka sòti a kaz a-w, santé a-w oblijé vin méyè. Ki jan nou pé konpwann, on pakèt moun an péyi-la ka mò èvè maladi kon kansè, AVC, dyabèt, kisisi, kisila?\nChonjé osi jou pétròl ké vin ra, ka nou ké fè? Davwa pri a transpò ké vin chè alò pri a machandiz ké oblijé wosé. Moun ki pa ni onlo lajan, ki jan yo ké pé fè? Mwenmenm an-mwen, pisimyé an péyé on pwodui pli chè mé ki sòti an péyi Gwada!\n[...]\nMèt Sarah Aristid, on fanm doubout! On avoka ka défann an péyi an-nou travayè é sé fwè-la an Karayib-la ki ka pwan bon gaz anba gyouk a léta kolonyal fwansé. On fanm doubout ki komansé dèpi kèk tan mélé zafè a sé pwofitan-la an péyi Gwada. On fanm yo ka éséyé fè-y tonbé mé nou ja konnèt an péyi kolonizé, yo ja éséyé fè onlo moun tonbé mé sa yo pa sav la, tini sòlda Gwadloup ki pé ké jen lésé kolonyalis fè madanm-lasa tonbé!\nMi an midi-la, jounalis fwansé dèyè Lachin padavwa péyi-lasa pa ka rèspèté démokrasi. Ah bon? E zòt alò? Zòt fwansé, zò ka rèspèté-y démokrasi-la? Dèpi on moun tini on lidé politik, on lidé pou fè péyi a-y sòti an kabouya yo mété-y la, zò vlé fè-y arété palé ankò!\nFò nou palé é maké kréyòl touléjou é toupatou an péyi-la!\nKanmarad, pa ni lontan nou menné PSE adan dènyé kaz a-y? Pa ni lontan toutmoun isi té ka kriyé woulo ba Patrick ki défann lang é kilti Gwadloup? Dé simenn apré, ka'y ka pasé? On pakèt fachis ka kriyé anmwé davwa kanmarad Eli Domota voyé on démo-maké ba minis fwansé a lajistis ola i ka di fò NOU gwadloupéyen, NOU ki an péyi an-nou, nou palé lang a péyi-la toupatou! Aka 'domactu' pou pa nonmé-y (davwa fò nou toujou jété on zyé aka lèlmi), yo mèt on sijé 'Parler créole au tribunal?'. Imajiné-zòt kanmarad, 114 répons asi sijé-lasa! 114 répons an di zòt, on rèkò! Aaaah, fout Eli ka fè yo chyé!\n[...]\nAprémidi-la, Lapwent, an ay adan paviyon-la owa Laplas Laviktwa ola on militan an-nou té ka rann omaj ba on dòt gwan militan a péyi-la Soni Ripè (Sonny Rupaire). Sé awtis Joël Nankin èvè tablo a-y ki té ka fè nou chonjé tout travay misyé Ripè fè ba péyi a-y. Joël Nankin ka sèvi koulè é osi délè enki èvè nwè é blan. Soni Ripè té fè pawòl-fonnkè asi kyouyézon (massacre) a Mé 67. Sé èvè tablo an nwè é blan, Joël Nankin ka rakonté nou sa ki té pasé Lapwent jou 26,27,28 Mé 1967.\nMoun ki an péyi-la, ka pasé an péyi-la, rann-zòt Lapwent owa Laplas Laviktwa pou zò pé sav vwayajé adan listwa èvè tablo a Joël Nankin.\n[...] « Bobòn fwa... Twa fwa bel kont ! »\nRann sèvis ka bay mal do.\nTé ni yon fwa yon pov nonm ki fè léprev-la. Sé té yon bien bon nonm : li té mayé. Zot tout konpwann déjà fanm-li pa té vo gran choy : i té mové kon gal set-an.\nBon chien pa ka janmen tonbé asou bon zo.\nPoulos, pov nonm-la té bien maléré. Tou lé jou fanm-la té ka fòjé kéchoy pou rann mari-li fou. Nonm-la té lé soukré kò’y okòmansman ; mé i wè sé pa té lapenn pa té ni mwayen chanjé sa ; sé té lavé lanmen épi suiyé to atè.\nAnfen, yon bon jou, soley té ka kité lorizon ; tout bet déjà ka dòmi ; lannuit té ka tonbé. Fanm-la té di mari-li :\n— Mwen ka mò pou manjé zibié.\n— a sé zè si, machè ? Mé ou pa ka sonjé ! Poul menm déjà kouché. Mwen ni labitid bat bwa ; janmen mwen pa ké touvé ayen.\n— Mwen lé, mwen di’w, mwen lé manjé zwézo.\nMari-li réponn ankò :\n— Ebien machè, yonn sé jou-la, ou ké mandé mwen lalin an koubouyon, soleil an frikasé, épi mwen ké fòsé bay ou yo alò ?\nFanm-la pa réponn, i fésé pié’y atè ; i trapé yon manch pilon, yon gwo bwa-lélé.\nPov boug-la té sav sa sa té lé di : i mété distans tousuit, i pwan lè laj épi fizi’y.\nRivé dan koté balizié i té ka fè yon tibwen nwè déjà, i gadé toupatou. Sa i té ka fè pou ritouné a kaz-li ? Fanm-la té ké bat li pou si.\nI maché, i maché, i maché dan fon gran bwa. Anfen, i wè, asou yon bwanch zab, yon bel zwézo ki té ka pozé. Tout plim-li té koulè lézot fwa ou té ké jiré yo té ka kléré.\nNonm-la pa té kapon pies : i bien gadé bet-la ki té ka balansé kò-li pa si, pa la ; i tann zwézo-a chanté. I té ka chanté tou dousman :\n« Dédé konnan, dédé a lépé. \nDédé konnan, lésé mwen dòmi. »\nNonm-la wè bien sa té pa yon bet Bondié té fè ; i té gwo kon yon timanmay. Mé tank i té ni pè fanm-li, i lévé fizi’y toudmenm. Alos, zwézo-la chanté pli fò, épi vit :\n« Vizé bien, vizé bien... yon glan, yon glan !\nMwen foukolé... yon glan ;\nMwen tranblé pié... yon glan ;\nMwen tini diablokwè... yon glan ! »\nNonm-la fou li ba kanmenm ; mété li dan sak-li ; épi kon i té pé, i mété zel dan pié pou li kouri lanmézon. Rivé li rivé, li montré bel zwézo-la : tout moun té bien kontan. Diné té ja paré ; té ni asou tab yon migan chou, kek volan fri, yon bon babacha ki té ka fè vini dlo adan bouch anfen, anfen... tout sot bon bagay.\nFanm-la mété tou sa dan gad-li pou dimen ; i té lé manjé anni zibié-a. Mafwè, i té asé gwo pou nouri tout fanmi-la.\nYo fè bon lasos pikant asou’y épi kek kouskouch alantou’y. Sé moun-la manjé jouk tan té ka rété anni zo épi yo alé kouché.\nMé vini wè pli bel la !\nAn bon mitan sonmey-yo, vant tout moun koumansé bouyi ; sé té toufé toubannman. Dan chak bouden, yo tann yon vwè té ka chanté :\n« Vomi mwen, vomi mwen... yon glan !\nMwen foukolé... mwen glan\nMwen tranlé pié... yon glan !\nMwen tini diablokwè... mwen glan »\nPa bonnè, yo tout fini pa vomi tout zibié-a. Pas san sa, yo té ké santi lanmò té ké vini ; Yo tann chanté alos :\n« Sanblé mwen, sanblé mwen yon glan\nMwen foukolé... yon glan\nMwen tranblé pié... yon glan\nMwen tini diablokwè... yon glan »\nPapa, manman, tout yich-la té blijé ranmasé tou sa yo té ka rann. Pandan tan-a, zibié-a ka chanté toujou :\n« Kolé mwen, kolé mwen…yon glan\nmwen foukolé…yon glan\nmwen tranblé pié…yon glan\nmwen tini diablokwè, yon glan »\nSé pov moun-la fini pa jwenn tout mòso-a ansa,nm ; yo rifè zibié-a kon yo té pé. Li-menm, bet-la, té ka ranjé zel-li, janm-li ; li té présé pas jou té ké ouvè. I ka kriyé yo :\n« Mété plim, mété plim... yon glan\nMwen foukolé... yon glan\nMwen tranblé pié... yon glan\nMwen tini diablokwè... yon glan »\nKi travay sa, mondié-sengnè ! Fanmi-la té ka swé. Plim-la té ka volé adan tout kaz-la, épi déwò, épi toupatou, jouk asou mòn. Yo brilé douz tjes bouji lannuit-la : tout moun té ka mò afos yo kouri ! Yo té ka chaché toujou, anmizi, pou vini kolé asou kò zwézo-a... Tout tan-a i té ka chanté, kon i té ka chanté dan bwa, tou dousman pou i wè si’y té ni kont plim-li :\n« Dédé konnan, dédé a lépé\nDédé konnan, lésé mwen dòmi ! »\nLi santi té ka manké’y dot plim. Alos, i présé yo, i chanté pli vit ; zié’y kléré ; jou té ka ouvè.\n« Sé pa tout, sé pa touyt... yon glan\nMwen foukolé... yon glan\nMwen tranblé pié... yon glan\nMwen tini diablokwè... yon glan ! »\nSé moun-la té prêt pou mò. Pouytan, yo touvé lafos anba zié zibié-a ki té ka fè lamaniétiz asou yo. Sa fè, yo chaché épi touvé jouk dènié plim-li.\nKan zwézo-la té bien soukré kò’y épi i té wè tout plim-li té la, i chanté présé pou yo :\n« Pòté mwen, pòté mwen... yon glan\nMwen foukolé... yon glan\nMwen tranblé pié... yon glan\nMwen tini diablokwè... yon glan »\nYo bien péyé goumandiz-la. Zwézo té présé yo. I té dwé rivé adan bwa avan jou ouvè ; osi, i fè sé moun-la tjwé kò-yo ; i fòsé yo pou mété li asou menm branch zab-la yo té touvé la. Kan li rivé, douvan-jou, i chanté pou yo pandan i té ka touné pas si, pa la :\n« Dédé konnan, dédé a lépé\nDédé konnan, lésé mwen dòmi »\nFanmi-la pa mandé li lèrestan ; yo pati si vit, jou pa pwan yo dan bwa. Dépi sa, madanm-la kité misié tibwen lavi pas i si tala sé di’y :\n« Tout pawol pa bon pou di ; tout manjé pa bon pou manjé. Sonjé, machè, kon di kont-la :\nKabrit bwè, mouton sou. » [...]\nPa rapôt a travay oben pou dé rézon pli pèwsonèl, ou désidé fè tèks a vou jwenn plis moun.\nPou pwofésyonèl, tradiksyon

In [32]:
!pip install ftfy

Requirement already satisfied: ftfy in c:\users\elise\anaconda3\lib\site-packages (6.3.1)
Requirement already satisfied: wcwidth in c:\users\elise\appdata\roaming\python\python311\site-packages (from ftfy) (0.2.13)

In [36]:
# fixing unicode and removing some punctuation strings
import ftfy

punct_to_remove = [" [...] ", "\n[...]\n", "[...]\n", " [...]", "[...] ",  "\n[...]", "[...]"]

def remove_punct (punct_to_remove, corpus):
    for punct in punct_to_remove:
        clean_text = corpus.replace(punct, "")
        text = ftfy.fix_text(clean_text)
    return text

text_gdl = remove_punct(punct_to_remove, corpus_gdl)
text_mqc = remove_punct(punct_to_remove, corpus_mqc)
text_gfr = remove_punct(punct_to_remove, corpus_gfr)
text_hcr = remove_punct(punct_to_remove, corpus_hcr)

print(text_gdl)

An non pèp fransé-a,
Gouvèlman fransé-a ka konssidéré ki lestravay sé an koutba kont dignité moun. Ika konsidéré ki, lè ou ka détwi tout posibilité moun té pou ni di gouvèné kòy limenm, ou ka dè dé bagay disparèt. Sé dé bagay-tala pa dòtki, baz natirel limanité menm sa ou ni dwa ni, épi sa yo andwa ba'w.
I ka konsidéré ki, yo ka anvyolé manman-chous Larépiblik, kivédi Liberté, Ègalité, Fratènitè.
I ka konsidéré ki, si yonn dé dispozisyon pa té ka vini lamenm déyè règ konduit poklamasyon abolisyon-an, an brigandaj san manman té ké mèt adan sé koloni-an.
Gouvèlman fransé mété dékré-tala doubout :
Priméy pwen
Lestravay kay aboli, nèt, adan tout koloni, tout mòso tè ki ta Lafrans, dé mwaapré laplikasyon lwa-tala adoptéé. Adan yo shak-la, di jou lapalikasyon dékré-a koumansé fè shimen'y, adan koloni, tout kalté chatiman éti moun
ka ba moun kou, tout kalité lavan éti moun ka vann moun, sa pa pou fèt pyès ankò ; sa entèdi.
Dézyèm pwen
Tafè oblijé moun Sénégal angajé kòy pandan antan, ki i lé, ki i da lé sa bout.
Twazyèm pwen
Sé sé gouvènè-a obencé kaomisè jénéral Larépiblik-la, ki ké ni pou asiré libèté pèp Matinik, pèp Gwadloup épi pèp lilet lantou'y, pèp Lagiyan, pèp Sénégal, pèp tout dòt bò lakòt west lafrik éti Lafrans établi dòy, pèp mayòt, pèp lilet ki lantou'y èk pèp Laljèri.
Katyèm pwen
Sa ki té esklav épi ki sé ni kondanasyon ki ka mété nonm pli ba ki nonm, oben ki sé ni penn korèksyonèl pou dé bagay an nonm lib pa té ké ni tousa lapenn pou fè, lalwa ka éfasé sé kondanasyon-tala. Tout dépòté ki té ka sibi mizi gouvèlman té pwan kont yo, té rantré kay yo.
Sentyèm pwen
Lasanblé National ké réglé chak pa déonmajman kolon sé ni pou touché.
Sizyèm pwen
Sé koloni nou an ki pa ni esklav ankò, épi tè nou ni Lézend, ké ni délégasyon yo Lasanblé Nasyonal.
Sétyèm pwen
Tèg jénéral la ki ka di « dépi ou pozé pyé an Frans si ou esklav, ou lib » ka aplithé kòy adan koloni fransé menm mannyè ki asou lézòt tè Larépiblik fransé ni.
Yuityèm pwen
Pou jòdi kon pou dèmen, menm andidan an péyi étranjé, an fransé pa ni pou ni esklav, i pa ni pou genyen
esklav, i pa ni pou vann esklav. I pa ni non pli pou mté kòy an pyès mannyè, ni mannyè dirèk, ni endirèk non dan pyès kalté modèltrafik konsa. Tout moun ki ké permèt kòy dérespèkèté sé dispozisyon-tala kay pèd tout dwa kriyé yo fransé ankò. Si, magré sa, an fransé sé ni wè épi sé entèsisyon-tala, an moma éti laplikasyon dékré-a sòti, léta ka ba'y twa zan pou mété kòy an naks. Sa ki sé vini ni esklav létranjé, swa sé an léritaj, swa yo sé ba yo'y, swa mariyaj yo sé fè yo ni yo, anba menm penn-an, yo ké ni pou rann esklav-la lib, oben, rifizé léritaj-tala adam menm délé-a, di jou yo apwann yo ké mèt esklav.
Névyèm pwen
Minis Lamarin, Minis Lékolini, Minis Ladjès, yo chak, an travail yo ki ta yo, yo ni pou fè dékré-tala fè chimen'y pou i réyalisé pou bon.
Dékré-tala fèt Pari dan konsèy gouvèlman li 27 avril 1848.
Moun-tala fèt Pari dan konsèy govèlman pwovizwa-a.
Victor Schoelcher . Counter Strike Source yo ka kriyéy osi CSS.
Sé on FPS (First Person Shout). Sé on swit a Counter Strike ki li mèm sé on mod a Half Life
Ou ni on ékip a téwowis' é on ékip a kont' téwowis' ka goumé avè zarm.
Fo ou rivé fè misyon la.
Swa ou téwowis é fo ou anpéché lot ékip la sové sé oatj la, ou swa fo ou ay pozé on bomb on koté prési.
Swa ou kont' téwowis' é fo ou ay sové otaj, ou swa fo ou anpéché sé téwowis' la pozé bomb a yo, é si yo rivé pozéy fo ou dézamorséy avan i pété.
Sé on jé Multijouè, ou pé jwéy anlè on serveur lokal(LAN), mè moun ka jwé sa onlo si internet.
Ni onlo kalité zarm adan, ni revolvè, snaypè, mitrayèt', grènad avéglant', etc... Ni onlo Map diféran osi adan !
Jé la sa fun !!!
Ou ka pran on bon pyé adan !
Zôt pé jwinn' nou si tracker la : KMKPC anlè tracker la.
Si zôt bizwin info é konsèy jwinn' nou si forum an nou, adan sijé la sa : CSS anlè forum an nou
Gadé vidéo la zôt ké konprann' ki jé sa yé... pou sa ki pa konèt... Mèt video la an HD !!! Moun ki konnèt tibwen listwa a péyi Ayiti, yo pitèt gadé nyouz lannuit pasé épi yo rété ka sonjé, tankou mwen menm an mwen sonjé pannan on ti moman tan : "On trannmandtè ? Epi kisa apré ? Sé modi pòò Ayiti modi, wi !"
Men, alòs trannmandtè sé brann lanati ; fèbasité total-radikal douvan trannmandtè, sa se moun tousèl ki anrèskonsab. Lèwgadé listwa a fèbasité a Ayiti douvan tout déga natirèl – dépi dlo-monté, lafen ka fè byò si moun épi maladi jis trannmandtè sanmanman lasa – sé on listwa ki pa fèt avantyè, sé on listwa ki konpliké men chouk a listwa lasa klè kon klè ka vwè.
Sé sé èsklav la yo té pran Lafrik-Ginen ki fè péyi Ayiti an lanné 1804. Alòs lèsklavaj téka fè florès atè Etazini épi tout Lakarayib, sé èsklav la pété chenn, jété tout kolon fransé déwò pou yo kréyé on répiblik ki ta yo. Sé padavwa yo lansé onsèl wélélé pou libèté a yo, moun Ayiti rousouvwè pinisyon dèyè pinisyon dépi sa. On pinisyon ki manjé lajan a péyi la toupannan onnèksétéra lanné lè – an lanné 1825 – sé Fransé la mandé Ayisyen gangné èvè lò on lendépandans yo té ja obtyenn èvè san. On pinisyon lè Mériken mètè Ayiti anba okipasyon militè dépi 1915 jis 1934. On pinisyon èvè on mové administrasyon natif-natal gouvèlman Etazini wousoulé épi sipòté. (Dépi yonndé tan, apré yo té koumansé ba li balan sé administrasyon mériken la pran lòpsyon dékalé démokrasi-konstitisyon Ayiti la.)
Sé konsa nou rivé an sityasyon konyéla la : sé pasé dis mil (10 000) òwganizasyon ki la ka pòté mannèv ki dapré yo pou pèwmèt rédé moun Ayiti, men Ayiti sé yonn a péyi pi andalo asi latè toujou. On mòso a lajan sé òwganizasyon rédé-moun lasa ka sèvi èvè y la sé on lajan ki sòti dyèktéman an pòch a gouvèlman Etazini, on gouvèlman ki apiyé pou onpilo adan mannèv ki pòté viré anfendéfen an pòch mériken – pou on pa pi gwo pasé sa ki fèt pou dòt péyi gwo lizinaj.
Solidarité ka koulé asou Ayiti.
Mé a pa tout pwoblèm la. Adan kèsyon a solidarité oliwonlatè, i ka sanm sa onchay mannèv – ki an tan pasé, ki jòdijou – té pou ankayé nèt dépi koumansman a yo. Tini tout sé pwojé la ki ka sanm sa yo pa fèt pou sèvi ba moun Ayiti ki anmizè men pou pwofité ba moun ki ka jéré sé pwojé lasa. Pi fò pasé sa, onpliralité òwganizasyon ka sanm sa yo pri adan on lapépasité – désèrten jis adan on lavépasité – mèt doubout on lyannaj ansanm ki èvè dòt òwganizasyon, ki – sa ki pi pòtalan – èvè èstrikti piblik a sosyété la yo pou sèvi la.
Eskiz yo abityé bay - on gouvèlman kon ta Ayiti flòkò épi li pri adan wousoulman – pa ka kyenbé. Okontrè, sé on rézon anplis pou travay èvè gouvèlman la. Bik final a tout sèkou ba péyi Ayiti téké pou fòwtifiyé ki enstitisyon, ki èstrikti, ki lakonésans Ayiti.
Simenn lasa, lis a biten Ayiti bouzwen – biten kontèl djòb, nannan épi woubwazman – lonjé bip! piplis ankò. Sé prensipalman anvil-kapital la èvè oliwon a li, la tini plis moun ka rété an péyi la, la dékalté òwganizasyon kon Kwa-Wouj épi Nasyon Alyansé tini biwo a yo trannmandtè la déchèpiyé. Onlo koté – kontèl lopital prensipal la – ki téké pé sèvi pou pòté sèkou ba moun andélala, yo menm yo andélala.
Kanmenmsa, tini désèrten òwganizasyon ki la ka ba moun pal ki pal pou tanbonvré atè péyi Ayiti. Ja tini yonn – omwens – trannmandtè la pa kité anzèb. Zanmi lasanté, Partners in Health an lang anglé, sé pi gwo èstrikti ka bay swen nan sèksyon a péyi Ayiti (Mwen menm, mwen adan krèy pou déplwayman òwganizasyon lasa). Zanmi lasanté, anlyannaj èvè Ministè lasanté Ayiti, ka jéré dis (10) lopital oben klinik ki yotout olwen Pòtoprens épi ki yotout annéta. Apré bidim dékalborasyon la ki rivé la, Zanmi lasanté sé pitèt pi gwo èstrikti lasanté ki vayan toujou an tout péyi la.
Abonnè, li sé osi on vré modèl lendépandans – on modèl èvè on zing Mériken ki angajé adan mouvman a touléjou épi èvè moun Ayiti ki mèt a mannyòk. Sé pitèt dékalté brennman konsa ki néta trasé on chimen pou Ayiti nèfté pwomès a révolisyon Sendomeng la ansanm i la ka woulévé.
Fabien Marius-Hatchi sé makè a blog Lidejis, li sé on zanmi a Tlaxcala, lyannaj lantou latè tradiktè pou pliralité lang. Tradiksyon lasa pé pibliyé nenpòt dòt koté dépi sé tout artik la ki pibliyé é dépi yo ka fè konnèt non a makè la, non a moun la ki touné artik la adan ondòt lang, non a moun la ki kontrolé jan artik la touné épi non a sitwèb la ki pibliyé li dabò. Mas An Nou, sé Mas a neg Gwadloup, sé Mas a moun tout koté, sé Mas a pep la. Mas An Nou, sé on Mas popilè, on Mas ka rasanblé nonm é fanm ki ni on bon lespri é ki vlé poté on kontribisyon o nivo a kilti a péyi la.
Mas An Nou, sé on mouvman a neg ki enmé tradisyon a péyi la, é ki vlé montré on lot son, on lot vibrasyon, on lot anbyans. Mas An Nou, sé osi on mouvman a mas a po, adan larel a Mas a Sen Jan. Dèpi lendi, an monté ba zòt on blòg ww otila an pé fè plis biten èvè-y kon pa èkzanp voyé vidéo, mizik asi-y. Non a-y 'Gwakafwika Révolisyon'. Aprédavwa an sibi pwoblèm èvè sé mésyé, plis ki janmen nou an tan a Révolisyon!

Kanmarad, asi CCN moun pé woupwan bokantaj a pawòl-maké! Mèt a mannyòk-la (webmaster) fè on bèl travay!
15 òktòb 1987, gouvèlman fwansé ka fè kyouyé mèt a mannyòk a révolisyon a péyi Bikina Faso, Thomas Sankara.
An ké woupwan an gwadloupéyen on pawòl a Thomas Sankara fwansé fè kyouyé on jou 15 òktòb 1987 an péyi Bikina Faso : 'Nèg mawon ki pé pa menné on révolisyon ankò pa mérité yo lévé yo di gad. Fò pa yo atann si pal a ansyen mèt a-yo pou sa. Sé lévé gawoulé pou yo pé sav woufè kò a-yo é libéré-yo!'.
Sa fwè é sè Gwadloup, sé konba a LKP, konba an-nou, konba a pèp Gwadloup!

Lò a gwadloupéyen dwèt rété an péyi a-yo!
Kriz mondyal vin pété, lò-la asi marché mondyal-la monté anflèch! Lò-la monté a 200% an apenn 10 lanné. Moun maléré ki bizwen lajan oblijé ay vann lò yo tini pou yo sòti-yo dafè. Mé pwoblèm-la si on moun bizwen vann lò a-y, i pé ké rékipéré valè a lò-la menm mé valè a pwa a lò-la. Kivédi yo ké achté-y an men a-y asi valè a pwa a-y. On èkzanp, on bijou a 18 kara a 10 gram ki ni on valè a 360 éwo, si on moun ka vann li ba on awtizan, sa ké kouté-y éwo. Rézilta, pisimyé on moun vann ba on moun ki pa ka woulé an larèl a lò-la. Malérèzman, konm moun-la bizwen gannyé lajan pas zafè a-yo mélé, yo pa kay aka awtizan gwadloupéyen-la, yo kay aka sé miltinasyonal-la ki tini mwayen bay plis lajan. Rézilta menm bijou a 10 gram-la ké kouté aka sé miltinasyonal-lasa éwo. Alò pisimyé moun-la ay aka sé mésyé. Mé sa moun pa sav la, lò-la sé miltinasyonal-la ka achté an men a gwadloupéyen pa ka rété an péyi-la. Lò-la yo ka menné-y an péyi éwopéyen, yo ka fonn lò-la pou yo fè dòt bijou oben ankò yo ka mété sé lengo-la adan kòf a-yo. Lè on moun ka vann lò-la ba sé miltinsayonal-la, lò-la pa ka rété Gwadloup mé si menm moun-lasa ka vann li ba on awtizan Gwadloup, lò-la ka rété an péyi-la. E an pa sav si zò sav, lò-la ka sèvi sékirité adan on péyi si an ka pa ka.
Si zò bizwen santi on losyon ki tini on lòdè 'nozé a bonda', ay jété on zyé asi http://info.france2.fr/jean-paul-guerlain-derape. On vidéo zò pé vwè osi aka 'Bondamanjak'.

Yè asi plaj 'Datcha' an komin Gozyé, on pwason mòdé rèd osèryé on boug pannan i té ka bengné an lanmè-la. Yo di sété ké on gwo pwason ki fè sa. Yo di sé travay a on békin. On gwo pwason ki ka fè pétèt 1, 70 a 1,80 m! Bomaten-la asi RTB, on maren-péchè di békin-lasa tini on laj é i tini pwoblèm pou touvé manjé osèryé. Alò sé pousa i ka touvé-y owa plaj-lasa pou'y pé sav manjé sa moun ka lagé an lanmè-la. Moun ka di osi, fò pa moun bengné èvè lò a-yo asi yo davwa tousa ka kléré ka fè pwason kon békin vini owa moun. Kifè alè moun oblijé mobilizé osèryé pou yo pé sav trapé békin-lasa. Chonjé pa tini lontan sé on pwason kon sa ki té blésé osèryé on ti-gason an pyé a-y.
Békin-la pé tini on longè ki pé rivé jous a 3 mèt! On pwason ki tini dan osèryé!

Pou plis kamo asi Koup Digicel Karayib-la, ay asi Boul an Karayib-la.
M'Bitako kay ba pèp Bastè on rèprézantasyon, non a-y 'On ti-longan lanmou'
andidan oditoryòm-la Gwadloup. Sa ka fèt jòdi sanmdi a Huitèd'swè. Vini vwè sa!
Annou manjé sa péyi an-nou ka fè, kon sa
nou ké mwens malad!
Bomaten-la asi RTB, Jéra adan jounal a-y té ka bay sa yo té ka di adan sanblé a LKP owa lapòs Bastè yè swa. On sanblé ola Alex Bandou a LiPG (Linyon Péyizan Gwadloup) té ka di nou ankò, ankò é ankò on fwa fò nou manjé sa péyi an-nou ka pwodui.
Poukisa? Sé padavwa lè'w ka manjé sa ka sòti a kaz a-w, santé a-w oblijé vin méyè. Ki jan nou pé konpwann, on pakèt moun an péyi-la ka mò èvè maladi kon kansè, AVC, dyabèt, kisisi, kisila?
Chonjé osi jou pétròl ké vin ra, ka nou ké fè? Davwa pri a transpò ké vin chè alò pri a machandiz ké oblijé wosé. Moun ki pa ni onlo lajan, ki jan yo ké pé fè? Mwenmenm an-mwen, pisimyé an péyé on pwodui pli chè mé ki sòti an péyi Gwada!

Mèt Sarah Aristid, on fanm doubout! On avoka ka défann an péyi an-nou travayè é sé fwè-la an Karayib-la ki ka pwan bon gaz anba gyouk a léta kolonyal fwansé. On fanm doubout ki komansé dèpi kèk tan mélé zafè a sé pwofitan-la an péyi Gwada. On fanm yo ka éséyé fè-y tonbé mé nou ja konnèt an péyi kolonizé, yo ja éséyé fè onlo moun tonbé mé sa yo pa sav la, tini sòlda Gwadloup ki pé ké jen lésé kolonyalis fè madanm-lasa tonbé!
Mi an midi-la, jounalis fwansé dèyè Lachin padavwa péyi-lasa pa ka rèspèté démokrasi. Ah bon? E zòt alò? Zòt fwansé, zò ka rèspèté-y démokrasi-la? Dèpi on moun tini on lidé politik, on lidé pou fè péyi a-y sòti an kabouya yo mété-y la, zò vlé fè-y arété palé ankò!
Fò nou palé é maké kréyòl touléjou é toupatou an péyi-la!
Kanmarad, pa ni lontan nou menné PSE adan dènyé kaz a-y? Pa ni lontan toutmoun isi té ka kriyé woulo ba Patrick ki défann lang é kilti Gwadloup? Dé simenn apré, ka'y ka pasé? On pakèt fachis ka kriyé anmwé davwa kanmarad Eli Domota voyé on démo-maké ba minis fwansé a lajistis ola i ka di fò NOU gwadloupéyen, NOU ki an péyi an-nou, nou palé lang a péyi-la toupatou! Aka 'domactu' pou pa nonmé-y (davwa fò nou toujou jété on zyé aka lèlmi), yo mèt on sijé 'Parler créole au tribunal?'. Imajiné-zòt kanmarad, 114 répons asi sijé-lasa! 114 répons an di zòt, on rèkò! Aaaah, fout Eli ka fè yo chyé!

Aprémidi-la, Lapwent, an ay adan paviyon-la owa Laplas Laviktwa ola on militan an-nou té ka rann omaj ba on dòt gwan militan a péyi-la Soni Ripè (Sonny Rupaire). Sé awtis Joël Nankin èvè tablo a-y ki té ka fè nou chonjé tout travay misyé Ripè fè ba péyi a-y. Joël Nankin ka sèvi koulè é osi délè enki èvè nwè é blan. Soni Ripè té fè pawòl-fonnkè asi kyouyézon (massacre) a Mé 67. Sé èvè tablo an nwè é blan, Joël Nankin ka rakonté nou sa ki té pasé Lapwent jou 26,27,28 Mé 1967.
Moun ki an péyi-la, ka pasé an péyi-la, rann-zòt Lapwent owa Laplas Laviktwa pou zò pé sav vwayajé adan listwa èvè tablo a Joël Nankin.
 « Bobòn fwa... Twa fwa bel kont ! »
Rann sèvis ka bay mal do.
Té ni yon fwa yon pov nonm ki fè léprev-la. Sé té yon bien bon nonm : li té mayé. Zot tout konpwann déjà fanm-li pa té vo gran choy : i té mové kon gal set-an.
Bon chien pa ka janmen tonbé asou bon zo.
Poulos, pov nonm-la té bien maléré. Tou lé jou fanm-la té ka fòjé kéchoy pou rann mari-li fou. Nonm-la té lé soukré kò'y okòmansman ; mé i wè sé pa té lapenn pa té ni mwayen chanjé sa ; sé té lavé lanmen épi suiyé to atè.
Anfen, yon bon jou, soley té ka kité lorizon ; tout bet déjà ka dòmi ; lannuit té ka tonbé. Fanm-la té di mari-li :
— Mwen ka mò pou manjé zibié.
— a sé zè si, machè ? Mé ou pa ka sonjé ! Poul menm déjà kouché. Mwen ni labitid bat bwa ; janmen mwen pa ké touvé ayen.
— Mwen lé, mwen di'w, mwen lé manjé zwézo.
Mari-li réponn ankò :
— Ebien machè, yonn sé jou-la, ou ké mandé mwen lalin an koubouyon, soleil an frikasé, épi mwen ké fòsé bay ou yo alò ?
Fanm-la pa réponn, i fésé pié'y atè ; i trapé yon manch pilon, yon gwo bwa-lélé.
Pov boug-la té sav sa sa té lé di : i mété distans tousuit, i pwan lè laj épi fizi'y.
Rivé dan koté balizié i té ka fè yon tibwen nwè déjà, i gadé toupatou. Sa i té ka fè pou ritouné a kaz-li ? Fanm-la té ké bat li pou si.
I maché, i maché, i maché dan fon gran bwa. Anfen, i wè, asou yon bwanch zab, yon bel zwézo ki té ka pozé. Tout plim-li té koulè lézot fwa ou té ké jiré yo té ka kléré.
Nonm-la pa té kapon pies : i bien gadé bet-la ki té ka balansé kò-li pa si, pa la ; i tann zwézo-a chanté. I té ka chanté tou dousman :
« Dédé konnan, dédé a lépé.
Dédé konnan, lésé mwen dòmi. »
Nonm-la wè bien sa té pa yon bet Bondié té fè ; i té gwo kon yon timanmay. Mé tank i té ni pè fanm-li, i lévé fizi'y toudmenm. Alos, zwézo-la chanté pli fò, épi vit :
« Vizé bien, vizé bien... yon glan, yon glan !
Mwen foukolé... yon glan ;
Mwen tranblé pié... yon glan ;
Mwen tini diablokwè... yon glan ! »
Nonm-la fou li ba kanmenm ; mété li dan sak-li ; épi kon i té pé, i mété zel dan pié pou li kouri lanmézon. Rivé li rivé, li montré bel zwézo-la : tout moun té bien kontan. Diné té ja paré ; té ni asou tab yon migan chou, kek volan fri, yon bon babacha ki té ka fè vini dlo adan bouch anfen, anfen... tout sot bon bagay.
Fanm-la mété tou sa dan gad-li pou dimen ; i té lé manjé anni zibié-a. Mafwè, i té asé gwo pou nouri tout fanmi-la.
Yo fè bon lasos pikant asou'y épi kek kouskouch alantou'y. Sé moun-la manjé jouk tan té ka rété anni zo épi yo alé kouché.
Mé vini wè pli bel la !
An bon mitan sonmey-yo, vant tout moun koumansé bouyi ; sé té toufé toubannman. Dan chak bouden, yo tann yon vwè té ka chanté :
« Vomi mwen, vomi mwen... yon glan !
Mwen foukolé... mwen glan
Mwen tranlé pié... yon glan !
Mwen tini diablokwè... mwen glan »
Pa bonnè, yo tout fini pa vomi tout zibié-a. Pas san sa, yo té ké santi lanmò té ké vini ; Yo tann chanté alos :
« Sanblé mwen, sanblé mwen yon glan
Mwen foukolé... yon glan
Mwen tranblé pié... yon glan
Mwen tini diablokwè... yon glan »
Papa, manman, tout yich-la té blijé ranmasé tou sa yo té ka rann. Pandan tan-a, zibié-a ka chanté toujou :
« Kolé mwen, kolé mwen…yon glan
mwen foukolé…yon glan
mwen tranblé pié…yon glan
mwen tini diablokwè, yon glan »
Sé pov moun-la fini pa jwenn tout mòso-a ansa,nm ; yo rifè zibié-a kon yo té pé. Li-menm, bet-la, té ka ranjé zel-li, janm-li ; li té présé pas jou té ké ouvè. I ka kriyé yo :
« Mété plim, mété plim... yon glan
Mwen foukolé... yon glan
Mwen tranblé pié... yon glan
Mwen tini diablokwè... yon glan »
Ki travay sa, mondié-sengnè ! Fanmi-la té ka swé. Plim-la té ka volé adan tout kaz-la, épi déwò, épi toupatou, jouk asou mòn. Yo brilé douz tjes bouji lannuit-la : tout moun té ka mò afos yo kouri ! Yo té ka chaché toujou, anmizi, pou vini kolé asou kò zwézo-a... Tout tan-a i té ka chanté, kon i té ka chanté dan bwa, tou dousman pou i wè si'y té ni kont plim-li :
« Dédé konnan, dédé a lépé
Dédé konnan, lésé mwen dòmi ! »
Li santi té ka manké'y dot plim. Alos, i présé yo, i chanté pli vit ; zié'y kléré ; jou té ka ouvè.
« Sé pa tout, sé pa touyt... yon glan
Mwen foukolé... yon glan
Mwen tranblé pié... yon glan
Mwen tini diablokwè... yon glan ! »
Sé moun-la té prêt pou mò. Pouytan, yo touvé lafos anba zié zibié-a ki té ka fè lamaniétiz asou yo. Sa fè, yo chaché épi touvé jouk dènié plim-li.
Kan zwézo-la té bien soukré kò'y épi i té wè tout plim-li té la, i chanté présé pou yo :
« Pòté mwen, pòté mwen... yon glan
Mwen foukolé... yon glan
Mwen tranblé pié... yon glan
Mwen tini diablokwè... yon glan »
Yo bien péyé goumandiz-la. Zwézo té présé yo. I té dwé rivé adan bwa avan jou ouvè ; osi, i fè sé moun-la tjwé kò-yo ; i fòsé yo pou mété li asou menm branch zab-la yo té touvé la. Kan li rivé, douvan-jou, i chanté pou yo pandan i té ka touné pas si, pa la :
« Dédé konnan, dédé a lépé
Dédé konnan, lésé mwen dòmi »
Fanmi-la pa mandé li lèrestan ; yo pati si vit, jou pa pwan yo dan bwa. Dépi sa, madanm-la kité misié tibwen lavi pas i si tala sé di'y :
« Tout pawol pa bon pou di ; tout manjé pa bon pou manjé. Sonjé, machè, kon di kont-la :
Kabrit bwè, mouton sou. »
Pa rapôt a travay oben pou dé rézon pli pèwsonèl, ou désidé fè tèks a vou jwenn plis moun.

In [38]:
print(text_mqc)

 Sé jou-tala, ou sé di nou ka tonbé bien ba, an manniè tjoupoutet. Lot jou an ti-fi koki zié an tibolonm, atjelman sé an boug ki asazinen madanm li avan I pann kò'y. Madanm la té lé chanjé lavi, i té bizwen yonn dé bo. Boug-la pa konprann i pa pran sa, i bay dé bal.
Ildèvè ki fini sòti lot péyi, tou abazoudi. Misié fini rantré pou dapré'y pasé an ti laritret trankil lecha, épi i ka tann tou sa. I jik mandé mwen es sé pa dan an péyi lotbò éti boug ka fè sa yo anvi épi fanm i té ké yé. Man di misié :
- Sé bien Matinik ou yé !
Sé pa Matinik la ou té kité a ni pasé trantan. An tan-tala té ni plis respé menm si boug té ka pran koutla-yo tou. Jòdijou Fanm pa ka rété pran kou ankò, sa fini ! Kou pa soup !
Misié di-mwen :
- Man ka viré pati, man té konprann ki sé la man té yé a ki té cho, mé isiya ankò pi danjéré !
Man pa té tro sav sa pou té réponn, man di'y konsa :
- Ga sa, si ou pa dakò épi vakabonajri-tala, sanmdi bonmaten désann douvan Lakatédral!
Zot sav ni boug ki pa djè enmen palé pou ayen, tann sa yonn di :
- Sé pa dot ki lo gaz lafimen sé avion « la patrouille de France » la ki simen an kochoni anlè tet-nou. An plis di sa, lafimen an té blé blan rouj, sa sé mové sin !
Vréman, vréman, ni boug ki enmen palé pou ayen !
Man tann anlot di :
- Pou tout lo bordel-tala sispann, fo nou alé an swasannkatoz la lamenn !
I poko té fini di sa, anlot koupé pawol li ek i di :
- Mé wi, sé pas zot lé chanjé ki fè tousa ka rivé nou !
Palapenn man di zot, sé té an swasanntrèzis ki vréyé fion-tala !
Antouléka, Niko la, i ka gadé jan isi débat kon dé mal krab dan an menm tou. I pa konnet kréyol mé i asiré ki « dé mal krab pa pou rété dan an menm tou ». Asirépapétet le 17 ek le 24 janvié lanné prochenn, nou ké sav ki manniè krab-la ka dékalé a. Sé la nou ké sav asou ki sa nou ka tonbé oben chwézi : 73 oben 74 !
Bel poveb kréyol 74
« Si ou lé ni rézon douvan lakras, fok ou benyen tou lé jou » Man pé palé di Jean Bernabé an manniè ki lib davwè, okontrè di sa anlo moun ka kwè, sé pa li ki wouvè chimen létid lang kréyol la ba mwen. Moun-lan ki fè sa-a sé misié Guy Hazaël-Massieux, an langis gwadloupéyen estwòdinè, ki té ka fè an montray anlè kréyol atè linivèsité Aix-en-Provence éti man té étidian okoumansman sé lanné 1970 la. Man té koumansé matjé yonn-dé teks an kréyol, yonn-dé poem, ki man té ké pibliyé titak pli ta anlè tit Jou baré (1979) men ki man té ka difizé an manniè ronéotipé. Man montré G. Hazaël-Massieux sa ek i ba mwen anpil ankonfowtasion abo i pa té djè dakò épi kalté grafi-a man té ka sèvi nan lépok-tala. Epi an kanmarad guiyànè, ki té ka fè létid penti, José Legrand, man désidé difizé tou yonn-dé teks kréyol kon ta Gilbert Gratiant oben Marie-Thérèse Lung-Fou davwè man té ka touvé ki yo té two red pou trapé. Man ka chonjé man té ékri an gran-nonm Guiyàn, misié Lony, pou té mandé'y voyé ba mwen dènié ekzanplè Atipa, primié woman an kréyol ki Alfred Parépou té mété déwò an 1885 ek ki té disparet bon disparet. Jik la-Bibliyotek Nasional Pari, ou pa té pé jwenn li : fich liv-la té la men liv-la li-menm té pwan lavol. Jou-a man risivwè patjé rikoumandé-a ki té ni an ekzanplè orijinal Atipa-a adan'y lan, man kouri pòté'y La-Fak ba G. Hazaël-Massieux ek nou tou lé dé-a, nou rété estébékwé douvan sé paj liv-tala ki tout moun té ka chaché a, paj ki té vini jòn, ki té pres fennen, men éti ou té ka érisi li sé let-la toujou. Lamenm, man ronéotipé sé dé primié dékatman -an pou voyé yo ba kréyolis man té tann palé di yo ek sé kon sa man voyé an ekzanplè ba Jean Bernabé ki té ka ansénié adan « Sant Inivèsitè Fouyol », atè Gwadloup.
Sé kon sa nou antriprann koresponn épi kourilet (pis an tan-tala, faks épi kouriel pòkò té lanmod), nou koumansé konnet kò-nou ek aprésié kò-nou. Tout tan man rété Aix-en-Provence, man ékri Bernabé ek Bernabé ékri mwen san ki janmen nou té kontré, san ki man té konnet koulè fidji'y ni koulè lavwa'y davwè jounal, radio ek télé pòkò té ka palé di nou. Dayè, i pibliyé an poem ta mwen (épi désen José Legrand) adan primié limowo rèvi Espace Créole. Telman nou pa té konnet kò-nou bien, Bernabé fè an lérè : i matjé ki man té étidian…Montpellier. Konmva man té ka fè étid Sians Politik ek anglé, man pa té konnet an tjou-patat adan zafè langistik ek sé misié Guy Hazaël-Massieux primié, adan montray-li ki man suiv 3 lanné yonn dèyè lot, ki espitjé mwen sa sa yé an « fonem », sa sa yé « la double articulation » oben ankò sa sa lé di « diglosi ». Lè man fè tan rantré Matinik, pa koté 1976, man vini ka ansénié anglé adan an lékol sigondè ek man pa sav poutji men man pa pwan kontak lamenm épi Jean Bernabé. Man té endépandantis kou-koupé ek man koumansé milité adan Grif An Tè, primié jounal anni ki an kréyol ki paret atè lé Zantiy. Nou fè 52 limowo ant 1978 ek 1982. Kanmarad-mwen sé té dé militan kréyolis kon Serge Harpin, Marie-Denise Léotin, Georges-Henri Léotin oben Franck Zaïre, sé pa té dé langis pies toubannman. Sé kanmarad-tala pa té ni pies liennay épi moun ki té ka travay asou kréyol anlè kanpis Chelchè a menm si yo té ka rikonnet ki Bernabé ek sé kanmarad-li a té ka fè an travay ki sérié. Lè ou gadé, nou té ka touvé ki sé moun-tala té tibwen two fèmen adan lasians, ki yo pa té ka mennen travay-yo sifizanman andidan pep-la. Ba nou, sé pep-la ki té met-a-manyok lang kréyol-la ek sé bò'y, falé nou té alé pou té rivé trapé bon grenn kréyol-la. Sa vré ki larel-lidé nou té titak maois nan lépok-tala davwa nou té ka di fok pa « ba pep-la lapawol » men fok « sé pep-la ki pwan lapawol ». Ek sé anni ki adan lang-li, lang natif-natal li, fok i té fè'y, pa adan ta kolonizatè fwansé a. Man pa kwè man mété pié plis ki kat oben 5 fwa anlè kanpis Chelchè a ant 1979 ek 1982. Man pa kwè man palé plis ki sa épi Jean Bernabé ki man té ka jwenn délè adan dé konsit Débat ; asou kréyol. Liennay-nou té obidjoul men nou pa té ni pies pwojé woulé ansanm. Nou té ka konsivwè ki travay-la i té ka fè a adan linivèsité-a ek tala man té ka fè atravè Grif An Tè a té konplémantè men ki nou pa té bizwen maché bwaré a tout fos. -tala
Sa ki konyen lespri-mwen plis lè man fè tan jwenn épi Jean Bernabé, sé modesti nonm-lan. Pou an boug ki té agréjé gramè ek doktè an langistik, an boug ki té jenn pasé sé lézot koleg-li a, man té ka touvé ki i pa té ka fè konparézon, i pa té ka fè ganm. Okoumansman, man jis pwan atitid-tala pou an atitid timid. I pa janmen chaché mété Grif An Tè anba lopsion'y abo i pa té dakò anlè larel-lidé nou ek i jis fè pwop jounal kréyol-li, Kabouya. Nou menm, nou adopté sistenm grafi a i té pwopozé a menm si nou té sav nou té ké ni bon difikilté pou vann jounal-nou an davwè, an tan-tala, moun pòkò té abitié épi grafi fonétik la. Kidonk sé lè Grif An Tè mò, lè lanné 1983 pwan ki, an mizi an mizi, man koumansé rapwoché kò-mwen di GEREC, krey-wouchach anlè kréyol Bernabé té kréyé a dépi lè Fakilté dé Let la té Gwadloup. Man vini konnet Robert Fontes, Donald Colat-Jolivière ek Danick Zandronis ki sé dé Gwadloupéyen, Jean-Luc Bonniol ek Robert Damoiseau ki sé dé fwansé, ek, titak pli ta, Clairis-Gautier, Yona Jérome ek Marie-José Saint-Louis ki sé dé Matinitjez. Man té koumansé ka milité adan défans laliwonday Matinik adan an krey-moun yo ka kriyé ASSAUPAMAR éti met-a-manyok li té Garcin Malsa, ki mè endépandantis Sentàn jòdi jou. Kivédi man té an militan politik toujou ek man té ka wè goumen an favè lang kréyol la kon an mòso adan gran goumen jénéral la nou té ka mennen an pou érisi kaskod épi lopsionnay fwansé a. Adan menm balan-an, man kontinié piblié liv an kréyol kontel Jik dèyè do Bondié (1981), Bitako-a (1985) oben Kod Yanm (1986) alè pwa kò-mwen, san mandé pèsonn pies kalté model pal. Pou montré a ki pwen, Bernabé épi mwen nou pòkò té konplis, i matjé an kritik anlè Jik dèyè do Bondié adan limowo 2 Espace Créole ki té asé red ek ki fè mwen titak lapenn. I té ka touvé ki lang kréyol-mwen an té lou ek ki man pa té ka rivé raché kréyol-la adan migan oralité a i té ka benyen adan'y lan. Lè man ka viré li kritik-tala pliziè lanné apré, man blijé konstaté ki Bernabé té ni rézon : kritik-li a té jis. Ek sa ka ba mwen lokazion révélé an dézienm kalité lakay langis matinitjé-a, an kalité ki anlo moun pa konnet oben ka rifizé konnet : Bernabé sé an boug ki pli red épi moun i konnet, épi moun i ka aprésié ki épi moun ki pa kanmarad-li. Ek redté-tala, sé pa an manniè pou'y montré ki i pli grangrek oben pli antèlijan ki pèsonn mé okontrè pou blijé moun-lan katjilé anlè kréyol an manniè ki siantifik. Twop moun nan lépok-tala, mwen primié douvan, té ka migannen twop larel-lidé épi wouchach anlè kréyol. Jean Bernabé sé an boug ki ni an ekzijans siantifik ki wo toubannman men si i pa janmen chaché séré ki, dèyè zafè kréyol la, pa ni anni ki lasians, ni an goumen idéolojik tou. Sa i té ka di sé ki fok mennen djoubak siantifik la dabò ek gadé-wè sé laspé idéyolojik la apré ek man blijé rikonnet atjèman ki i té ni rézon. Sé pa koté 1984 man antré adan krey-wouchach GEREC la ek man vini -montray adan Fakilté dé Let Chelchè a toupannan man té ka kontinié ansénié anglé adan lisé-mwen. Ek sé an fwa man antré adan'y ki man pwan konsians di an lot kalité Bernabé : fos travay-li ek lespri vizionnè'y. Si ni an moun ki fenyan, sé pa Jean Bernabé ! Okontrè di anlo inivèsité ki ka kontanté kò-yo di viv anlè an tez éti yo pasé lè yo té ni 25 an oben 30 anlè tet-yo ek ki tout lèrestan kariè-yo ka jakoté sé menm bagay-la, i té ka kontinié woulé red adan larel-wouchach li ek sé konsa i mété doubout 4 rèvi :
_ ESPACE CREOLE : an rèvi langistik pou étidié lang ek kilti kréyol la.
_ MOFWAZ : an rèvi pédagojik pou difizé bò sé enstititè-a ek sé pwofésè lékol sigondè a finaldikont sé wouchach GEREC-la.
_ TEXTES-ETUDES ET DOCUMENTS : an rèvi litérati pou katjilé anlè litérati antiyez la.
_ KABOUYA : an rèvi ki té matjé enki an kréyol pou vréyé douvan an kréyol nef, an kréyol matjé.
Mennen tou sa pres li yonn, pa té rédi chez bò tab ba Bernabé men nonm-lan té ni an lénerji ki té ka ba tout moun lafos alantou'y ek adan dis primié lanné lekzistans GEREC, nou pé di ki krey-wouchach la kraché-difé. Sé poutji, lè jounal fwansé Le Point fè an artik, an 1985, asou sé 20 jenn inivèsitè fwansé-a ki té pli briyan an, ki té ni plis divini douvan yo, enben sel inivèsitè antiyé yo ritienn sé té Jean Bernabé. Men man pòkò djè palé asou lespri vizionnè nonm-lan ek 25 lanné apré, lespri-tala ka konyen lespri-mwen plis ankò. Poutji ? Sé davwè Jean Bernabé toujou pansé ki divini a lang ek kilti kréyol la ka pasé atravè lékol-la, ki aprézan, konmva transmision nennenn lan pa ka djè fet ankò, fok sé lékol ki viré pwan sèbi-a osnon lang-lan ké disparet net-é-pwop. Sé poutji an lanné 1982, i mété doubout Linivèsité livènay kréyol anlè kanpis Chèlchè éti i sanblé met-lékol matinitjé, gwadloupéyen ek guiyanè pou ba yo an fòmasion asou langistik, litérati, antwopoloji ek listwè kréyol. Sé la dé Guiyanè kon Christiane Taubira, Emmanuella Rattier, Aline Chanol oben dé Matinitjé kon Nicole Rémion ek Marcel Lebielle trapé yonn-dé zouti ki pèmet yo ay pli douvan adan katjilasion yo. Apré étap-tala, Jean Bernabé désidé kréyé an diplom linivèsité an kréyol éti non'y sé D.U.L.C.C (Diplôme universitaires de Langues et Cultures Créoles) ki vini apré D.U.L.C.R. (Diplôme universitaire de langues et cultures régionales). Laplipa adan primié jénérasion étidian D.U.L.C.R, sé té moun ki té fè « Linivèsité livènay kréyol » kivédi dé moun ki té za ka fè lékol ; délè dé moun ki té ja ni an lisans, an métriz oben an CAPES adan an lot matiè. Sa ki té pli fèo épi diplom-tala, sé ki non selman i té ka woulé anlè sé 3 kanpis Linivèsité lé Zantiy ek la Guiyàn men Sent-Lisi ek Dominik tou. Sé primié diplom toutwonlatè Linivèsité lé Zantiy ek la Guiyàn mété doubout ek diplom-tala diré 5 lanné ek fòmé apochan 30 moun adan sé dé zil anglo-kréyolopal la. Sa ka montré ki Jean Bernabé pa té ka konsivwè kréyol-la adan an larel lonbrikè men okontrè adan an larel ki wouvè asou tout sé péyi kréyolopal la Karayib la. Ba'y, fok nou té rivé bwaré an mizi an mizi sé diféran kréyol-la pou rivé konstwi an gran lang kréyol matjé ki nou té ké sèvi dépi Ayiti pou rivé jik an Guiyàn. Mété étidian pliziè péyi kréyolopal ka travay anlè sé menm sijé-a té an prèmié balan adan direksion-tala. Apré « Linivèsité Livènay kréyol », apré « D.U.L.C.R. », Jean Bernabé désidé vansé pli douvan ankò lè zot wè sé lanné 90-la pwan : i goumen pou trapé an lisans ek an métriz kréyol. Goumen-tala té red davwè té ni anlo moun, adan linivèsité lé Zantiy ek la Guiyàn, ki pa té ka wè nésésité mété kalté diplom-tala doubout. Dé sèten adan yo té ka di ki sé étidian-an pa té ké ni pies débouché ; dot té ka di olié kréyé an diplom ba kréyol, poutji pa mété montray kréyol adan lisans Let Modèn. Bernabé pa ladjé mòdan douvan sé alvèsè-tala ek i érisi fè pwojé'y la wè jou.
Raphaël CONFIANT Messié, Dam, sé MetoBôkay ka palé ba zôt!
Dé mo kat pawol pou di, mwen kontan wè zôt.
Mové tan, sé lè i ni siklon, zoraj, la pli ki pa ka fini, twop chalè, twop van, twop frédi, twop sab.. (Pa tout an sèl kou...)
MétéoBôkay sé lé ni an palé bôkay, lokal, épi kréyol-la chak lè.. Mè tout moun pa sa li kreyol, ta mwen yan pa djè fô, é ni dé lè, i méyè en fwansé, pass kreyol-la pa ni an lo mo siantifik, fok mété an lo mo kreyol youn dèyè lôt, pou di an sèl mo siantifik fwansé, sa ka fè'w pèd tan...
Alô MétéoBôkay, ka palé ba'w an lè Twitè (isiya too, ou la ka li mwen...) épi ti tak fwansé, ti tak anglé, ti tak kreyol, konsa, ki manniè i yé, zôt pé komprann... ti tak.
MétéoBokay pa rèd pou li (sof jodi-a si zôt pa sa li kreyol...) Man pa biswen izé an lo mo kompliké pou di zôt kon sa : 'Siklon va vini an do'w, finmin kô'w kay ou'
Mé sa ka rivé ke man ka voyé zôt li an bagay, pli détayé an lè Internet. Ki y an anglé, ki y an fwansé, ni an lo chif matjé, an lo mo siantifik.. Mèmm si ni koulè pou i pli fasil, ni moun ki ka lité pou komprann, pass yo lé sav pa yo memm...
Mé si ou sèlmen lé sav si ou an danjé, ki ou komprann, ki ou pa komprann sa ki matjé kon fos van, fos lanmè, chimin, sa pa an pwoblem.
Dépi ou ka suiv sa sé ofisiel la ka di, ou pé sav li a tan, sové kô'w, sové zafè'w, alô i bon.
Sa té MétéoBokay pou sa ki sa li kreyol, mèmm lè i mal matjé... Ou ja sav...
Pa ni an mwa, nou té ka vréyé bon labou, pas Jennkarlos té vini Matinik, pou té sa wè fanatik-li. Ében kou-tala, i pa vini Fòdfrans, i monté pa dan Linò. Lémami pé ké ni lapenn fè kar pou désann an vil. Kou-tala, ou sé di sa ki enmen misié pli chansé, pas biyé-a titak mwen chè, (i a 35 éro selman, avan sété 50 éro).
Simenn pasé sé té Jounen Entènasional Kréyol, é kon chak jou, man ka aprann an bagay nouvo. Man té ja tann dépi lontan, ki kréyol sé pa té an lang. Andidan Antilla, man wè an gran mè an komin ki lianné épi Lasoufriyè Sent-Lisi, ki pran bon fè épi Toma, té ka pousuiv jounal-la. An menm balan-an, man aprann ki adan komin Sentàn, sé té épi kréyol yo té ka bokanté épi sé lézot péyi-a. Yo jik mété atè épi Gwadloup, an Fédérasion Kolektivité Kréyolopal andidan Lakarayib (FCCC) pou bokanté épi Karayib-la.
Man aprann, menm manniè té ni « fransé-bannann » éti moun ka fè kawo, atjelman i ni « kréyol ponm-tè ». Tout moun ka fè fot, ka fè sa yo lé, ka ékri'y an gou-yo, ka palé'y gro gra épi épé, pèsonn pa ka di ayen, yo pa ka fè lafet épi sa. Akondi Janklod Diverjé : « Lè ou piti, fout ou ka pran fè ». Lè ou sé an piti lang, an piti pep, an ti-zizin nasion ek an ti-gigin kilti : fout ou ka pran fè !
Chak bètafé ka kléré pou nam-li, an patjé parti politik ka fè sa yo pé pou yo douvan-douvan. Anni gadé Dominik (sé pa péyi-a ki an fas Gran-Riviè a, mé tala ki té prèmié minis-la) ében, i ka vini sé tan prochen andidan an lékol pou i palé di an liv asou Sézè. Tousa fè ki magré Marni lajòl dépi pasé karantan, i pres ped tout tet-li. Sé bien pou sa yo vréyé'y Kolson. Sé pa li selman ka di Matinik ka pati pa tet ek ka planté létjet. Ni moun ka di :
- Ni lontan i ja tjou-pou-tet !
Bel poveb kréyol 127
Ou sé di pou Ayiti, Toma pa ka distrè : « Pli ou déchiré, pli chien ralé'w » épi : « Sé lè'w déchiré ou ka jwenn belmè'w ». Sé dépi lanné 2.000 an asosiyasion Chinwa l'Afrik di Sid té ka goumen pou sa obtienn estati « Neg ». Lè yo wè yo pa ka obtienn satisfaksion, yo mété gouvelman péyi a douvan tribinal ek sé jou-tala, yo fini pa genyen. Sa pé paret tibwen dwol ki Chinwa mandé ki yo klasé yo kon « Neg », men fok sav ki adan nouvo réjim sid-afritjen an, tala ki suiv réjim l'Aparted la, 3 katégori moun obtienn mizi espésial pou fè yo vansé andidan sosiété-a : « Neg ». Métis (milat, chaben, bata-zendien, bata-chinwa kisasayésa…) . Zendien Sa ki sé mizi espésial tala ? Sé mizi ki ka pèmet, kontel, sé moun-tala achté « aksion » adan gwo sosiété a an pri ki pli ba ki pri marché-a. Sé ankò posibilité yo ni di trapé bon pos adan ki ladministrasion ki gwo sosiété. Dot mizi ankò ka prévwè ki yich-yo pé antré linivèsité san péyé menm wotè lajan ki Blan. Politik-tala, sé sa Méritjen ka kriyé « affirmative action » ek sé « Fwansé-a « discrimination positive ». Enben, ayen pa té prévwè ba sé Chinwa l'Afrik di Sid la. Fok sav ki magré yo pa anpil moun (10.000 asou an popilasion 47 million), Chinwa rivé an péyi-a dépi lanné 1670 pou sèvi travayè ba sé kolon olandé a (sa yo ka kriyé « les Boers »). Kon nou sav, primié Niopen (= éwopéyen) ki kolonizé l'Afrik di Sid, sé Olandé. Anglé débatjé titak pli ta.
An dézienm konvwa Chinwa rivé nan finisman 19è siek-la, lè zot vwè yo dékouvè lò an Afrik di Sid. Yo té vini pou fè minè. Dépi avan sistenm l'Aparted la, sé Chinwa té ja ka sibi diskriminasion ek an tan l'Aparted, sistenm rasis la té klasé yo kon « métis ». An tan–tala, an métis pa té ni menm dwa ki Blan, i pa té pé manjé adan menm restoran, monté adan menm lotobis, voyé yich-li adan menm lékol ki Blan. Mé sé vré tou ki métis té ka pwan mwens fè ki Neg. Lè zot wè l'Aparted kalpaté ek Mandela pwan pouvwè-a, nouvo réjim-la enki bliyé sé Chinwa-a net-é-pwop. Sé Chinwa-a ritouvé kò-yo san pies pozision adan nouvo sosiété-a. Yo pa té klasé ni « métis » ni « Chinwa » ni « Blan » ek bagay-tala té ka pozé yo anpil poblem. Soutou yo pa té pé bénéfisié an pies kalté manniè di sé mizi espésial la gouvelman-an té mété déwò pou pèmet Neg, métis ek Zendien ratrapé nivo rékolonmik sé Blan-an.
Atjelman, apré jijman-an ki sòti paret la, Chinwa klasé « Neg » kon yo té mandé a. Sé pétet prenmié fwa adan listwa an krey-moun ki pa ni lapo nwè ek chivé grennen ka mandé pou yo mété yo adan katégori « Neg ». Bagay-tala ka démontré nou tou ki zafè klasé moun silon ras, sé an fouti kouyonnad ! An tan a l'Aparted, annou chonjé ki sé Blan-a té ka klasé sé Japoné-a kon... « Blanc d'honneur ».
Ek poutji ? Davwa Japon sé 2è mapipi rékolonmik asou latè ek réjim l'Aparted la té blijé établi liannaj èvè'y. Antouka, atè lakay-nou, o Zantiy, lontan « Chinwa sé Neg » ! Ki Matinik ki Trinidad ki Janmayik, Chinwa ka viv ekzaktiman kon Neg dépi etsétéra tan. Jédi pasé (17/06) tout lari Fodfrans épi Matinik té tou kam. An mouch pa té ka volé pas tout moun té douvan télé-yo pou yo té sa wè « Lé Blé », kidonk Létjip dè Frans.
Ni an machann pwason ki rivé a ped vwa'y afos kriyé. Mari'y té sòti miklon épi an kanno volan. I ped vwa'y afos i kriyé :
- Volé blé, volé blé!
Yo fini pa ba "Lé Blé" an bèl volé. Meksik pa fè sik i matjé dé bi ki fè an jwè ped tet-li.
Asiparé an boug ki ni fanmi'y isi té ké anrajé telman i té ké di antrénè a an mo anlè manman'y.
Domének pa ka konprann kréyol mé i té asiré, sé pa an belbonjou misié té di'y, pas i rivé tann fout…
Es i di'y foutbol ?
Es i di'y fouté'y la...... pasians?
Pèsonn pa djè sav, mé sa ki asiré sé pa an bon bagay i di'y.
Domének mandé misié pa antré lamitan, i bay biyé palapenn-li.
Apré poudjol-tala sa frédi sé boug-la anlè téren-an.
Es sé pa sa ki fè sé boug-la jwé kon dé blé ?
Ni sipòtè ki vréyé bon flanm. Kouté sa yonn di :
- Sé blé-a pa sa chouté an sitron dan ladésant !
- Sé blé-a sé dé pié-niklé !
Mé adan tousa ni an sipòtè ki té konnet sé jwè-a kondisiré i té fè-yo. Mi sa i mété kò'y ka rakonté.

In [40]:
# download the corpora as UTF-8 text files

with open("gdl_guadeloupe_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_gdl)

with open("mqc_martinique_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_mqc)
    
with open("gfr_guyane_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_gfr)

with open("hcr_haiti_corpus.txt", "w", encoding="utf-8") as f:
    f.write(text_hcr)