# Download Creoles and French Corpora

https://huggingface.co/datasets/innadark/GlotCC-V1

https://huggingface.co/datasets/allenai/MADLAD-400

https://huggingface.co/datasets/HuggingFaceFW/fineweb-2

### 1. Fineweb-2

##### a. ISO-code cgf (Guadeloupean / Martinican)

NEXT STEPS:
- for each of the two final chosen corpora, the subset taken from them will be half train half test for each of the variety (gcf, hat, gcr), so limit of documents is 25 per corpus, 13 per splits (considering that it is doubled for gcf since it englobes MAR and GUA, so 25 for splits)
- close control of the data (éditer les fichiers téléchargés)
- le moment venu : ne garder que le texte et le tag de langue

In [1]:
# Libraries

!pip install datatrove
from datatrove.pipeline.readers import ParquetReader
import pandas as pd

Collecting datatrove
  Downloading datatrove-0.9.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: dill>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datatrove) (0.3.8)
Requirement already satisfied: fsspec>=2023.12.2 in /usr/local/lib/python3.12/dist-packages (from datatrove) (2025.3.0)
Collecting huggingface-hub<1.0,>=0.34.0 (from datatrove)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: humanize in /usr/local/lib/python3.12/dist-packages (from datatrove) (4.15.0)
Collecting loguru>=0.7.0 (from datatrove)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datatrove) (0.70.16)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from datatrove) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from datatrove) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (1.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (2.32.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->datatrove) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.34.0->datatrove) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.34.0->datatrove) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.34.0->datatrove) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.34.0->datatrove) (2026.5.20)
Downloading datatrove-0.9.0-py3-none-any.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 48.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 21.6 MB/s eta 0:00:00
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 2.7 MB/s eta 0:00:00
Installing collected packages: loguru, huggingface-hub, datatrove
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.16.1
    Uninstalling huggingface_hub-1.16.1:
      Successfully uninstalled huggingface_hub-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.0.0 requires huggingface-hub<2.0,>=1.3.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed datatrove-0.9.0 huggingface-hub-0.36.2 loguru-0.7.3

In [ ]:
# Importation from HuggingFace of the train and tests splits of the subset gcf_Latn of the corpus Fineweb-2
# The "limit" parameter determines how many documents will be streamed, fixed here to 25
# This will fetch the Guadeloupean/Martinican Creoles filtered data

# Importation with ParquetReader
data_reader_gcf_train = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/gcf_Latn/train", limit=25)
data_reader_gcf_test = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/gcf_Latn/test", limit=25)

# Reformating of the two data splits into DataFrames
df_gcf_train = pd.DataFrame([doc for doc in data_reader_gcf_train()])
df_gcf_test = pd.DataFrame([doc for doc in data_reader_gcf_test()])

# Observation of the two DataFrames
print(df_gcf_train.shape)
print(df_gcf_train.head())
print(df_gcf_test.shape)
print(df_gcf_test.head())

# Exportation into CSV files
df_gcf_train.to_csv("fineweb2_gcf_train.csv", index=False)
df_gcf_test.to_csv("fineweb2_gcf_test.csv", index=False)

2026-05-27 10:36:13.062 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1
2026-05-27 10:36:14.362 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1

(25, 4)
                                                text  \
0  billet - chronique\n- Détails\n- Publié le sam...
1  Dékré konmkwa lestravay aboli adan tout koloni...
2  Il y a deux ans était publié, sous la houlette...
3  "Counter Strike Source"\nCounter Strike Source...
4  \n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...

                                                id media  \
0  <urn:uuid:8b665f6d-1ec7-413f-9560-fbd0b941d22f>    []
1  <urn:uuid:a6ef2d6f-d2d6-4fa4-9f50-d0f0a10b4396>    []
2  <urn:uuid:f8a9a3d0-268c-4b0c-9ba4-6d439484a396>    []
3  <urn:uuid:45222417-204e-456c-8f4f-039d1210c351>    []
4  <urn:uuid:e487404b-555a-4459-ad01-5c66f450a070>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://gen...
1  {'dump': 'CC-MAIN-2013-20', 'url': 'http://ord...
2  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
3  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
4  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
(22, 4)
                                                text  \
0  Ki Amérendien, ki Afriken, ki Zendien, ki Blan...
1  Site de promotion des cultures et des langues ...
2  Tini déserten moun, yo toujou ka chèché-touvé ...
3  -\n-\n-\nPar SHAKA (Gwakafwika) le 1 Septembre...
4  A pies kalté moman yo pa santi ki andidan pep-...

                                                id media  \
0  <urn:uuid:714615e2-37b4-4af3-bdf6-e3dde81cafab>    []
1  <urn:uuid:1c674fe2-d547-4528-a685-becee13c687c>    []
2  <urn:uuid:5b227398-adf2-407e-9b99-373900017ef2>    []
3  <urn:uuid:f16c0d4c-7b6b-49b3-b333-d2ed22260c8a>    []
4  <urn:uuid:74d63b73-c97a-4532-8d67-2ce3f3b6e9cf>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
1  {'dump': 'CC-MAIN-2017-13', 'url': 'http://pot...
2  {'dump': 'CC-MAIN-2017-22', 'url': 'http://mon...
3  {'dump': 'CC-MAIN-2017-30', 'url': 'http://gwa...
4  {'dump': 'CC-MAIN-2017-30', 'url': 'http://mon...

In [ ]:
df_gcf_train

,text,id,media,metadata
0,billet - chronique\n- Détails\n- Publié le sam...,<urn:uuid:8b665f6d-1ec7-413f-9560-fbd0b941d22f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://gen..."
1,Dékré konmkwa lestravay aboli adan tout koloni...,<urn:uuid:a6ef2d6f-d2d6-4fa4-9f50-d0f0a10b4396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://ord..."
2,"Il y a deux ans était publié, sous la houlette...",<urn:uuid:f8a9a3d0-268c-4b0c-9ba4-6d439484a396>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
3,"""Counter Strike Source""\nCounter Strike Source...",<urn:uuid:45222417-204e-456c-8f4f-039d1210c351>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
4,\n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...,<urn:uuid:e487404b-555a-4459-ad01-5c66f450a070>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
5,"Mas An Nou, sé Mas a neg Gwadloup, sé Mas a mo...",<urn:uuid:8eace61a-1191-463b-bc70-bb0b54b56f9f>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://mas..."
6,"Messié, Dam, sé MetoBôkay ka palé ba zôt!\nDé ...",<urn:uuid:1661751a-bdeb-4d60-a524-4e50ab8fc32c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://met..."
7,"Dèpi lendi, an monté ba zòt on blòg ww otila a...",<urn:uuid:96d834b7-93b8-4643-9ab4-e479d71e2aab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://sha..."
8,« Bobòn fwa…\nTwa fwa bel kont ! »\nRann sèvis...,<urn:uuid:4d61ce30-164c-4b86-9d34-897fb209e916>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
9,\n\nPa rapôt a travay oben pou dé rézon pli pè...,<urn:uuid:db19b73b-61a0-41aa-90d6-d44004580c76>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
10,billet - chronique\n- Détails\n- Publié le lun...,<urn:uuid:485b0675-1c1f-4b41-89b6-47707fcf7f4a>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
11,[ Refrain ]\nShabine Glindor Miss Docterous Gi...,<urn:uuid:5cd2dc22-16b8-4267-b9ab-c36c59186f26>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
12,L’écriture en langue créole s’est d’abord dépl...,<urn:uuid:4ca9dd6b-5a05-4347-acbe-254c521e8a4c>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
13,Player mode on | off\nGrid\nList\n02:48Watch l...,<urn:uuid:0bd9d00e-459c-44d0-b75a-59e3ee42a032>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
14,Sé dépi lanné 2.000 an asosiyasion Chinwa l’Af...,<urn:uuid:b58e621b-2f14-49c9-b335-e76b338f92b6>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
15,"[Intro] :\nYeah !!, Brasco (Brasco)\nHey gué c...",<urn:uuid:3c8ba6a5-db13-4c9b-ae42-07ba3a815733>,[],"{'dump': 'CC-MAIN-2013-48', 'url': 'http://www..."
16,billet - chronique\n- Détails\n- Catégorie : B...,<urn:uuid:d876e575-e705-44b5-91db-d96e6e299e5e>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://gen..."
17,Sé jou-tala pétrolet Madinina an vèdet. Sé cho...,<urn:uuid:d3ca1c60-a08c-4e9d-a875-ba05ab75d03a>,[],"{'dump': 'CC-MAIN-2014-10', 'url': 'http://www..."
18,an chèché ... an pas touvé ...\nalò .... an ka...,<urn:uuid:18e81c5b-1631-4900-b659-b6b4721c7cb8>,[],"{'dump': 'CC-MAIN-2014-15', 'url': 'http://www..."
19,Man pé ké mélanjé sa ou fè an politik épi sa’w...,<urn:uuid:4cdfc40e-bac9-47ae-a1bc-e45971c638cf>,[],"{'dump': 'CC-MAIN-2014-23', 'url': 'http://www..."
20,"La mwen té près fin tout lantou en mwen, en té...",<urn:uuid:db6b202e-c9d6-4ab1-b36e-41f0e2c25ef0>,[],"{'dump': 'CC-MAIN-2014-42', 'url': 'http://www..."
21,Le drapeau d'Haïti est rouge et bleu organisé ...,<urn:uuid:c138fc4e-6173-4ffc-9a22-e33a0cff2a0f>,[],"{'dump': 'CC-MAIN-2015-22', 'url': 'http://www..."
22,Léssé mwen diw jan ou té ka manké mwen La nost...,<urn:uuid:15fab596-9108-479a-ac56-393d7b9dfa9a>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
23,Kouté nou\nLecture automatique sauf pour\n(Cli...,<urn:uuid:a38aad9e-547b-4409-9cab-21c58c41320f>,[],"{'dump': 'CC-MAIN-2015-40', 'url': 'http://www..."
24,"On lè, fanm touvé-yo las pran kou anba men a n...",<urn:uuid:1df21096-5351-4e16-91eb-0677be57d943>,[],"{'dump': 'CC-MAIN-2016-36', 'url': 'http://dya..."

In [ ]:
df_gcf_test

,text,id,media,metadata
0,"Ki Amérendien, ki Afriken, ki Zendien, ki Blan...",<urn:uuid:714615e2-37b4-4af3-bdf6-e3dde81cafab>,[],"{'dump': 'CC-MAIN-2013-20', 'url': 'http://www..."
1,Site de promotion des cultures et des langues ...,<urn:uuid:1c674fe2-d547-4528-a685-becee13c687c>,[],"{'dump': 'CC-MAIN-2017-13', 'url': 'http://pot..."
2,"Tini déserten moun, yo toujou ka chèché-touvé ...",<urn:uuid:5b227398-adf2-407e-9b99-373900017ef2>,[],"{'dump': 'CC-MAIN-2017-22', 'url': 'http://mon..."
3,-\n-\n-\nPar SHAKA (Gwakafwika) le 1 Septembre...,<urn:uuid:f16c0d4c-7b6b-49b3-b333-d2ed22260c8a>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://gwa..."
4,A pies kalté moman yo pa santi ki andidan pep-...,<urn:uuid:74d63b73-c97a-4532-8d67-2ce3f3b6e9cf>,[],"{'dump': 'CC-MAIN-2017-30', 'url': 'http://mon..."
5,"An mwa mé-la ki pasé la, té ni twa kongré ki f...",<urn:uuid:6cf1a325-4c44-49a3-9901-ad6f3cee8f8c>,[],"{'dump': 'CC-MAIN-2017-43', 'url': 'http://car..."
6,Corrigé Exercice n° 1\nLes particules pré-verb...,<urn:uuid:288c580f-3a86-4688-a5ee-b9ee6a8c50d8>,[],"{'dump': 'CC-MAIN-2017-51', 'url': 'http://cre..."
7,"Pa plita ki an midi a, man tann an granmoun ka...",<urn:uuid:a6dc41d7-a049-4700-8471-1cd4a4e14b91>,[],"{'dump': 'CC-MAIN-2018-05', 'url': 'http://mon..."
8,Chalè té ka lévé anba wob Létisia kifè manzel ...,<urn:uuid:3717d539-2401-4c49-996a-a4ed542d7a80>,[],"{'dump': 'CC-MAIN-2018-22', 'url': 'http://www..."
9,"Chofè an retrè, mé pa laritret\nSé sa tout sé ...",<urn:uuid:eb73bd59-9ec3-483b-a89f-b7ccd06a8d74>,[],"{'dump': 'CC-MAIN-2019-04', 'url': 'http://mon..."
10,Tan ka bay. Mémwè ka chonjé. Wi ! Lot jou a la...,<urn:uuid:f3dcca57-69b7-4a70-b0bd-d4c53d8a75b1>,[],"{'dump': 'CC-MAIN-2019-22', 'url': 'http://mon..."
11,Pawòl-palé a moun Lésent é ta moun Déhé pa tou...,<urn:uuid:f2ec55cb-4315-4582-976d-79ddc8be0633>,[],"{'dump': 'CC-MAIN-2019-30', 'url': 'http://www..."
12,Gadé vidéo-a ki pli ba teks-tala ! Sa nou ka w...,<urn:uuid:84aceb86-c508-486a-a1da-df152d55bde4>,[],"{'dump': 'CC-MAIN-2019-51', 'url': 'http://mon..."
13,Mètfédàm : En hommage à Gerty Archimède\nOu té...,<urn:uuid:8b0b2c88-8970-4caa-bd63-0807af416b1b>,[],"{'dump': 'CC-MAIN-2020-16', 'url': 'https://ww..."
14,Dékouvè kijan réinyon an nou ka déwoulé é touv...,<urn:uuid:389ed822-57e3-4323-b9b6-ad87b85ecce8>,[],"{'dump': 'CC-MAIN-2020-50', 'url': 'https://ww..."
15,"Nou ka goumen pou siklotwon, nou ka goumen pou...",<urn:uuid:851cae32-94cf-4f5a-b228-3217aa84b8f9>,[],"{'dump': 'CC-MAIN-2021-04', 'url': 'http://www..."
16,"Dézienm bagay nou pé konstaté tou, sé ki l'Eko...",<urn:uuid:16940138-2bf9-41d3-8e31-e324112b8b0d>,[],"{'dump': 'CC-MAIN-2021-17', 'url': 'http://mon..."
17,"Jòdijou, kontel an zwézo yo démaré zel-li, lan...",<urn:uuid:2753ab82-728a-4d99-a233-5d1cb5b2d22c>,[],"{'dump': 'CC-MAIN-2021-43', 'url': 'https://ww..."
18,« Roch dan dlo pa konnet doulè roch dan solèy”...,<urn:uuid:3b0fd1d0-acac-4b4c-a9d6-c56f4a6d54bc>,[],"{'dump': 'CC-MAIN-2022-21', 'url': 'http://jud..."
19,"Dans le cadre du Festival haïtien ""FESTIVAL EN...",<urn:uuid:015c422e-5170-43c3-90d1-85a4af49665f>,[],"{'dump': 'CC-MAIN-2023-06', 'url': 'https://fo..."
20,Description\nDégajé & Pwòpté\nTin plizyè jan p...,<urn:uuid:534f732a-490f-4b33-924a-2e4c8e9b619f>,[],"{'dump': 'CC-MAIN-2023-14', 'url': 'https://ww..."
21,Man té ka travay épi Maksimilien LIMINO. Misié...,<urn:uuid:bedd30ca-4e19-4cb3-a83f-204a8565623b>,[],"{'dump': 'CC-MAIN-2023-40', 'url': 'https://mo..."

In [ ]:
# Combine the train and test splits into a same DataFrame
df_gcf = pd.concat([df_gcf_train, df_gcf_test], ignore_index=True)

# Check
print(df_gcf.shape)
print(df_gcf.head())

# Exportation into CSV file
df_gcf.to_csv("fineweb2_gcf.csv", index=False)

(47, 4)
                                                text  \
0  billet - chronique\n- Détails\n- Publié le sam...
1  Dékré konmkwa lestravay aboli adan tout koloni...
2  Il y a deux ans était publié, sous la houlette...
3  "Counter Strike Source"\nCounter Strike Source...
4  \n\nKreyòl\nMoun ki konnèt tibwen listwa a péy...

                                                id media  \
0  <urn:uuid:8b665f6d-1ec7-413f-9560-fbd0b941d22f>    []
1  <urn:uuid:a6ef2d6f-d2d6-4fa4-9f50-d0f0a10b4396>    []
2  <urn:uuid:f8a9a3d0-268c-4b0c-9ba4-6d439484a396>    []
3  <urn:uuid:45222417-204e-456c-8f4f-039d1210c351>    []
4  <urn:uuid:e487404b-555a-4459-ad01-5c66f450a070>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://gen...
1  {'dump': 'CC-MAIN-2013-20', 'url': 'http://ord...
2  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
3  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
4  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...

##### b. ISO-code cgr (Guyanese)

In [ ]:
# Importation from HuggingFace of the train and tests splits of the subset gcr_Latn of the corpus Fineweb-2
# The "limit" parameter fixed here to 13
# This will fetch the Guyanese Creole filtered data

# Libraries needed already imported

# Importation
data_reader_gcr_train = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/gcr_Latn/train", limit=13)
data_reader_gcr_test = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/gcr_Latn/test", limit=13)

# Reformating into DataFrames
df_gcr_train = pd.DataFrame([doc for doc in data_reader_gcr_train()])
df_gcr_test = pd.DataFrame([doc for doc in data_reader_gcr_test()])

# Check
print(df_gcr_train.head())
print(df_gcr_train.dtypes)
print(df_gcr_test.head())
print(df_gcr_test.dtypes)

# Exportation into CSV files
df_gcr_train.to_csv("fineweb2_gcr_train.csv", index=False)
df_gcr_test.to_csv("fineweb2_gcr_test.csv", index=False)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
2026-05-27 15:48:32.672 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1
2026-05-27 15:48:33.768 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1

                                                text  \
0  VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...
1  Lé ven senk(25) mè démildis(2010) tout éléktér...
2  Communique de presse du 16 octobre 2013\nALE L...
3  1)LONI : POUKISA LAGWIYANN NOU PA ANNAN SA ?\n...
4  Lo nou té wè lit bann moun-yan ki té jwenn ann...

                                                id media  \
0  <urn:uuid:a75ceea1-b219-4638-8e00-02acb367c1db>    []
1  <urn:uuid:466cbd4c-2ac3-428c-be47-7542f3a43441>    []
2  <urn:uuid:db5e1e9c-cd46-4030-822f-557f8fb844bb>    []
3  <urn:uuid:c9a5e8cb-04ae-444a-bc44-8ce3bcf37cb4>    []
4  <urn:uuid:179977e2-4c73-41e4-8447-326efedd77a0>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
1  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
2  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
3  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
4  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
text        object
id          object
media       object
metadata    object
dtype: object
                                                text  \
0  Grann Dépresyon\nGrann Déprésyon-an (The Great...
1  Ion\nOun ion oben yon est sa roun atom oben ro...
2  Jé di sosyété\nJé di sosyété-a sa roun jé ki k...
3  Tablo péryodik di sé éléman\nTablo péryodik dé...
4  Artiri\nNou ka aplé artiri ansanm-an dé arm ko...

                                                id media  \
0  <urn:uuid:d2d3d1ae-fcd2-41ab-adcb-67e7521c34c5>    []
1  <urn:uuid:bbb0a98e-31c1-450b-a4fe-96d6b3b4b9a6>    []
2  <urn:uuid:9fd27054-1b1f-468c-ac9b-96814f368d4b>    []
3  <urn:uuid:96ee8b29-40ec-47a5-8f6c-7c2cf89c5c24>    []
4  <urn:uuid:37f83382-a0ea-4099-9d16-d77c19ad413b>    []

                                            metadata
0  {'dump': 'CC-MAIN-2020-05', 'url': 'https://gc...
1  {'dump': 'CC-MAIN-2020-05', 'url': 'https://gc...
2  {'dump': 'CC-MAIN-2020-05', 'url': 'https://gc...
3  {'dump': 'CC-MAIN-2020-05', 'url': 'https://gc...
4  {'dump': 'CC-MAIN-2020-10', 'url': 'https://gc...
text        object
id          object
media       object
metadata    object
dtype: object

In [ ]:
# Combine the train and test splits into a same DataFrame
df_gcr = pd.concat([df_gcr_train, df_gcr_test], ignore_index=True)

# Check
print(df_gcr.shape)
print(df_gcr.head())

# Exportation into CSV file
df_gcr.to_csv("fineweb2_gcr.csv", index=False)

(21, 4)
                                                text  \
0  VOTÉ POU TO PÉI\nVOTÉ POU LAGWIYANN\nVOTÉ POU ...
1  Lé ven senk(25) mè démildis(2010) tout éléktér...
2  Communique de presse du 16 octobre 2013\nALE L...
3  1)LONI : POUKISA LAGWIYANN NOU PA ANNAN SA ?\n...
4  Lo nou té wè lit bann moun-yan ki té jwenn ann...

                                                id media  \
0  <urn:uuid:a75ceea1-b219-4638-8e00-02acb367c1db>    []
1  <urn:uuid:466cbd4c-2ac3-428c-be47-7542f3a43441>    []
2  <urn:uuid:db5e1e9c-cd46-4030-822f-557f8fb844bb>    []
3  <urn:uuid:c9a5e8cb-04ae-444a-bc44-8ce3bcf37cb4>    []
4  <urn:uuid:179977e2-4c73-41e4-8447-326efedd77a0>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
1  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
2  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
3  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...
4  {'dump': 'CC-MAIN-2016-50', 'url': 'http://rot...

##### c. ISO-code hat (Haitian)

In [ ]:
# Importation from HuggingFace of the train and tests splits of the subset hat_Latn of the corpus Fineweb-2
# The "limit" parameter fixed here to 15
# This will fetch the Haitian Creole filtered data

# Libraries needed already imported

# Importation
data_reader_hat_train = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/hat_Latn/train", limit=13)
data_reader_hat_test = ParquetReader("hf://datasets/HuggingFaceFW/fineweb-2/data/hat_Latn/test", limit=13)

# Reformating into DataFrames
df_hat_train = pd.DataFrame([doc for doc in data_reader_hat_train()])
df_hat_test = pd.DataFrame([doc for doc in data_reader_hat_test()])

# Check
print(df_hat_train.head())
print(df_hat_train.dtypes)
print(df_hat_test.head())
print(df_hat_test.dtypes)

# Exportation into CSV files
df_hat_train.to_csv("fineweb2_hat_train.csv", index=False)
df_hat_test.to_csv("fineweb2_hat_test.csv", index=False)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
2026-06-02 14:28:49.211 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1
2026-06-02 14:28:50.436 | INFO     | datatrove.pipeline.readers.base:read_files_shard:206 - Reading input file 000_00000.parquet, 1/1

                                                text  \
0  Foutbòl\nUSC foutbòl Jwè bati kay yo an Ayiti\...
1  Otorite nan Repiblik Demokratik Kongo, mande s...
2  About the Caribbean Sea Migration Collection\n...
3  1Men non pitit Jakòb yo ki te desann avè l’ na...
4  Senatè Jean William Jeanty (Depatman Nip) deno...

                                                id media  \
0  <urn:uuid:f3edc588-d4bf-4cef-8d52-39301cc65c00>    []
1  <urn:uuid:788d7917-dbcf-4285-ada3-79f8a40dc36f>    []
2  <urn:uuid:d16d3508-920c-4ad2-ba40-c16f5ffd26c7>    []
3  <urn:uuid:fdf2184e-27f6-4d9d-b071-aefd163d4413>    []
4  <urn:uuid:c153f695-a8b5-422e-b6be-92c31368be14>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
1  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
2  {'dump': 'CC-MAIN-2013-48', 'url': 'http://lib...
3  {'dump': 'CC-MAIN-2013-48', 'url': 'http://www...
4  {'dump': 'CC-MAIN-2013-48', 'url': 'http://www...
text        object
id          object
media       object
metadata    object
dtype: object
                                                text  \
0  Creole 0.9.5 te lage pa twò lontan de sa, ak v...
1  Chapter 14\n1\n¶ Gade! Men jou jijman Seyè a a...
2  Ayiti 1 an apre, se tit yon konferans Lavwadla...
3  Jwenn yon gade pi pre ki jan anplwaye IRS te p...
4  Bailey Ryder se yon enstriktè fè egzèsis vire ...

                                                id media  \
0  <urn:uuid:ea2c3e21-00ff-4efc-89fe-555d1ba2bf62>    []
1  <urn:uuid:20f6036f-814c-4c9f-9771-b015ff39d18a>    []
2  <urn:uuid:2797c047-9d82-4b32-9b32-307d56f4d886>    []
3  <urn:uuid:b3aa0bde-35f9-44e7-9bb5-b080b0d63f24>    []
4  <urn:uuid:c6a203e2-7d30-4ac6-8992-085a24b65dd0>    []

                                            metadata
0  {'dump': 'CC-MAIN-2014-41', 'url': 'http://tra...
1  {'dump': 'CC-MAIN-2017-13', 'url': 'http://www...
2  {'dump': 'CC-MAIN-2021-04', 'url': 'https://ww...
3  {'dump': 'CC-MAIN-2022-21', 'url': 'https://ww...
4  {'dump': 'CC-MAIN-2022-21', 'url': 'https://vi...
text        object
id          object
media       object
metadata    object
dtype: object

In [4]:
# Combine the train and test splits into a same DataFrame
df_hat = pd.concat([df_hat_train, df_hat_test], ignore_index=True)

# Check
print(df_hat.shape)
print(df_hat.head())

# Exportation into CSV file
df_hat.to_csv("fineweb2_hat.csv", index=False)

(30, 4)
                                                text  \
0  Foutbòl\nUSC foutbòl Jwè bati kay yo an Ayiti\...
1  Otorite nan Repiblik Demokratik Kongo, mande s...
2  About the Caribbean Sea Migration Collection\n...
3  1Men non pitit Jakòb yo ki te desann avè l’ na...
4  Senatè Jean William Jeanty (Depatman Nip) deno...

                                                id media  \
0  <urn:uuid:f3edc588-d4bf-4cef-8d52-39301cc65c00>    []
1  <urn:uuid:788d7917-dbcf-4285-ada3-79f8a40dc36f>    []
2  <urn:uuid:d16d3508-920c-4ad2-ba40-c16f5ffd26c7>    []
3  <urn:uuid:fdf2184e-27f6-4d9d-b071-aefd163d4413>    []
4  <urn:uuid:c153f695-a8b5-422e-b6be-92c31368be14>    []

                                            metadata
0  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
1  {'dump': 'CC-MAIN-2013-20', 'url': 'http://www...
2  {'dump': 'CC-MAIN-2013-48', 'url': 'http://lib...
3  {'dump': 'CC-MAIN-2013-48', 'url': 'http://www...
4  {'dump': 'CC-MAIN-2013-48', 'url': 'http://www...

Autre code possible :
```
Using huggingface_hub

from huggingface_hub import snapshot_download
folder = snapshot_download(
                "HuggingFaceFW/fineweb-2",
                repo_type="dataset",
                local_dir="./fineweb2/",
                # download the Czech filtered + removed data
                allow_patterns=["data/ces_Latn/train/*", "data/ces_Latn_removed/train/*"])

# For faster downloads, make sure to install pip install huggingface_hub[hf_transfer] and set the environment variable HF_HUB_ENABLE_HF_TRANSFER=1.

# Load the dataset from a Parquet file
# Replace the file path with the path to the desired language's Parquet file
dataset = pd.read_parquet('./path/to/glotcc-v1/v1.0/bal-Arab/bal-Arab_0.parquet')

# Print the first 5 rows of the dataset
print(dataset.head())
```

### 2. Filtering and downlading GlotCC
##### a. ISO-code cgf (Guadeloupean / Martinican)

In [ ]:
import requests

response = requests.get("https://huggingface.co/api/datasets/innadark/GlotCC-V1/tree/main/v1.0")
files = response.json()

for f in files:
    print(f["path"])

v1.0/aau-Latn
v1.0/aaz-Latn
v1.0/abk-Cyrl
v1.0/abq-Cyrl
v1.0/abs-Latn
v1.0/abt-Latn
v1.0/abx-Latn
v1.0/aby-Latn
v1.0/ace-Latn
v1.0/acf-Latn
v1.0/ach-Latn
v1.0/acm-Arab
v1.0/acn-Latn
v1.0/acr-Latn
v1.0/acu-Latn
v1.0/ada-Latn
v1.0/adi-Latn
v1.0/adj-Latn
v1.0/ady-Cyrl
v1.0/adz-Latn
v1.0/aeb-Arab
v1.0/aer-Latn
v1.0/aey-Latn
v1.0/afr-Latn
v1.0/agd-Latn
v1.0/agm-Latn
v1.0/agn-Latn
v1.0/agr-Latn
v1.0/agt-Latn
v1.0/agu-Latn
v1.0/agw-Latn
v1.0/aii-Syrc
v1.0/aim-Latn
v1.0/ain-Latn
v1.0/ajp-Arab
v1.0/ajz-Latn
v1.0/akb-Latn
v1.0/akh-Latn
v1.0/aln-Latn
v1.0/alp-Latn
v1.0/alq-Latn
v1.0/als-Latn
v1.0/alt-Cyrl
v1.0/aly-Latn
v1.0/amf-Latn
v1.0/amh-Ethi
v1.0/ami-Latn
v1.0/amm-Latn
v1.0/amu-Latn
v1.0/ang-Latn
v1.0/ann-Latn
v1.0/anp-Deva
v1.0/any-Latn
v1.0/aoi-Latn
v1.0/aoj-Latn
v1.0/aom-Latn
v1.0/aoz-Latn
v1.0/apb-Latn
v1.0/apc-Arab
v1.0/ape-Latn
v1.0/apr-Latn
v1.0/apt-Latn
v1.0/apz-Latn
v1.0/arb-Arab
v1.0/arb-Latn
v1.0/arg-Latn
v1.0/arl-Latn
v1.0/arn-Latn
v1.0/arq-Arab
v1.0/ars-Arab
v1.0/ary-Arab
v1.0/arz-Arab
v1.0/asm-Beng
v1.0/asm-Latn
v1.0/aso-Latn
v1.0/ast-Latn
v1.0/ata-Latn
v1.0/atb-Latn
v1.0/atd-Latn
v1.0/atj-Latn
v1.0/atq-Latn
v1.0/att-Latn
v1.0/aui-Latn
v1.0/auy-Latn
v1.0/ava-Cyrl
v1.0/avk-Latn
v1.0/avt-Latn
v1.0/avu-Latn
v1.0/awa-Deva
v1.0/awx-Latn
v1.0/ayr-Latn
v1.0/azb-Arab
v1.0/azg-Latn
v1.0/azj-Cyrl
v1.0/azj-Latn
v1.0/bak-Cyrl
v1.0/bal-Arab
v1.0/bam-Latn
v1.0/ban-Latn
v1.0/bar-Latn
v1.0/bas-Latn
v1.0/bba-Latn
v1.0/bbb-Latn
v1.0/bbc-Latn
v1.0/bbr-Latn
v1.0/bch-Latn
v1.0/bci-Latn
v1.0/bcl-Latn
v1.0/bdd-Latn
v1.0/bdh-Latn
v1.0/bdq-Latn
v1.0/bef-Latn
v1.0/bel-Cyrl
v1.0/bem-Latn
v1.0/ben-Beng
v1.0/ben-Latn
v1.0/bew-Latn
v1.0/bgr-Latn
v1.0/bgs-Latn
v1.0/bgz-Latn
v1.0/bhg-Latn
v1.0/bhl-Latn
v1.0/bho-Deva
v1.0/bhw-Latn
v1.0/big-Latn
v1.0/bim-Latn
v1.0/bin-Latn
v1.0/bis-Latn
v1.0/biu-Latn
v1.0/bjn-Arab
v1.0/bjn-Latn
v1.0/bjp-Latn
v1.0/bjr-Latn
v1.0/bkd-Latn
v1.0/bkl-Latn
v1.0/blk-Mymr
v1.0/blw-Latn
v1.0/blz-Latn
v1.0/bmh-Latn
v1.0/bmu-Latn
v1.0/bno-Latn
v1.0/bnp-Latn
v1.0/boa-Latn
v1.0/bod-Tibt
v1.0/boj-Latn
v1.0/bom-Latn
v1.0/bon-Latn
v1.0/bos-Latn
v1.0/bpr-Latn
v1.0/bps-Latn
v1.0/bpy-Beng
v1.0/bqc-Latn
v1.0/bqj-Latn
v1.0/bre-Latn
v1.0/brh-Arab
v1.0/bru-Latn
v1.0/brx-Deva
v1.0/bsp-Latn
v1.0/btd-Latn
v1.0/bts-Latn
v1.0/btx-Latn
v1.0/bug-Latn
v1.0/buk-Latn
v1.0/bul-Cyrl
v1.0/bum-Latn
v1.0/bus-Latn
v1.0/bvr-Latn
v1.0/bwd-Latn
v1.0/bxh-Latn
v1.0/bxr-Cyrl
v1.0/byr-Latn
v1.0/bzd-Latn
v1.0/bzi-Thai
v1.0/bzj-Latn
v1.0/caa-Latn
v1.0/cab-Latn
v1.0/cac-Latn
v1.0/cag-Latn
v1.0/cak-Latn
v1.0/cao-Latn
v1.0/car-Latn
v1.0/cat-Latn
v1.0/cax-Latn
v1.0/cbi-Latn
v1.0/cbk-Latn
v1.0/cbr-Latn
v1.0/cbs-Latn
v1.0/cbt-Latn
v1.0/cbu-Latn
v1.0/ccp-Latn
v1.0/ceb-Latn
v1.0/ces-Latn
v1.0/cfm-Latn
v1.0/cgc-Latn
v1.0/cha-Latn
v1.0/chd-Latn
v1.0/che-Cyrl
v1.0/chk-Latn
v1.0/cho-Latn
v1.0/chu-Cyrl
v1.0/chv-Cyrl
v1.0/chw-Latn
v1.0/cjk-Latn
v1.0/cjv-Latn
v1.0/ckb-Arab
v1.0/ckm-Latn
v1.0/ckt-Cyrl
v1.0/clu-Latn
v1.0/cmn-Hani
v1.0/cmo-Latn
v1.0/cmr-Latn
v1.0/cnh-Latn
v1.0/cni-Latn
v1.0/cnk-Latn
v1.0/cnr-Latn
v1.0/cnw-Latn
v1.0/con-Latn
v1.0/cop-Copt
v1.0/cor-Latn
v1.0/cos-Latn
v1.0/cot-Latn
v1.0/cpb-Latn
v1.0/cpc-Latn
v1.0/cpy-Latn
v1.0/crh-Cyrl
v1.0/crh-Latn
v1.0/crk-Cans
v1.0/crk-Latn
v1.0/crl-Cans
v1.0/crn-Latn
v1.0/crs-Latn
v1.0/crx-Latn
v1.0/csb-Latn
v1.0/csw-Latn
v1.0/csy-Latn
v1.0/cta-Latn
v1.0/ctd-Latn
v1.0/ctu-Latn
v1.0/cub-Latn
v1.0/cuk-Latn
v1.0/cut-Latn
v1.0/cwe-Latn
v1.0/cwt-Latn
v1.0/cya-Latn
v1.0/cym-Latn
v1.0/czt-Latn
v1.0/dad-Latn
v1.0/dag-Latn
v1.0/dah-Latn
v1.0/dak-Latn
v1.0/dan-Latn
v1.0/dao-Latn
v1.0/dar-Cyrl
v1.0/ddg-Latn
v1.0/ded-Latn
v1.0/deu-Latn
v1.0/dga-Latn
v1.0/dgc-Latn
v1.0/dgz-Latn
v1.0/dhg-Latn
v1.0/dhm-Latn
v1.0/dhv-Latn
v1.0/did-Latn
v1.0/dik-Latn
v1.0/diq-Latn
v1.0/dis-Latn
v1.0/div-Thaa
v1.0/dje-Latn
v1.0/djk-Latn
v1.0/djr-Latn
v1.0/dng-Cyrl
v1.0/dob-Latn
v1.0/doi-Deva
v1.0/dop-Latn
v1.0/dru-Latn
v1.0/dsb-Latn
v1.0/dtp-Latn
v1.0/dts-Latn
v1.0/dua-Latn
v1.0/dwr-Ethi
v1.0/dww-Latn
v1.0/dyi-Latn
v1.0/dyo-Latn
v1.0/dyu-Latn
v1.0/dzo-Tibt
v1.0/efi-Latn
v1.0/ekk-Latn
v1.0/eko-Latn
v1.0/ell-Grek
v1.0/emi-Latn
v1.0/eml-Latn
v1.0/emp-Latn
v1.0/eng-Latn
v1.0/enl-Latn
v1.0/enm-Latn
v1.0/enq-Latn
v1.0/epo-Latn
v1.0/eri-Latn
v1.0/esk-Latn
v1.0/esu-Latn
v1.0/etr-Latn
v1.0/eus-Latn
v1.0/eve-Cyrl
v1.0/ewe-Latn
v1.0/ewo-Latn
v1.0/ext-Latn
v1.0/eza-Latn
v1.0/faa-Latn
v1.0/fai-Latn
v1.0/fao-Latn
v1.0/fas-Arab
v1.0/fat-Latn
v1.0/ffm-Latn
v1.0/fij-Latn
v1.0/fil-Latn
v1.0/fin-Latn
v1.0/fit-Latn
v1.0/fkv-Latn
v1.0/fon-Latn
v1.0/for-Latn
v1.0/fra-Latn
v1.0/fro-Latn
v1.0/frp-Latn
v1.0/frr-Latn
v1.0/fry-Latn
v1.0/fub-Latn
v1.0/fud-Latn
v1.0/fue-Latn
v1.0/fuf-Latn
v1.0/fuh-Latn
v1.0/fur-Latn
v1.0/fuv-Latn
v1.0/gaa-Latn
v1.0/gag-Latn
v1.0/gah-Latn
v1.0/gai-Latn
v1.0/gam-Latn
v1.0/gaw-Latn
v1.0/gaz-Latn
v1.0/gbi-Latn
v1.0/gcf-Latn
v1.0/gcr-Latn
v1.0/gdg-Latn
v1.0/gdn-Latn
v1.0/geb-Latn
v1.0/gfk-Latn
v1.0/ghs-Latn
v1.0/gil-Latn
v1.0/gjn-Latn
v1.0/gla-Latn
v1.0/gle-Latn
v1.0/glg-Latn
v1.0/glk-Arab
v1.0/glv-Latn
v1.0/gmh-Latn
v1.0/gmv-Ethi
v1.0/gnb-Latn
v1.0/gng-Latn
v1.0/gnn-Latn
v1.0/gnw-Latn
v1.0/goh-Latn
v1.0/gom-Deva
v1.0/gom-Latn
v1.0/gor-Latn
v1.0/gos-Latn
v1.0/got-Goth
v1.0/got-Latn
v1.0/grc-Grek
v1.0/gsw-Latn
v1.0/gub-Latn
v1.0/guc-Latn
v1.0/gug-Latn
v1.0/guj-Arab
v1.0/guj-Gujr
v1.0/guj-Latn
v1.0/gul-Latn
v1.0/gum-Latn
v1.0/gur-Latn
v1.0/guw-Latn
v1.0/gux-Latn
v1.0/guz-Latn
v1.0/gvn-Latn
v1.0/gwi-Latn
v1.0/gwr-Latn
v1.0/gym-Latn
v1.0/gyr-Latn
v1.0/hac-Arab
v1.0/hag-Latn
v1.0/hak-Latn
v1.0/hat-Latn
v1.0/hau-Latn
v1.0/haw-Latn
v1.0/hbo-Hebr
v1.0/hch-Latn
v1.0/heb-Hebr
v1.0/heg-Latn
v1.0/her-Latn
v1.0/hif-Latn
v1.0/hil-Latn
v1.0/hin-Deva
v1.0/hin-Latn
v1.0/hla-Latn
v1.0/hmo-Latn
v1.0/hmr-Latn
v1.0/hne-Deva
v1.0/hnj-Latn
v1.0/hns-Latn
v1.0/hot-Latn
v1.0/hra-Latn
v1.0/hrv-Latn
v1.0/hsb-Latn
v1.0/hto-Latn
v1.0/hub-Latn
v1.0/hui-Latn
v1.0/hun-Latn
v1.0/hus-Latn
v1.0/huu-Latn
v1.0/hvn-Latn
v1.0/hwc-Latn
v1.0/hye-Armn
v1.0/hyw-Armn
v1.0/ian-Latn
v1.0/iba-Latn
v1.0/ibg-Latn
v1.0/ibo-Latn
v1.0/icr-Latn
v1.0/ido-Latn
v1.0/idu-Latn
v1.0/ify-Latn
v1.0/ike-Cans
v1.0/ikk-Latn
v1.0/ikt-Latn
v1.0/ikw-Latn
v1.0/ile-Latn
v1.0/ilo-Latn
v1.0/ina-Latn
v1.0/inb-Latn
v1.0/ind-Latn
v1.0/inh-Cyrl
v1.0/ino-Latn
v1.0/iou-Latn
v1.0/ipi-Latn
v1.0/iqw-Latn
v1.0/isd-Latn
v1.0/ish-Latn
v1.0/isl-Latn
v1.0/iso-Latn
v1.0/ita-Latn
v1.0/itv-Latn
v1.0/ium-Latn
v1.0/ivb-Latn
v1.0/ivv-Latn
v1.0/iws-Latn
v1.0/ixl-Latn
v1.0/jac-Latn
v1.0/jae-Latn
v1.0/jam-Latn
v1.0/jav-Latn
v1.0/jbo-Latn
v1.0/jiv-Latn
v1.0/jpn-Jpan
v1.0/jra-Latn
v1.0/jvn-Latn
v1.0/kaa-Cyrl
v1.0/kaa-Latn
v1.0/kab-Latn
v1.0/kac-Latn
v1.0/kak-Latn
v1.0/kal-Latn
v1.0/kam-Latn
v1.0/kan-Knda
v1.0/kan-Latn
v1.0/kaq-Latn
v1.0/kas-Arab
v1.0/kas-Deva
v1.0/kat-Geor
v1.0/kaz-Cyrl
v1.0/kbc-Latn
v1.0/kbd-Cyrl
v1.0/kbh-Latn
v1.0/kbm-Latn
v1.0/kbo-Latn
v1.0/kbp-Latn
v1.0/kbq-Latn
v1.0/kby-Latn
v1.0/kca-Cyrl
v1.0/kcg-Latn
v1.0/kck-Latn
v1.0/kdc-Latn
v1.0/kde-Latn
v1.0/kdi-Latn
v1.0/kdl-Latn
v1.0/kea-Latn
v1.0/kek-Latn
v1.0/kew-Latn
v1.0/kgk-Latn
v1.0/kgr-Latn
v1.0/kha-Latn
v1.0/khk-Cyrl
v1.0/khm-Khmr
v1.0/khz-Latn
v1.0/kij-Latn
v1.0/kik-Latn
v1.0/kin-Latn
v1.0/kir-Cyrl
v1.0/kiu-Latn
v1.0/kix-Latn
v1.0/kjb-Latn
v1.0/kjh-Cyrl
v1.0/kjs-Latn
v1.0/kkc-Latn
v1.0/kkl-Latn
v1.0/klt-Latn
v1.0/klv-Latn
v1.0/kmb-Latn
v1.0/kmd-Latn
v1.0/kmg-Latn
v1.0/kmh-Latn
v1.0/kmk-Latn
v1.0/kmm-Latn
v1.0/kmr-Cyrl
v1.0/kmr-Latn
v1.0/kms-Latn
v1.0/kmu-Latn
v1.0/kmy-Latn
v1.0/knc-Latn
v1.0/kne-Latn
v1.0/kng-Latn
v1.0/knv-Latn
v1.0/kog-Latn
v1.0/koi-Cyrl
v1.0/kor-Hang
v1.0/kos-Latn
v1.0/kpe-Latn
v1.0/kpf-Latn
v1.0/kpg-Latn
v1.0/kpj-Latn
v1.0/kpo-Latn
v1.0/kpr-Latn
v1.0/kpv-Cyrl
v1.0/kpw-Latn
v1.0/kpx-Latn
v1.0/kqc-Latn
v1.0/kqf-Latn
v1.0/kqn-Latn
v1.0/kqw-Latn
v1.0/krc-Cyrl
v1.0/kri-Latn
v1.0/krl-Latn
v1.0/kru-Deva
v1.0/ksd-Latn
v1.0/ksh-Latn
v1.0/ksr-Latn
v1.0/ksw-Mymr
v1.0/ktm-Latn
v1.0/kto-Latn
v1.0/ktu-Latn
v1.0/ktz-Latn
v1.0/kua-Latn
v1.0/kum-Cyrl
v1.0/kup-Latn
v1.0/kvg-Latn
v1.0/kwf-Latn
v1.0/kwj-Latn
v1.0/kwn-Latn
v1.0/kwy-Latn
v1.0/kyc-Latn
v1.0/kyg-Latn
v1.0/kyq-Latn
v1.0/kyu-Kali
v1.0/kyu-Latn
v1.0/kyz-Latn
v1.0/kze-Latn
v1.0/kzf-Latn
v1.0/kzj-Latn
v1.0/lad-Latn
v1.0/laj-Latn
v1.0/lam-Latn
v1.0/lao-Laoo
v1.0/lat-Latn
v1.0/lbb-Latn
v1.0/lbe-Cyrl
v1.0/lbj-Tibt
v1.0/lbk-Latn
v1.0/lcm-Latn
v1.0/leu-Latn
v1.0/lew-Latn
v1.0/lex-Latn
v1.0/lez-Cyrl
v1.0/lfn-Cyrl
v1.0/lfn-Latn
v1.0/lgg-Latn
v1.0/lgl-Latn
v1.0/lhi-Latn
v1.0/lia-Latn
v1.0/lid-Latn
v1.0/lif-Deva
v1.0/lif-Limb
v1.0/lij-Latn
v1.0/lim-Latn
v1.0/lin-Latn
v1.0/lis-Lisu
v1.0/lit-Latn
v1.0/liv-Latn
v1.0/ljp-Latn
v1.0/lki-Arab
v1.0/lld-Latn
v1.0/llg-Latn
v1.0/lmk-Latn
v1.0/lmo-Latn
v1.0/lnd-Latn
v1.0/loz-Latn
v1.0/lrc-Arab
v1.0/lsi-Latn
v1.0/ltg-Latn
v1.0/ltz-Latn
v1.0/lua-Latn
v1.0/lub-Latn
v1.0/lud-Latn
v1.0/lue-Latn
v1.0/lug-Latn
v1.0/lun-Latn
v1.0/luo-Latn
v1.0/lus-Latn
v1.0/lvs-Latn
v1.0/lwg-Latn
v1.0/lww-Latn
v1.0/lzh-Hani
v1.0/maa-Latn
v1.0/mad-Latn
v1.0/mag-Deva
v1.0/mah-Latn
v1.0/mai-Deva
v1.0/mak-Latn
v1.0/mal-Latn
v1.0/mal-Mlym
v1.0/mam-Latn
v1.0/mar-Deva
v1.0/mar-Latn
v1.0/mas-Latn
v1.0/mau-Latn
v1.0/maw-Latn
v1.0/maz-Latn
v1.0/mbb-Latn
v1.0/mbf-Latn
v1.0/mbh-Latn
v1.0/mbs-Latn
v1.0/mbt-Latn
v1.0/mcd-Latn
v1.0/mck-Latn
v1.0/mcq-Latn
v1.0/mdf-Cyrl
v1.0/mdy-Ethi
v1.0/med-Latn
v1.0/mej-Latn
v1.0/mek-Latn
v1.0/men-Latn
v1.0/met-Latn
v1.0/meu-Latn
v1.0/mfe-Latn
v1.0/mfi-Latn
v1.0/mfq-Latn
v1.0/mfy-Latn
v1.0/mge-Latn
v1.0/mgh-Latn
v1.0/mhi-Latn
v1.0/mhr-Cyrl
v1.0/mhw-Latn
v1.0/mhx-Latn
v1.0/mic-Latn
v1.0/mie-Latn
v1.0/mif-Latn
v1.0/min-Latn
v1.0/mip-Latn
v1.0/miq-Latn
v1.0/mjc-Latn
v1.0/mjw-Latn
v1.0/mkd-Cyrl
v1.0/mkn-Latn
v1.0/mlh-Latn
v1.0/mlt-Latn
v1.0/mmo-Latn
v1.0/mmx-Latn
v1.0/mna-Latn
v1.0/mnb-Latn
v1.0/mni-Beng
v1.0/mni-Latn
v1.0/mni-Mtei
v1.0/mnk-Latn
v1.0/mns-Cyrl
v1.0/mnw-Mymr
v1.0/moc-Latn
v1.0/mog-Latn
v1.0/moh-Latn
v1.0/mos-Latn
v1.0/mph-Latn
v1.0/mpm-Latn
v1.0/mpp-Latn
v1.0/mps-Latn
v1.0/mpx-Latn
v1.0/mqj-Latn
v1.0/mqy-Latn
v1.0/mri-Latn
v1.0/mrj-Cyrl
v1.0/mrw-Latn
v1.0/msb-Latn
v1.0/msc-Latn
v1.0/msk-Latn
v1.0/msy-Latn
v1.0/mtg-Latn
v1.0/mti-Latn
v1.0/muh-Latn
v1.0/mui-Latn
v1.0/mup-Deva
v1.0/mur-Latn
v1.0/mux-Latn
v1.0/mva-Latn
v1.0/mvn-Latn
v1.0/mvp-Latn
v1.0/mwc-Latn
v1.0/mwf-Latn
v1.0/mwl-Latn
v1.0/mwm-Latn
v1.0/mwn-Latn
v1.0/mwp-Latn
v1.0/mwv-Latn
v1.0/mww-Latn
v1.0/mxb-Latn
v1.0/mxt-Latn
v1.0/mxv-Latn
v1.0/mxx-Latn
v1.0/mya-Mymr
v1.0/myb-Latn
v1.0/myk-Latn
v1.0/myu-Latn
v1.0/myv-Cyrl
v1.0/myw-Latn
v1.0/myy-Latn
v1.0/mza-Latn
v1.0/mzh-Latn
v1.0/mzn-Arab
v1.0/naf-Latn
v1.0/nah-Latn
v1.0/nak-Latn
v1.0/nan-Latn
v1.0/nap-Latn
v1.0/naq-Latn
v1.0/nas-Latn
v1.0/nav-Latn
v1.0/nbc-Latn
v1.0/nbe-Latn
v1.0/nbl-Latn
v1.0/nbu-Latn
v1.0/nca-Latn
v1.0/nch-Latn
v1.0/ncj-Latn
v1.0/ncx-Latn
v1.0/ndc-Latn
v1.0/nde-Latn
v1.0/ndo-Latn
v1.0/nds-Latn
v1.0/new-Deva
v1.0/nfa-Latn
v1.0/ngl-Latn
v1.0/ngu-Latn
v1.0/nhe-Latn
v1.0/nhg-Latn
v1.0/nhi-Latn
v1.0/nho-Latn
v1.0/nhr-Latn
v1.0/nhw-Latn
v1.0/nhx-Latn
v1.0/nia-Latn
v1.0/nif-Latn
v1.0/nii-Latn
v1.0/nij-Latn
v1.0/nin-Latn
v1.0/niu-Latn
v1.0/njm-Latn
v1.0/njn-Latn
v1.0/njz-Latn
v1.0/nld-Latn
v1.0/nlg-Latn
v1.0/nmf-Latn
v1.0/nmz-Latn
v1.0/nnb-Latn
v1.0/nnh-Latn
v1.0/nno-Latn
v1.0/nnp-Latn
v1.0/nnw-Latn
v1.0/nob-Latn
v1.0/nog-Cyrl
v1.0/non-Latn
v1.0/nop-Latn
v1.0/not-Latn
v1.0/nov-Latn
v1.0/nph-Latn
v1.0/npi-Deva
v1.0/npi-Latn
v1.0/npy-Latn
v1.0/nqo-Nkoo
v1.0/nrm-Latn
v1.0/nsa-Latn
v1.0/nsn-Latn
v1.0/nso-Latn
v1.0/nss-Latn
v1.0/nst-Latn
v1.0/nsu-Latn
v1.0/ntp-Latn
v1.0/ntu-Latn
v1.0/nuj-Latn
v1.0/nus-Latn
v1.0/nuy-Latn
v1.0/nvm-Latn
v1.0/nwi-Latn
v1.0/nya-Latn
v1.0/nyk-Latn
v1.0/nyn-Latn
v1.0/nyu-Latn
v1.0/nyy-Latn
v1.0/nzi-Latn
v1.0/nzm-Latn
v1.0/obo-Latn
v1.0/oci-Latn
v1.0/ojb-Cans
v1.0/ojb-Latn
v1.0/okv-Latn
v1.0/olo-Latn
v1.0/omb-Latn
v1.0/omw-Latn
v1.0/ong-Latn
v1.0/opm-Latn
v1.0/orv-Cyrl
v1.0/ory-Latn
v1.0/ory-Orya
v1.0/oss-Cyrl
v1.0/ota-Arab
v1.0/otd-Latn
v1.0/ote-Latn
v1.0/ots-Latn
v1.0/otw-Latn
v1.0/pad-Latn
v1.0/pag-Latn
v1.0/pam-Latn
v1.0/pan-Guru
v1.0/pan-Latn
v1.0/pao-Latn
v1.0/pap-Latn
v1.0/pau-Latn
v1.0/pbb-Latn
v1.0/pbt-Arab
v1.0/pcd-Latn
v1.0/pck-Latn
v1.0/pcm-Latn
v1.0/pdc-Latn
v1.0/pdt-Latn
v1.0/pfl-Latn
v1.0/pib-Latn
v1.0/pis-Latn
v1.0/pjt-Latn
v1.0/plg-Latn
v1.0/pls-Latn
v1.0/plt-Latn
v1.0/plu-Latn
v1.0/plw-Latn
v1.0/pma-Latn
v1.0/pmf-Latn
v1.0/pms-Latn
v1.0/pmx-Latn
v1.0/pnb-Arab
v1.0/pnt-Grek
v1.0/poe-Latn
v1.0/poh-Latn
v1.0/poi-Latn
v1.0/pol-Latn
v1.0/pon-Latn
v1.0/por-Latn
v1.0/pot-Latn
v1.0/ppk-Latn
v1.0/ppo-Latn
v1.0/pps-Latn
v1.0/prg-Latn
v1.0/ptp-Latn
v1.0/ptu-Latn
v1.0/pui-Latn
v1.0/pwg-Latn
v1.0/pwn-Latn
v1.0/qub-Latn
v1.0/quc-Latn
v1.0/quf-Latn
v1.0/qug-Latn
v1.0/quh-Latn
v1.0/qul-Latn
v1.0/qup-Latn
v1.0/quw-Latn
v1.0/quy-Latn
v1.0/quz-Latn
v1.0/qvc-Latn
v1.0/qvh-Latn
v1.0/qvi-Latn
v1.0/qvn-Latn
v1.0/qvs-Latn
v1.0/qvw-Latn
v1.0/qxl-Latn
v1.0/qxn-Latn
v1.0/qxo-Latn
v1.0/rad-Latn
v1.0/rap-Latn
v1.0/rar-Latn
v1.0/raw-Latn
v1.0/rcf-Latn
v1.0/rej-Latn
v1.0/rgu-Latn
v1.0/rhg-Latn
v1.0/ria-Latn
v1.0/rif-Latn
v1.0/rif-Tfng
v1.0/rjs-Deva
v1.0/rkb-Latn
v1.0/rmc-Latn
v1.0/rml-Latn
v1.0/rmn-Cyrl
v1.0/rmn-Latn
v1.0/rmo-Latn
v1.0/rmq-Latn
v1.0/rmy-Cyrl
v1.0/rmy-Latn
v1.0/rnl-Latn
v1.0/roh-Latn
v1.0/ron-Cyrl
v1.0/ron-Latn
v1.0/roo-Latn
v1.0/rop-Latn
v1.0/row-Latn
v1.0/rro-Latn
v1.0/rtm-Latn
v1.0/rue-Cyrl
v1.0/ruf-Latn
v1.0/rug-Latn
v1.0/run-Latn
v1.0/rup-Latn
v1.0/rus-Cyrl
v1.0/rwo-Latn
v1.0/sab-Latn
v1.0/sag-Latn
v1.0/sah-Cyrl
v1.0/san-Deva
v1.0/san-Latn
v1.0/sas-Latn
v1.0/sat-Latn
v1.0/sat-Olck
v1.0/sbd-Latn
v1.0/sbe-Latn
v1.0/scn-Latn
v1.0/sco-Latn
v1.0/sda-Latn
v1.0/sdc-Latn
v1.0/sdh-Arab
v1.0/seh-Latn
v1.0/ses-Latn
v1.0/sgb-Latn
v1.0/sgc-Latn
v1.0/sgh-Cyrl
v1.0/sgs-Latn
v1.0/sgw-Ethi
v1.0/shi-Latn
v1.0/shk-Latn
v1.0/shn-Mymr
v1.0/shp-Latn
v1.0/shu-Arab
v1.0/sid-Latn
v1.0/sil-Latn
v1.0/sim-Latn
v1.0/sin-Sinh
v1.0/skg-Latn
v1.0/skr-Arab
v1.0/slk-Latn
v1.0/sll-Latn
v1.0/slv-Latn
v1.0/sma-Latn
v1.0/sme-Latn
v1.0/smj-Latn
v1.0/smk-Latn
v1.0/sml-Latn
v1.0/smn-Latn
v1.0/smo-Latn
v1.0/sms-Latn
v1.0/sna-Latn
v1.0/snc-Latn
v1.0/snd-Arab
v1.0/snd-Deva
v1.0/snd-Latn
v1.0/snf-Latn
v1.0/snn-Latn
v1.0/snp-Latn
v1.0/snw-Latn
v1.0/sny-Latn
v1.0/som-Latn
v1.0/sop-Latn
v1.0/soq-Latn

In [ ]:
# Libraries
from huggingface_hub import snapshot_download
from datasets import load_dataset
import pandas as pd

In [ ]:
folder = snapshot_download(
    "cis-lmu/glotcc-v1",
    repo_type="dataset",
    local_dir="./path/to/glotcc-v1/",
    allow_patterns="v1.0/gcf-Latn/*"
)

dataset_glotcc_gcf = load_dataset("cis-lmu/glotcc-v1", name="gcf-Latn", split="train")

df_dataset_glotcc_gcf = dataset_glotcc_gcf.to_pandas()
df_gcf_glotcc = df_dataset_glotcc_gcf[df_dataset_glotcc_gcf.index <= 24]

print(df_gcf_glotcc.shape)
print(df_gcf_glotcc.head())

df_gcf_glotcc.to_csv("glotcc_gcf.csv", index=False)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/541 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/106 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/94 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/45 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/27 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/47 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/22 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

DataFrame shape: (25, 13)
DataFrame head:
                                             content  \
0  Popozision ki sòti nan Konsit LLKM za òganizé,...
1  Kantapou létjip Lafrans fanm, yo mennen bon mo...
2  Lanné 2017 ka komansé, lokazyon pou viré jété ...
3  ADN Awa !, 14 février 1952, 14 décembre 2010, ...
4  Lendi bonmaten, anlo moun té anrajé anlè lawou...

                                     warc-target-uri             warc-date  \
0  https://www.llkm.org/bretmo/lam%C3%A9t%C3%A9yo...  2024-03-01T01:07:20Z
1     https://potomitan.info/duranty/kreyolad395.php  2024-02-29T17:29:10Z
2               https://www.timalo.com/bye-bye-2016/  2024-02-28T20:28:03Z
3               https://ugtg.org/spip.php?article657  2024-02-22T23:42:45Z
4     https://potomitan.info/duranty/kreyolad592.php  2024-02-26T21:39:29Z

                                    warc-record-id           quality-warnings  \
0  <urn:uuid:4ff66a63-2d90-4f0d-9dc5-46963283798d>          [short_sentences]
1  <urn:uuid:5a7bc6a7-e4c9-44af-9fd4-e5f40e215bb8>  [footer, short_sentences]
2  <urn:uuid:53594eb8-9c6e-4024-b01e-107176a306d9>                   [header]
3  <urn:uuid:3c632070-bca0-4f71-b811-2183f1418fde>  [footer, short_sentences]
4  <urn:uuid:0703ddcb-3466-4020-af64-f4b88c50872f>  [footer, short_sentences]

  categories identification-language  identification-prob  \
0         []                gcf-Latn                 0.53
1         []                gcf-Latn                 0.73
2         []                gcf-Latn                 0.97
3         []                gcf-Latn                 0.60
4         []                gcf-Latn                 0.64

   identification-consistency  script-percentage  num-sents  content-length  \
0                        0.73               1.00         11            2648
1                        0.62               0.99         16            2402
2                        0.86               1.00         14            3251
3                        0.70               1.00         76           13151
4                        0.64               1.00         14            2125

                                                tlsh
0  tlsh:T17DF5E5516412CE9B1FCF90E10A3A8FA450187A4...
1  tlsh:T196E154417444DF670BE742D1FCBEE98441707B5...
2  tlsh:T1D4AF996141A0CBCB1FC320C25C1FDB90A828334...
3  tlsh:T1035F6F42E850DB8B0BCF22C3642FEE11046832A...
4  tlsh:T1BFF24F4197D4E7C70FD762E1683AAE8404A02B6...

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 0 to 24
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   content                     25 non-null     object
 1   warc-target-uri             25 non-null     object
 2   warc-date                   25 non-null     object
 3   warc-record-id              25 non-null     object
 4   quality-warnings            25 non-null     object
 5   categories                  25 non-null     object
 6   identification-language     25 non-null     object
 7   identification-prob         25 non-null     float64
 8   identification-consistency  25 non-null     float64
 9   script-percentage           25 non-null     float64
 10  num-sents                   25 non-null     int64
 11  content-length              25 non-null     int64
 12  tlsh                        25 non-null     object
dtypes: float64(3), int64(2), object(8)
memory usage: 2.7+ KB

In [ ]:
df_gcf_glotcc

,content,warc-target-uri,warc-date,warc-record-id,quality-warnings,categories,identification-language,identification-prob,identification-consistency,script-percentage,num-sents,content-length,tlsh
0,"Popozision ki sòti nan Konsit LLKM za òganizé,...",https://www.llkm.org/bretmo/lam%C3%A9t%C3%A9yo...,2024-03-01T01:07:20Z,<urn:uuid:4ff66a63-2d90-4f0d-9dc5-46963283798d>,[short_sentences],[],gcf-Latn,0.53,0.73,1.00,11,2648,tlsh:T17DF5E5516412CE9B1FCF90E10A3A8FA450187A4...
1,"Kantapou létjip Lafrans fanm, yo mennen bon mo...",https://potomitan.info/duranty/kreyolad395.php,2024-02-29T17:29:10Z,<urn:uuid:5a7bc6a7-e4c9-44af-9fd4-e5f40e215bb8>,"[footer, short_sentences]",[],gcf-Latn,0.73,0.62,0.99,16,2402,tlsh:T196E154417444DF670BE742D1FCBEE98441707B5...
2,"Lanné 2017 ka komansé, lokazyon pou viré jété ...",https://www.timalo.com/bye-bye-2016/,2024-02-28T20:28:03Z,<urn:uuid:53594eb8-9c6e-4024-b01e-107176a306d9>,[header],[],gcf-Latn,0.97,0.86,1.00,14,3251,tlsh:T1D4AF996141A0CBCB1FC320C25C1FDB90A828334...
3,"ADN Awa !, 14 février 1952, 14 décembre 2010, ...",https://ugtg.org/spip.php?article657,2024-02-22T23:42:45Z,<urn:uuid:3c632070-bca0-4f71-b811-2183f1418fde>,"[footer, short_sentences]",[],gcf-Latn,0.60,0.70,1.00,76,13151,tlsh:T1035F6F42E850DB8B0BCF22C3642FEE11046832A...
4,"Lendi bonmaten, anlo moun té anrajé anlè lawou...",https://potomitan.info/duranty/kreyolad592.php,2024-02-26T21:39:29Z,<urn:uuid:0703ddcb-3466-4020-af64-f4b88c50872f>,"[footer, short_sentences]",[],gcf-Latn,0.64,0.64,1.00,14,2125,tlsh:T1BFF24F4197D4E7C70FD762E1683AAE8404A02B6...
5,House of Àṣẹ (pwononsé a-ché) sé on koté èspés...,https://www.houseofase.com/gp/,2024-02-29T23:58:27Z,<urn:uuid:a6499e62-8373-4535-806a-50016e48b78f>,[short_sentences],[],gcf-Latn,0.86,0.62,1.00,8,1069,tlsh:T1CE96A411F041E10657C802E8653EEA402629248...
6,An ay fè on lantou Brisèl é an pa vwè pon-on m...,https://www.timalo.com/timalo-an-beljik/,2024-02-28T18:24:06Z,<urn:uuid:78f7cb3e-574e-4fa3-8412-d32dfb4b5a83>,[],[],gcf-Latn,0.99,1.00,0.99,7,1970,tlsh:T18C3710417651D3DB0B8F71D7182BEFC9583872C...
7,Cette nouvelle lecture devrait se faire aiséme...,http://creoles.free.fr/Cours/tichika.htm,2024-02-28T02:13:28Z,<urn:uuid:124db539-144b-4dbd-978b-cc66f5c214f7>,[],[],gcf-Latn,0.86,0.95,1.00,41,8870,tlsh:T1FC65B6028673D78B2FCB11C2152DEF88852C298...
8,Dimanch pasé tout moun té douvan télé-yo pou t...,https://potomitan.info/duranty/kreyolad955.php,2024-02-26T22:16:57Z,<urn:uuid:1ce24461-055e-4faa-9172-39fb6b3a6729>,"[footer, short_sentences]",[],gcf-Latn,0.65,0.60,1.00,15,2063,tlsh:T18D7E3F417291CBBB2DD611F6382EED914C74228...
9,Aaaah arrété fè mwen chié dé labiè mwen brè Ou...,https://www.lyricsmania.com/an_kou_tombe_lyric...,2024-03-03T05:53:59Z,<urn:uuid:a4792ef2-6bd6-4aa0-ac49-8d3ff21d3bc9>,[],[],gcf-Latn,0.53,1.00,1.00,2,2213,tlsh:T1FB8C1E41F125EBDA27EB0AF29D29E5181958169...
10,Lasimenn pasé té ja ka ba’y nef jou moun té ka...,https://potomitan.info/duranty/kreyolad538.php,2024-03-01T21:17:20Z,<urn:uuid:870e3235-dc6a-4128-9f2c-bb39511e5695>,"[footer, header, short_sentences]",[],gcf-Latn,0.50,0.62,0.99,16,2107,tlsh:T15F77094155E1E71807DB43D1A57D8E4818242B9...
11,"ADN Awa !, 14 février 1952, 14 décembre 2010, ...",http://ugtg.org/spip.php?article657,2024-02-21T00:39:47Z,<urn:uuid:73f6a395-f788-44df-a106-89966e9ff536>,"[footer, short_sentences]",[],gcf-Latn,0.61,0.69,1.00,77,13057,tlsh:T118919342F850DB8B0BCF22C3642FEE11046832A...
12,"Popozision ki sòti nan Konsit LLKM za òganizé,...",https://www.llkm.org/kontak/,2024-03-01T02:04:18Z,<urn:uuid:d759bbd2-ee8e-452b-9934-be6e5e6499cc>,[short_sentences],[],gcf-Latn,0.53,0.73,1.00,11,2648,tlsh:T17DF5E5516412CE9B1FCF90E10A3A8FA450187A4...
13,Sé nan lanné 1981 an éti an krey manmay ki té ...,http://www.latribunedesantilles.net/article/28...,2024-02-28T21:34:28Z,<urn:uuid:ef8a3177-3e13-4bb4-8be8-0edf0ebcbd5c>,[],[],gcf-Latn,0.68,0.88,0.99,8,7529,tlsh:T12A6E39F16151DB770FCF50E26AEF4B94A814074...
14,"Senkan apré i pati an péyi san chapo, Neg fond...",https://potomitan.info/duranty/kreyolad476.php,2024-02-26T20:48:15Z,<urn:uuid:139c3f44-ce74-4fb9-a0e9-76be5f156041>,"[footer, short_sentences]",[],gcf-Latn,0.73,0.65,0.99,17,1717,tlsh:T1F7A8A13154D1DB070BCF92D1751FEFD00428268...
15,"Sé sa anlo moun ka mandé, mé sa vré, lè an bag...",https://potomitan.info/duranty/kreyolad730.php,2024-02-29T17:19:33Z,<urn:uuid:586b6a37-44bf-49c4-b606-7b0aea248447>,"[footer, short_sentences]",[],gcf-Latn,0.65,0.60,1.00,15,1788,tlsh:T1C50286318584FB431FDE10E22E7FDB508864338...
16,"« Manman, lagrev baré mwen, misié Michel pa lé...",https://www.llkm.org/mak-listw%C3%A8/f%C3%A9vr...,2024-03-01T02:17:13Z,<urn:uuid:573ff3d8-aaf7-4ee6-bb05-355928a2fb08>,[],[],gcf-Latn,0.73,0.74,1.00,23,5048,tlsh:T17A5674A19516DF9B2BCAA1E1196B9FD84028364...
17,"Magré mwa mas-la dit dépi lontan, ni anlo moun...",https://potomitan.info/duranty/kreyolad820.php,2024-02-26T21:57:02Z,<urn:uuid:d7bc313e-1118-408a-b470-506f714fdf24>,"[footer, short_sentences]",[],gcf-Latn,0.66,0.67,0.99,18,2092,tlsh:T132EA98415200EB6B2BCD45D16D3DAB78682832C...
18,"Le 22 septembre dernier, les amies et camarade...",https://www.nouvellesetincelles.fr/article/421...,2024-03-02T23:12:52Z,<urn:uuid:83a6517e-e63d-4e50-b0eb-0c159b6abbad>,[],[],gcf-Latn,0.53,0.64,0.99,11,3752,tlsh:T13EFC5A71A555D7902FF322824D2ECB590028714...
19,Cliquez ici pour aller directement à la méthod...,http://eritaj.org/bacs-creoles/preparation-a-l...,2024-02-26T20:58:56Z,<urn:uuid:29d52e56-ddb8-4ae1-9511-ca2abb04f812>,[],[],gcf-Latn,0.84,0.93,0.99,40,7654,tlsh:T144C163F173B4CF8B1FC610E3182E07746568134...
20,(extraits d'une interview de Katrin René-St-El...,http://creoles.free.fr/Cours/sainteloi.htm,2024-02-28T03:55:25Z,<urn:uuid:562f04fb-0019-43e2-bbc6-545fbdda11f6>,[],[],gcf-Latn,0.90,0.75,1.00,4,1308,tlsh:T1D861B621423097864FC117C1181D4D16F00433C...
21,"Apré on Bac Litérè an Gwadloup, an pasé dé lan...",http://traduction-multilingue.com/index_kr.php...,2024-02-25T08:12:50Z,<urn:uuid:8feb089a-6db5-4160-9a49-f8ffbab66c80>,[short_sentences],[],gcf-Latn,0.78,0.67,1.00,6,731,tlsh:T114DD2C01C041DA7B0BC520F5924E9154505477C...
22,"Misié té ka fè wol mò, pas anlo moun té lé tér...",https://potomitan.info/duranty/kreyolad380.php,2024-02-29T18:23:29Z,<urn:uuid:30147c2b-df12-4807-b2af-e9c3239b3a88>,"[footer, short_sentences]",[],gcf-Latn,0.71,0.62,0.99,13,1796,tlsh:T1E94C73310010EB8B0FEE52DB357ECE49841C230...
23,Luil ésansiyèl a vétivè (Vetiveria zizanioides...,https://phytochemia.com/en/2020/10/28/on-vetiv...,2024-02-28T22:35:33Z,<urn:uuid:3a921ba7-bed6-43e6-bda6-2274141a7d5f>,[],[],gcf-Latn,0.89,0.89,1.00,9,5128,tlsh:T1075232B184BAD7631FCF62E3652EDFA46518228...
24,"Pou moun ki ka di kréyòl pé pa maké, sa pa vré...",https://bokantajenes.alychouette.com/2019/10/0...,2024-02-28T00:14:37Z,<urn:uuid:5cda3993-438c-4213-a308-9c499ad13ea1>,"[footer, short_sentences]",[],gcf-Latn,0.77,0.84,0.98,19,2708,tlsh:T13A1361517721D7868FDEC1C61829DB78A268118...

##### b. ISO-code cgr (Guyanese)

In [ ]:
# Importation from HuggingFace of the train split (test split non-available) of the subset gcr_Latn of the corpus GlotCC
# This will fetch the Guyanese Creole resulting data
# Dataset limited to 13 documents

# Library already imported

# Importation
folder = snapshot_download(
    "cis-lmu/glotcc-v1",
    repo_type="dataset",
    local_dir="./path/to/glotcc-v1/",
    allow_patterns="v1.0/gcr-Latn/*" # Replaced "v1.0/bal-Arab/*" with the path for gcr language
)
# Loading
dataset_glotcc_gcr = load_dataset("cis-lmu/glotcc-v1", name="gcr-Latn", split="train")

# Reformating into DataFrame and limitation to 25 first rows
df_dataset_glotcc_gcr = dataset_glotcc_gcr.to_pandas()
df_gcr_glotcc = df_dataset_glotcc_gcr[df_dataset_glotcc_gcr.index <= 12]

# Check
print(df_gcr_glotcc.shape)
print(df_gcr_glotcc.head())

# Exportation into CSV files
df_gcr_glotcc.to_csv("glotcc_gcr.csv", index=False)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/541 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/106 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/94 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/45 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/27 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/47 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/22 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

(13, 13)
                                             content  \
0  Jupiter (senbòl : ) sa roun planèt jéyant gazé...
1  Hiver : kanpangn di Boleslas III Bouche-Torse,...
2  Friedrich Wilhelm Nietzsche (prounonsé [ˈfʁiːd...
3  Rock-a sa roun janr mizikal ki aparèt andan la...
4  Adi Shankara (sanskri : Ādi Śaṅkara, devanagar...

                                     warc-target-uri             warc-date  \
0  https://gcr.m.wikipedia.org/wiki/Jupiter_(plan...  2024-02-25T20:56:17Z
1                https://gcr.wikipedia.org/wiki/1119  2024-02-24T12:00:55Z
2  https://gcr.wikipedia.org/wiki/Friedrich_Nietz...  2024-02-28T06:10:18Z
3                https://gcr.wikipedia.org/wiki/Rock  2024-02-24T12:15:18Z
4        https://gcr.wikipedia.org/wiki/Adi_Shankara  2024-02-23T00:13:20Z

                                    warc-record-id   quality-warnings  \
0  <urn:uuid:137f1061-c5d1-458e-b06c-d73c06101ff1>                 []
1  <urn:uuid:898158f9-d647-4a3f-93ac-5e3722bad937>                 []
2  <urn:uuid:a9524872-4a39-451f-8eae-b889672b9619>  [short_sentences]
3  <urn:uuid:84ae1998-873b-4c47-baf0-4f84e9f180d9>  [short_sentences]
4  <urn:uuid:2b7fa70b-1c37-4559-a277-c4031949df68>  [short_sentences]

              categories identification-language  identification-prob  \
0  [liste_bu, wikipedia]                gcr-Latn                 1.00
1  [liste_bu, wikipedia]                gcr-Latn                 0.72
2  [liste_bu, wikipedia]                gcr-Latn                 0.60
3  [liste_bu, wikipedia]                gcr-Latn                 0.88
4  [liste_bu, wikipedia]                gcr-Latn                 0.83

   identification-consistency  script-percentage  num-sents  content-length  \
0                         1.0               0.98          3             608
1                         1.0               1.00          7            1668
2                         1.0               0.98          4            1079
3                         0.8               0.99          5            1020
4                         1.0               0.98          4            1047

                                                tlsh
0  tlsh:T1BB857FF002B5DA03C983E3A053C9CDD00E701AC...
1  tlsh:T1E24B9C318662BB0BBFCB13F29135CEC6B935398...
2  tlsh:T1A802921120665DDF2BDB067A4065DFD8943A2D0...
3  tlsh:T1DD17AE1102AE2F1A1FDB07B17432DF945A36374...
4  tlsh:T1A3F2721175259F8B4BDB17B3B233CFE2FE3F2E5...

In [ ]:
df_gcr_glotcc

,content,warc-target-uri,warc-date,warc-record-id,quality-warnings,categories,identification-language,identification-prob,identification-consistency,script-percentage,num-sents,content-length,tlsh
0,Jupiter (senbòl : ) sa roun planèt jéyant gazé...,https://gcr.m.wikipedia.org/wiki/Jupiter_(plan...,2024-02-25T20:56:17Z,<urn:uuid:137f1061-c5d1-458e-b06c-d73c06101ff1>,[],"[liste_bu, wikipedia]",gcr-Latn,1.00,1.00,0.98,3,608,tlsh:T1BB857FF002B5DA03C983E3A053C9CDD00E701AC...
1,"Hiver : kanpangn di Boleslas III Bouche-Torse,...",https://gcr.wikipedia.org/wiki/1119,2024-02-24T12:00:55Z,<urn:uuid:898158f9-d647-4a3f-93ac-5e3722bad937>,[],"[liste_bu, wikipedia]",gcr-Latn,0.72,1.00,1.00,7,1668,tlsh:T1E24B9C318662BB0BBFCB13F29135CEC6B935398...
2,Friedrich Wilhelm Nietzsche (prounonsé [ˈfʁiːd...,https://gcr.wikipedia.org/wiki/Friedrich_Nietz...,2024-02-28T06:10:18Z,<urn:uuid:a9524872-4a39-451f-8eae-b889672b9619>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.60,1.00,0.98,4,1079,tlsh:T1A802921120665DDF2BDB067A4065DFD8943A2D0...
3,Rock-a sa roun janr mizikal ki aparèt andan la...,https://gcr.wikipedia.org/wiki/Rock,2024-02-24T12:15:18Z,<urn:uuid:84ae1998-873b-4c47-baf0-4f84e9f180d9>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.88,0.80,0.99,5,1020,tlsh:T1DD17AE1102AE2F1A1FDB07B17432DF945A36374...
4,"Adi Shankara (sanskri : Ādi Śaṅkara, devanagar...",https://gcr.wikipedia.org/wiki/Adi_Shankara,2024-02-23T00:13:20Z,<urn:uuid:2b7fa70b-1c37-4559-a277-c4031949df68>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.83,1.00,0.98,4,1047,tlsh:T1A3F2721175259F8B4BDB17B3B233CFE2FE3F2E5...
5,Jen : èspédisyon di Saladin à lès-a di Jourdai...,https://gcr.wikipedia.org/wiki/1173,2024-02-24T12:03:33Z,<urn:uuid:d3dc7021-f522-4e59-bc02-7e5ef63698a4>,[],"[liste_bu, wikipedia]",gcr-Latn,0.89,1.00,1.00,6,1438,tlsh:T1E4969B219625FF0B478F03E32525DFD4513D3E1...
6,"Bahamas, an form long Commonwealth dé Bahamas,...",https://gcr.wikipedia.org/wiki/Bahamas,2024-02-28T07:32:32Z,<urn:uuid:461e2a75-922c-4024-88aa-071520fc2fc5>,[],"[liste_bu, wikipedia]",gcr-Latn,0.82,1.00,0.99,3,576,tlsh:T13F8172F0E1441F6F07FF0DD21312FED8F0390BE...
7,"10 mè : lanprò-a di Mali Kanga Moussa, ki pati...",https://gcr.wikipedia.org/wiki/1324,2024-02-24T12:32:05Z,<urn:uuid:ff428524-5579-4679-b1a6-500acff8bbe4>,[],"[liste_bu, wikipedia]",gcr-Latn,0.87,1.00,1.00,7,1290,tlsh:T1D48866214235AB1F4FDB53A2A072EFC5512D3A8...
8,"21 mè : dé navir fransé, ki koumandé pa August...",https://gcr.wikipedia.org/wiki/1620,2024-02-22T00:24:15Z,<urn:uuid:d4839e60-ef23-4be2-840b-574be7616445>,[],"[liste_bu, wikipedia]",gcr-Latn,0.82,1.00,1.00,5,1356,tlsh:T1012A99216367DF9A4BDB6B139432DFC55C2D25A...
9,26 jen : Palman ékosè-a ka ògtrwayé monnonpòl-...,https://gcr.wikipedia.org/wiki/1695,2024-02-23T01:21:04Z,<urn:uuid:95f580ed-90ea-478c-8ade-7a86af5fd1d5>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.81,1.00,1.00,7,1368,tlsh:T1A12E902166A37F5F47E727309125DFC995392D4...
10,Bondjé ka dézigné oun fika oben fòs souprenm k...,https://gcr.wikipedia.org/wiki/Bondj%C3%A9,2024-02-24T12:35:58Z,<urn:uuid:12cb09bf-c32a-4cda-a773-5853419b50d3>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.86,1.00,1.00,4,948,tlsh:T14133F0112112AF0A4FDB16621033DBD588293BC...
11,Jayinism-an oben jinism-an (du sanskrit : जैनम...,https://gcr.wikipedia.org/wiki/Jayinism,2024-02-28T23:16:57Z,<urn:uuid:77f039bb-034d-4cf4-8ddf-df9b46b29d75>,[short_sentences],"[liste_bu, wikipedia]",gcr-Latn,0.85,1.00,0.98,5,1057,tlsh:T10638B41142966E770FD7267D11329FA0303B3AD...
12,11 janvyé : tout koumèrs dirèk ant Filipin-yan...,https://gcr.wikipedia.org/wiki/1593,2024-02-28T23:04:43Z,<urn:uuid:775400df-d5b6-4391-be91-c7febaea1ed9>,[],"[liste_bu, wikipedia]",gcr-Latn,0.88,0.88,1.00,8,1598,tlsh:T121DE4E318617AF0B1FC707E26031DEF81435359...

##### c. ISO-code hat (Haitian)

In [ ]:
# Importation from HuggingFace of the train split (test split non-available) of the subset hat_Latn of the corpus GlotCC
# This will fetch the Haitian Creole resulting data
# Dataset limited to 13 documents

# Library already imported

# Importation
folder = snapshot_download(
    "cis-lmu/glotcc-v1",
    repo_type="dataset",
    local_dir="./path/to/glotcc-v1/",
    allow_patterns="v1.0/hat-Latn/*" # Replaced "v1.0/bal-Arab/*" with the path for hat language
)
# Loading
dataset_glotcc_hat = load_dataset("cis-lmu/glotcc-v1", name="hat-Latn", split="train")

# Reformating and limitations to the 25 first rows
df_dataset_glotcc_hat = dataset_glotcc_hat.to_pandas()
df_hat_glotcc = df_dataset_glotcc_hat[df_dataset_glotcc_hat.index <= 12]

# Print the first 5 rows of the dataset
print(df_hat_glotcc.shape)
print(df_hat_glotcc.head())

# Exportation into CSV files
df_hat_glotcc.to_csv("glotcc_hat.csv", index=False)

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/2591 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/541 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/106 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/94 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/90 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/45 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/27 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/47 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/39 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/22 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

(13, 13)
                                             content  \
0  AfrikaansAzərbaycanBahasa IndonesiaBasa jawabo...
1  Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...
2  Prezidan Joe Biden te byen resevwa lòt jou la ...
3  Ningbo Hongtai te etabli an 2004, ki chita nan...
4  Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...

                                     warc-target-uri             warc-date  \
0  https://mcc.is/ht?AA1FG=JJJ75QQQ&a=JJJ47QQQ&ac...  2024-03-02T10:29:51Z
1  https://www.wkkf.org/ht/news-and-media/article...  2024-03-01T19:51:08Z
2  https://editorials.voa.gov/a/partenarya-amerik...  2024-03-04T01:43:36Z
3                    http://ht.ecosrcplate.com/news/  2024-02-24T14:49:24Z
4  https://haitiancreole.nycvotes.org/how-to-vote...  2024-03-04T01:49:26Z

                                    warc-record-id  \
0  <urn:uuid:10a54a61-c46c-4b73-8fbf-398a659f2a88>
1  <urn:uuid:9136945c-7617-4654-a354-ea661feead03>
2  <urn:uuid:362bc10a-9ed5-4f2d-b8ce-bc357c4656a5>
3  <urn:uuid:c6b1817d-3685-48ab-9c65-531fec600f98>
4  <urn:uuid:6832b3aa-48f7-46fa-95e4-e0b88eb6ae7e>

                    quality-warnings categories identification-language  \
0  [footer, header, short_sentences]         []                hat-Latn
1                                 []         []                hat-Latn
2                                 []         []                hat-Latn
3  [footer, header, short_sentences]         []                hat-Latn
4  [footer, header, short_sentences]         []                hat-Latn

   identification-prob  identification-consistency  script-percentage  \
0                 0.68                        0.70               0.93
1                 1.00                        1.00               1.00
2                 1.00                        1.00               1.00
3                 0.91                        0.93               1.00
4                 0.94                        0.93               1.00

   num-sents  content-length  \
0         53            4528
1          5            1402
2          9            2481
3         68            7155
4         45            4962

                                                tlsh
0  tlsh:T1A5764B91D8F21E9255D3BAD10598E376A070369...
1  tlsh:T1360F91212255714B28DB36C14CEED3BFE135151...
2  tlsh:T1AA7E605163DABF713AD739C1A49EF3776231248...
3  tlsh:T11CD43FE1859825A637E33AD1F6DCF3379530515...
4  tlsh:T13B0B7DA1612E5B625DD3428A2849E65AA73102C...

In [ ]:
df_dataset_glotcc_hat

,content,warc-target-uri,warc-date,warc-record-id,quality-warnings,categories,identification-language,identification-prob,identification-consistency,script-percentage,num-sents,content-length,tlsh
0,AfrikaansAzərbaycanBahasa IndonesiaBasa jawabo...,https://mcc.is/ht?AA1FG=JJJ75QQQ&a=JJJ47QQQ&ac...,2024-03-02T10:29:51Z,<urn:uuid:10a54a61-c46c-4b73-8fbf-398a659f2a88>,"[footer, header, short_sentences]",[],hat-Latn,0.68,0.70,0.93,53,4528,tlsh:T1A5764B91D8F21E9255D3BAD10598E376A070369...
1,Pwogram Rechèch Agrikilti Nòdès ak Edikasyon (...,https://www.wkkf.org/ht/news-and-media/article...,2024-03-01T19:51:08Z,<urn:uuid:9136945c-7617-4654-a354-ea661feead03>,[],[],hat-Latn,1.00,1.00,1.00,5,1402,tlsh:T1360F91212255714B28DB36C14CEED3BFE135151...
2,Prezidan Joe Biden te byen resevwa lòt jou la ...,https://editorials.voa.gov/a/partenarya-amerik...,2024-03-04T01:43:36Z,<urn:uuid:362bc10a-9ed5-4f2d-b8ce-bc357c4656a5>,[],[],hat-Latn,1.00,1.00,1.00,9,2481,tlsh:T1AA7E605163DABF713AD739C1A49EF3776231248...
3,"Ningbo Hongtai te etabli an 2004, ki chita nan...",http://ht.ecosrcplate.com/news/,2024-02-24T14:49:24Z,<urn:uuid:c6b1817d-3685-48ab-9c65-531fec600f98>,"[footer, header, short_sentences]",[],hat-Latn,0.91,0.93,1.00,68,7155,tlsh:T11CD43FE1859825A637E33AD1F6DCF3379530515...
4,Si w bezwen èd pou w ranpli Bilten Vòt ou a ak...,https://haitiancreole.nycvotes.org/how-to-vote...,2024-03-04T01:49:26Z,<urn:uuid:6832b3aa-48f7-46fa-95e4-e0b88eb6ae7e>,"[footer, header, short_sentences]",[],hat-Latn,0.94,0.93,1.00,45,4962,tlsh:T13B0B7DA1612E5B625DD3428A2849E65AA73102C...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13571,2-Inik ak klasik konsepsyon: sak zepòl tandans...,http://ht.fusencraft.com/women-felt-summer-bag...,2023-09-25T12:30:39Z,<urn:uuid:63202657-9e7a-4743-82df-b4736dea7787>,[],[],hat-Latn,1.00,1.00,1.00,4,747,tlsh:T1DB6A4001656694BA6FFA73C582AC3A560380004...
13572,"Depi kreyasyon li 30 ane de sa, JUNBOM Group t...",http://ht.junbond.com/about-us/,2023-09-22T14:29:45Z,<urn:uuid:b9be6881-48f4-4040-aece-eaa8b86133d3>,"[footer, short_sentences]",[],hat-Latn,0.86,0.80,1.00,10,3273,tlsh:T165BB7C6174D0329D3DBABBE35DDDEA1B53B165F...
13573,Foto Achiv: Logo Intel la devan katye jeneral ...,https://www.voanouvel.com/a/7227542.html,2023-10-03T10:38:02Z,<urn:uuid:436cba5c-a8c0-4343-91cd-1bfc7e91a55f>,[],[],hat-Latn,0.91,0.75,1.00,8,1074,tlsh:T182009E1142B96E4239F31FC378A9FB094034910...
13574,"XZWD Slewing kote yo pote co, Ltd.se yon manif...",http://ht.xzwdslewing.com/customized-oem-rolle...,2023-09-24T13:30:47Z,<urn:uuid:116d09d2-9c2c-434e-94cd-736c591d8b2f>,"[footer, header, short_sentences]",[],hat-Latn,0.90,1.00,1.00,17,2681,tlsh:T17F2CCF5172D0198E7ED35A8B38DDE9A65A3148B...
13575,"Don Bosco se te yon prèt Italyen ak edikatè, f...",https://www.ioamogesu.com/ht/Sen-Jan-Bosco-ak-...,2023-09-30T22:23:15Z,<urn:uuid:978a55fd-40bc-4f34-8ac3-63473d11ad92>,[footer],[],hat-Latn,0.66,0.90,1.00,10,3167,tlsh:T1CE1C9151A67456062BC72ED9229DE7EAF530345...

### 3. Filtering and downlading MADLAD-400
##### a. ISO-code cgf (Guadeloupean / Martinican)

In [ ]:
!pip install "datasets==2.14.0"

Collecting datasets==2.14.0
  Downloading datasets-2.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (2.0.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (18.1.0)
Collecting dill<0.3.8,>=0.3.0 (from datasets==2.14.0)
  Downloading dill-0.3.7-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (3.7.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (0.70.16)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.11.1->datasets==2.14.0) (2025.3.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (3.13.5)
Collecting huggingface-hub<1.0.0,>=0.14.0 (from datasets==2.14.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.14.0) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.14.0) (1.24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets==2.14.0) (3.29.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets==2.14.0) (1.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets==2.14.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.14.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.14.0) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.14.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->datasets==2.14.0) (2026.5.20)
INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
Collecting multiprocess (from datasets==2.14.0)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
  Downloading multiprocess-0.70.18-py312-none-any.whl.metadata (7.5 kB)
  Downloading multiprocess-0.70.17-py312-none-any.whl.metadata (7.2 kB)
  Downloading multiprocess-0.70.15-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.14.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.14.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.14.0) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==2.14.0) (1.17.0)
Downloading datasets-2.14.0-py3-none-any.whl (492 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.2/492.2 kB 15.5 MB/s eta 0:00:00
Downloading dill-0.3.7-py3-none-any.whl (115 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 7.9 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 29.4 MB/s eta 0:00:00
Downloading multiprocess-0.70.15-py311-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 9.7 MB/s eta 0:00:00
Installing collected packages: dill, multiprocess, huggingface-hub, datasets
  Attempting uninstall: dill
    Found existing installation: dill 0.3.8
    Uninstalling dill-0.3.8:
      Successfully uninstalled dill-0.3.8
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.16
    Uninstalling multiprocess-0.70.16:
      Successfully uninstalled multiprocess-0.70.16
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.16.1
    Uninstalling huggingface_hub-1.16.1:
      Successfully uninstalled huggingface_hub-1.16.1
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.0.0 requires huggingface-hub<2.0,>=1.3.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed datasets-2.14.0 dill-0.3.7 huggingface-hub-0.36.2 multiprocess-0.70.15

In [ ]:
!pip install "fsspec==2023.9.2"

Requirement already satisfied: fsspec==2023.9.2 in /usr/local/lib/python3.12/dist-packages (2023.9.2)

In [ ]:
# Libraries

from datasets import load_dataset
import pandas as pd

In [ ]:
# Importation from HuggingFace of the clean split of the subset gcf of the corpus MADLAD-400
# Method: importation with dataset.load_dataset
# This will fetch the Guadeloupean/Martinican Creoles resulting data
# Dataset limited to 25 documents

# Importation
dataset_madlad_gcf_clean = load_dataset("allenai/madlad-400", "gcf", split="clean")

# Reformating into dataframe
df_dataset_madlad_gcf = pd.DataFrame(dataset_madlad_gcf_clean)

# Only keeping the 25 first rows
df_madlad_gcf = df_dataset_madlad_gcf[df_dataset_madlad_gcf.index <= 24]

# Check
print(df_madlad_gcf.shape)
print(df_madlad_gcf.head())

# Exportation into CSV files
df_madlad_gcf.to_csv("madlad_gcf.csv", index=False)

ValueError: Invalid pattern: '**' can only be an entire path component

##### b. ISO-code cgr (Guyanese)

In [ ]:
# Importation from HuggingFace of the clean split of the subset gcr of the corpus MADLAD-400
# Method: importation with dataset.load_dataset
# This will fetch the Guayanese Creole resulting data
# Dataset limited to 13 documents

# Library already imported

# Importation
dataset_madlad_gcr_clean = load_dataset("allenai/madlad-400", "gcr", split="clean[:15%]")

# Reformating into dataframe
df_dataset_madlad_gcr = pd.DataFrame(dataset_madlad_gcr_clean)

# Only keeping the 25 first rows
df_madlad_gcr = df_dataset_madlad_gcr[df_dataset_madlad_gcr.index <= 12]

# Check
print(df_madlad_gcr.shape)
print(df_madlad_gcr.head())

# Exportation into CSV files
df_madlad_gcr.to_csv("madlad_gcr.csv", index=False)

Resolving data files:   0%|          | 0/284074 [00:00<?, ?it/s]

FileNotFoundError: Couldn't find a dataset script at /content/allenai/madlad-400/madlad-400.py or any data file in the same directory. Couldn't find 'allenai/madlad-400' on the Hugging Face Hub either: FileNotFoundError: No (supported) data files or dataset script found in allenai/madlad-400.

In [ ]:
import requests

response = requests.get("https://huggingface.co/api/datasets/allenai/madlad-400/tree/main/data")
files = response.json()

for f in files:
    print(f["path"])

data/abt
data/ace
data/acf
data/ach
data/ada
data/adh
data/ady
data/af
data/agr
data/ahk
data/ak
data/akb
data/alt
data/alz
data/am
data/amu
data/ang
data/ann
data/ape
data/ar
data/arn
data/as
data/av
data/awa
data/ay
data/az
data/az_RU
data/ba
data/ban
data/bas
data/bbc
data/bci
data/be
data/ber
data/ber_Latn
data/bew
data/bg
data/bg_Latn
data/bgp
data/bho
data/bi
data/bik
data/bim
data/bm
data/bn
data/bn_Latn
data/bo
data/bqc
data/br
data/bru
data/brx
data/bs
data/bts
data/btx
data/bua
data/bum
data/bus
data/bzj
data/ca
data/cab
data/cac
data/cak
data/cbk
data/cce
data/ce
data/ceb
data/cfm
data/ch
data/chk
data/chm
data/chr
data/ckb
data/cnh
data/co
data/cr_Latn
data/crh
data/crs
data/cs
data/ctd_Latn
data/ctu
data/cuk
data/cv
data/cy
data/da
data/de
data/din
data/dje
data/djk
data/dln
data/doi
data/dov
data/dtp
data/dv
data/dwr
data/dyu
data/dz
data/ee
data/el
data/el_Latn
data/emp
data/en
data/enq
data/eo
data/es
data/et
data/eu
data/fa
data/ff
data/ffm
data/fi
data/fil
data/fip
data/fj
data/fo
data/fon
data/fr
data/frp
data/fy
data/ga
data/gag
data/gbm
data/gd
data/gl
data/gn
data/gof
data/gom
data/gom_Latn
data/gor
data/grc
data/gsw
data/gu
data/gu_Latn
data/gub
data/guc
data/guh
data/gui
data/gv
data/gvl
data/gym
data/ha
data/haw
data/he
data/hi
data/hi_Latn
data/hif
data/hil
data/hmn
data/hne
data/ho
data/hr
data/ht
data/hu
data/hui
data/hus
data/hvn
data/hy
data/iba
data/ibb
data/id
data/ify
data/ig
data/ilo
data/inb
data/is
data/iso
data/it
data/iu
data/ium
data/izz
data/ja
data/jac
data/jam
data/jiv
data/jv
data/jvn
data/ka
data/kaa
data/kaa_Latn
data/kac
data/kbd
data/kbp
data/kek
data/kg
data/kha
data/kj
data/kjg
data/kjh
data/kk
data/kl
data/km
data/kmb
data/kmz_Latn
data/kn
data/kn_Latn
data/knj
data/ko
data/koi
data/kos
data/krc
data/kri
data/ksd
data/ksw
data/ktu
data/ku
data/kum
data/kv
data/kw
data/kwi
data/ky
data/la
data/laj
data/lb
data/lg
data/lhu
data/ln
data/lo
data/lrc
data/lt
data/ltg
data/lu
data/lus
data/lv
data/mad
data/mag
data/mai
data/mak
data/mam
data/mas
data/maz
data/mbt
data/mdf
data/meo
data/meu
data/mfe
data/mg
data/mgh
data/mh
data/mi
data/min
data/miq
data/mk
data/mkn
data/ml
data/ml_Latn
data/mn
data/mni
data/mps
data/mqy
data/mr
data/mrj
data/mrw
data/ms
data/ms_Arab
data/ms_Arab_BN
data/msb
data/msi
data/msm
data/mt
data/my
data/myv
data/nan_Latn_TW
data/ndc_ZW
data/ne
data/new
data/ngu
data/nhe
data/nia
data/nij
data/niq
data/nl
data/nnb
data/no
data/noa
data/nog
data/nr
data/nso
data/nut
data/nv
data/ny
data/nyu
data/nzi
data/oc
data/oj
data/om
data/or
data/os
data/otq
data/pa
data/pag
data/pap
data/pau
data/pck
data/pis
data/pl
data/pon
data/ppk
data/ps
data/pt
data/qu
data/qub
data/quc
data/quf
data/quh
data/qup
data/quy
data/qvc
data/qvi
data/qvz
data/qxr
data/raj
data/rcf
data/rki
data/rm
data/rmc
data/rn
data/ro
data/rom
data/ru
data/ru_Latn
data/rw
data/rwo
data/sa
data/sah
data/sat_Latn
data/sd
data/sda
data/se
data/seh
data/sg
data/shn
data/shp
data/si
data/sja
data/sk
data/skr
data/sl
data/sm
data/smt
data/sn
data/so
data/spp
data/sq
data/sr
data/srm
data/srn
data/ss
data/st
data/stq
data/su
data/sus
data/suz
data/sv
data/sw
data/sxn
data/syr
data/ta
data/ta_Latn
data/tab
data/taj
data/tbz
data/tca
data/tcy
data/tdx
data/te
data/te_Latn
data/teo
data/tet
data/tg
data/th
data/ti
data/tiv
data/tk
data/tks
data/tlh
data/tll
data/tly_IR
data/tn
data/to
data/toj
data/tr
data/trp
data/ts
data/tsc
data/tsg
data/tt
data/tuc
data/tvl
data/twu
data/tyv
data/tyz
data/tzh
data/tzj
data/tzo
data/ubu
data/udm
data/ug
data/uk
data/ur
data/uz
data/ve
data/vec
data/vi
data/wa
data/wal
data/war
data/wo
data/xal
data/xh
data/yap
data/yi
data/yo
data/yua
data/zap
data/zh
data/zh_Latn
data/zne
data/zu
data/zxx_xx_dtynoise
data/zza

##### c. ISO-code hat (Haitian)